### ISSUE TITLE
error ENOENT while installing on Android

### ISSUE THREAD

**Issue by xhanrot** [mickael-kerjean/filestash#104]
At the end of the Android installation, I get the following message :

> Error: ENOENT: no such file or directory, open '/data/data/com.termux/files/usr/share/nuage/config_client.js'

Installation done, following the steps described in the documentation : 

- install and launch Termux
- apt update
- apt install curl
- curl -L https://link.kerjean.me/nuage_install_termux | bash

Phone : OnePlus 5, unrooted.

**Comment by mickael-kerjean** [comment]
The installer hasn't been maintained for a while and a lot has change since this was created. Either somebody will take over when it comes to installation on Android (pull request welcome) or it will wait until I can put my hands on a Android phone as I broke mine several weeks ago.
