### ISSUE TITLE
Alternative Docker approach

### ISSUE THREAD

**Issue by Lewiscowles1986** [mickael-kerjean/filestash#105]
Would you accept a PR to turn the Dockerfile into a multi-stage with the build separated from the production image?

It should simplify uninstalling, cache purging etc.

**Comment by mickael-kerjean** [comment]
I'm not very familiar with the benefits that this will bring but I'm a big proponent of simplifying.

On a different perspective, the Dockerfile brings the topic of distribution. Long term, the distribution will happen from a downloadable fat binary, not via Docker as this will make it really easy to perform an install and decrease the bareer to entry for installation (I've encounter a lot of people not willing to touch Docker at all for reason I failed to understand).

As of today, the Dockerfile is complex for the wrong reason: I couldn't manage to statically compile the program with the associated libraries ([libvips](https://github.com/mickael-kerjean/nuage/blob/master/docker/prod/Dockerfile#L9-L17) for image resizing and [libraw](https://github.com/mickael-kerjean/nuage/blob/master/docker/prod/Dockerfile#L18-L25) for DSLR image transcoding -> there's a factor 100 difference comparing the Golang equivalent to there highly dedicated C counterpart: the code is [here](https://github.com/mickael-kerjean/nuage/tree/master/server/services/images)).

**Comment by hoshsadiq** [comment]
Saw this on reddit super cool!

Regarding multistage docker image, it allows for separation of unnecessary stuff into a much simpler and smaller container. I can see a lot of extra stuff added (some of which not removed) that are simply not necessary for a production environment, and if anything, increase attack surface. Additionally, you don't need to worry about clean up (trust me when I say, even when you use the `--virtual` flag, there's still left over items).

The best thing however, is your finally docker image can in theory be a simply:

```
FROM scratch

COPY --from=builder /path/to/binary /usr/bin/binary
# copy any other items

ENTRYPOINT['/usr/bin/binary']
```

Which will obviously allow for even smaller overheads and smaller attack surface.

**Comment by Lewiscowles1986** [comment]
It can also help to make the image more secure using non-root users, which when combined with stripped down docker, and sane defaults as @hoshsadiq said can really dial down the distribution size of a docker image, and helps to codify build steps.

Thanks both for sharing, I'll try to catch up at weekend.

**Comment by mickael-kerjean** [comment]
> trust me when I say, even when you use the --virtual flag, there's still left over items

Hum, that's interesting, you prove your point.

> docker image can in theory be a simply
```
FROM scratch

COPY --from=builder /path/to/binary /usr/bin/binary
# copy any other items

ENTRYPOINT['/usr/bin/binary']
```
Ending up with such a simple Dockerfile is the dream. I've spent a couple of days attempting this but couldn't create a proper build. That's literally the only task while migrating the code base from NodeJS to Golang that I drop as I have to admit I'm not experience enough with GCC to get it done. If someone get any idea how to end up with this dream Dockerfile, please advise `:)`

**Comment by mickael-kerjean** [comment]
If someone is still interested in this:

1) the dockerfile has been updated recently. It now:
- [run under its own user](https://github.com/mickael-kerjean/filestash/blob/master/docker/prod/Dockerfile#L75-L78)
- [has a few more dependencies](https://github.com/mickael-kerjean/filestash/blob/master/docker/prod/Dockerfile#L52-L64) that are used for the [org mode export](https://orgmode.org/manual/Exporting.html)
2) "Would you accept a PR to turn the Dockerfile into a multi-stage with the build separated from the production image" => Yes
