### ISSUE TITLE
Regions other than us-east-1 are broken

### ISSUE THREAD

**Issue by wpuckering** [mickael-kerjean/filestash#112]
It seems like setting a different region other than us-east-1 does not work properly. I have a bucket in ca-central-1 which I can upload and delete files from just fine, but I can't edit a text file once uploaded to the bucket. I get the following error saying that the region is invalid:

![image](https://user-images.githubusercontent.com/3478486/47805433-8b2e5300-dcf4-11e8-931d-3d03126b681a.png)

A snippet of my configuration file showing that I have set my region to ca-central-1 is below:

![image](https://user-images.githubusercontent.com/3478486/47805557-d6e0fc80-dcf4-11e8-9948-5ef59d06f308.png)

Seems like this piece of code is the culprit:

![image](https://user-images.githubusercontent.com/3478486/47805711-34754900-dcf5-11e8-9b30-87371b448460.png)

**Comment by mickael-kerjean** [comment]
Thanks for the report! 
I'll try to fix somewhere next week.

**Comment by mickael-kerjean** [comment]
I wasn't able to replicate your error with a bucket in Canada. I'm not sure where did you get the full endpoint url from, can you try this:
```
    "connections": [
        {
            "type": "s3",
            "label": "S3",
            "access_key_id": "xxxxxxx",
            "secret_access_key": "xxxxxxx",
            "region": "ca-central-1",
            "advanced": false,
            "encryption_key": "",
            "endpoint": "",
            "path": "/bucket_name/"
        }
    ]
```

**Comment by mickael-kerjean** [comment]
Looks like problem solve in here. I'm closing but feel free to comment back and I'll reopen

**Comment by stefanoCaroli** [comment]
Hi, I'm trying to connect to a bucket in Europe (region: eu-west-1) but I am still experiencing the same error code:

![Screenshot 2019-10-15 at 13 16 38](https://user-images.githubusercontent.com/29304962/66826994-0e6ca700-ef4e-11e9-83c1-a5c7306d39f8.png)

Am I missing something in the configuration or is it just the same bug mentioned above?

**Comment by gianlucapisati** [comment]
Hi @mickael-kerjean same problem here, buckets different than us-east-1 seems not to be working

my connection string is like this:
"connections": [
        {
            "type": "s3",
            "label": "S3",
            "access_key_id": "xxxxxxx",
            "secret_access_key": "xxxxxxx",
            "region": "eu-west-1",
            "advanced": false,
            "encryption_key": "",
            "endpoint": "",
            "path": ""
        }
    ]

if i don't specify any path it loads the initial list of buckets, but then, when I open one bucket I receive the same error of @stefanoCaroli and @wpuckering

**Comment by mickael-kerjean** [comment]
Can someone send me a testing account from which I can try?

**Comment by mickael-kerjean** [comment]
I haven't received anything at all. I'm closing until there's enough information to act upon.

**Comment by TetrisBlack** [comment]
Hello,
I have the same issue with the region s3 bucket config. I wanted to test my assumption, but I couldn't get the backend to build on my machine, but could attach a debugger. Nevertheless, I think the problem lies in this line: 
https://github.com/mickael-kerjean/filestash/blob/625e0ed160aed76e991fe4e8061c3ba4790e75f2/server/plugin/plg_backend_s3/index.go#L439

It always results in an error. And overwriting the region. 
Something similar was discussed in here -> https://github.com/aws/aws-sdk-go/issues/720.

**Comment by jonasjancarik** [comment]
> EDIT: If you add "s3:GetBucketLocation" to your allowed actions. It works as well. Maybe add a list of minimum needed S3 Permissions?

I second that, adding "s3:GetBucketLocation" to allowed actions also fixed the issue for us.

**Comment by mickael-kerjean** [comment]
I still need a testing account to test this out, can you send one? email is in my profile

**Comment by jonasjancarik** [comment]
Do you mean an access key/secret key? I can't use our corporate one (for obvious reasons) but I'll try to sign up for a new AWS account at some point soon to teset this.
