### ISSUE TITLE
persistent database and config in docker

### ISSUE THREAD

**Issue by eleaner** [mickael-kerjean/filestash#113]
Hi,

I am playing with persistent volume in docker swarm using minio to store config and database.
I can create a volume and map it to nuage but only as a folder. (not a file)
At the moment I would have to store in this volume complete /app/data, that's probably too much.
Would you be able to separate the move the db.sql into a separate subfolder?
Also at the moment, I will have to have local copies of both mime.json and config.json
I am not sure if mime.json is not more like an internal configuration.

**Comment by mickael-kerjean** [comment]
> At the moment I would have to store in this volume complete /app/data .. both mime.json and config.json

Personally I have two things loaded as volume:
1) /app/data/config/config.json: which contains all sort of config stuff
2) /app/data/db.sql: which contains the data that's being shared

The rest is not necessary to persist as volume. As of today the build look like this:
```
|- cache (contains all sort of temporary data that can be delete at any time without problem)
|- config (the mime.json file is responsible for 2 things: 1) settings the mimeType of the server response which is the thing that the browser interpret to distinguish an image from some CSS for example. 2) used by the client to open the imageviewer on an image or the movie player on a movie. It could be used to disable say the editor feature on the client by setting all the "text/stuff" to "application/octet-stream"
|- public: the client code: just a bunch of html, css and JS that's pregzip
|- plugin: that one is very new. It's being used to change the server and add other features. For instance, today, there's [2 plugins available in the repo](https://github.com/mickael-kerjean/nuage/tree/master/server/plugin) (there's some more but the other one got developped for some very specific use cases that don't make sense for anybody else): image_light and image_heavy. image_light is the image transcoding that comes by default and image_heavy is a pure golang version of if that don't support many features and is very slow compared to the image_light (like at least 10 times slower) but pure golang (= easy installation without any system dependencies)
```

**Comment by eleaner** [comment]
I might be wrong but it looks like I can only bind files to the host
filesystem.
If I would like to use a volume to store the data (e.g. on minio cluster)
then it hast o be a complete folder
hence the question if you could move both files to dedicated folder(s)

**Comment by mickael-kerjean** [comment]
Docker can mount both folder and files inside the container.  I'm not sure what you mean here. What are you trying to achieve?

**Comment by eleaner** [comment]
It looks like one can use configs in docker swarm to make configuration files persistent
It's way better solution then what I wanted as it replicates to all manager nodes.
I am closing the issue.
