### ISSUE TITLE
Nuage will soon become Filestash

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/filestash#116]
As the project is growing, we will be changing the name of the project from Nuage to Filestash. The reasons are multifold:
1) avoid potential issues such as confusion with a product from Nokia named "nuage networks"
2) Position the application in line with the expectation of privacy activists
3) get a proper website with a proper domain: http://filestash.app (WIP at this point)

**Comment by Akito13** [comment]
I don't really understand point #2.

**Comment by mickael-kerjean** [comment]
@Akito13: I've received quite a lot of criticism while enabling by default the collection of data to some log server, see the [wiki](https://github.com/mickael-kerjean/filestash/wiki/Customisation#usage-statistics). This data has been used to fix quite a few technical glitches but the critics were loud and blessing to both me and the project. Long story short, the new version will have this specific log collection disabled by default with a new configuration screen that appear upon installation to enable/disable stuff easily without having to go through configuration files.

**Comment by Akito13** [comment]
@mickael-kerjean Okay, I agree with those privacy-conscious people, though I still don't quite understand how it is related to changing the project's name.
It is also interesting to see how you respond to user feedback.

**Comment by mickael-kerjean** [comment]
@Akito13: Change of name is a way for me to reboot the project and give it a new direction. A whole lot has change: telemetry on the new release has been disabled by default, a new admin console just appeared, shared links, export of org mode documents to a whole range of format (HTML, PDF, TXT, LATEX, MD and open office), new API to create plugins, a proper website, a lot of test, .... A proper release note will be created in the next few days, the software itself is 99.9% ready
