### ISSUE TITLE
Feature request: Make a Sandstorm package

### ISSUE THREAD

**Issue by properlypurple** [mickael-kerjean/filestash#118]
Sandstorm is a platform and set of software packages, to make it easy for people to set up self-hosted, open source apps. Their website is 
https://sandstorm.io/

Sandstorm allows one to package existing web apps in a way that allows it to run inside a Sanndstorm instance, and people can intall the app from their apps page, into their own Sandstorm instances. I think it's a great way to distribute Filestash.

They have packaging instructions here
https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

**Comment by mickael-kerjean** [comment]
Creating custom packages that are tailored for your environment and specific distribution is a perk that's available to my [Patreon](https://www.patreon.com/mickaelk) as packaging, maintaining and testing for every possible distribution is an extremely time consuming activity I have no plan on doing on my free time. In the meantime I would be glad to see other people creating and maintaining all possible distribution method from Sandstorm to Cloudron, Yunohost, Cozzy, Ubuntu, Debian, Gentoo, Arch Linux, Fedora, Centos, RHEL, ....

**Comment by properlypurple** [comment]
Thanks for the clarification @mickael-kerjean . I've started trying to get a Sandstorm package running, and will send in a pull request if it works out :)

**Comment by mickael-kerjean** [comment]
Sounds pretty good to me. 
I'm in the middle of setting up a brand new website for the project, if you make it work, feel free to send a pull request on [this page](https://www.filestash.app/docs/install-and-upgrade)
