### ISSUE TITLE
Feature request: Auto-login link

### ISSUE THREAD

**Issue by pauladams24** [mickael-kerjean/filestash#121]
It would be good if there was a way of generating a login link for Nuage / filestash to log in automatically, with the username, FTP host, password and initial directory ready set. 

I run a web hosting company and would like to provide Nuage as an FTP client, but would need this functionality.

**Comment by mickael-kerjean** [comment]
There's a few existing things that might be a fit for you:
1) Generate different share links for different people with authentication happening by email. The share at this point is a beta feature
2) [Configure](https://github.com/mickael-kerjean/filestash/wiki/Customisation#connection-page) the application to prefill whatever field you want. As an example, this instance is leveraging SFTP using ProFTPd with authentication using a LDAP directory: ![1](https://www.filestash.app/img/screenshots/feature3.png)
3) It's also possible for me to generate some custom build that are tailored for very specific use and maintain those build in parallel. As an example, I have some customers with this kind of setup:
    1. this instance is leveraging SFTP using openSSH and is access by the customers of a VPS vendor
<img width="847" alt="screen shot 2018-12-05 at 1 30 51 pm" src="https://user-images.githubusercontent.com/13233076/49486375-45841d80-f892-11e8-95f8-35744ecbd79a.png">There's also a few customisations in this application in term of branding and file edition that's not available yet in the open source version.
    2. Another installation where a  F500 company needed to integrate their single sign on with their installation so that their employees don't even have to login anywhere. Their instance has some other features that won't make their way on the open source project as they're highly specialised for their internal process

**Comment by pauladams24** [comment]
Out of these options, single sign on is by far the most practical for what I am looking to achieve. Ideally, I just wanted to be able to provide clients with a single link (for example filestack-install.example.com/login?ftpUser={{ftpUser}}&password={{ftppassword}}&initialDirectory={{initialDirectory}}) which would take them straight into the FTP manager, without having to login.

If this requires a custom install I could have a go at creating this myself, although wouldn't know where to start to be honest.

**Comment by pauladams24** [comment]
I currently use an FTP client called MonstaFTP but am finding it glitchy and it requires an expensive license as it is no longer open source. They provide a feature which allows you to login using a base64 encoded login link, perhaps filestack / nuage could have a similar functionality?

**Comment by mickael-kerjean** [comment]
> as it is no longer open source

Filestash will remain open source, there's no intention of closing the source code like MonstaFTP did. My plan to make the software profitable is to create a plugin marketplace that brings features that aren't of any interest for anybody else than a company: things like accessing an Oracle database/ a Microsoft SQL database, build a SAML layer on top of an existing backend, ....

> finding it glitchy and it requires an expensive license ... perhaps filestack / nuage could have a similar functionality?

It's definitely doable. To make it happen you can either:
1) Create a pull request, I will definitely merge this
2) Subscribe to the Patreon page. The 100$/month plan is made specifically for people who want support and specific features. This feature can definitely be part of this.

**Comment by SRugina** [comment]
I've been working on this for the past day. Pull request will be coming in about a week once I make sure it's stable. I'll also add an option to have the credentials be base64 encoded in the query parameter (so filestash will decode it)

**Comment by SRugina** [comment]
Hi, I've got it all to work on v2 of filestash (as I was able to easily run the nodeJS backend locally), but quite a few things have changed between v2 and v3, so it will take a while longer to make a pull request. If you want to integrate the code yourself, it is at: [https://github.com/SRugina/filestash-js](url), the main files changed were `client/connectpage.js` and `client/connectpage/form.js`. Specifically, the way the config file is used in the `form.js` has changed in such a way that the current code I have for auto-login links will not work.

**Comment by mickael-kerjean** [comment]
> I've got it all to work on v2 of filestash

Between v0.2 and now, a complete rewrite has happen. The entire backend you seem to be using is deprecated and won't receive any upgrade which if you're planning to use it in a production settings isn't ideal.

> If you want to integrate the code yourself,

I have my own roadmap and working on a completely different set of features. For example, i've sunk all my time working since 3 weeks on the creation of an admin console and a fully feature webdav server for shared links. I just don't have time to do a lot of extra work on things I have 0 use of. But again if you have a proper pull request, we can work out to merge it in here directly.

**Comment by SRugina** [comment]
I've been trying to get it to work with the latest filestash. After a few modifications, it still is not working. Right now, I just want to get sftp working and then add the rest. I've created this dummy javascript object for the authData: 

    var connections = [
                {
                label: "",
                type: "",
                hostname: "",
                username: "",
                password: "",
                advanced: true,
                path: "",
                port: null,
                passphrase: null,
                }
            ];

In the connectpage.js file. I fill in all the properties with getParam (I replaced the function with a `window.location.search` function) and then in the form.js in `componentDidMount()` I've added:

    if(this.props.submitVal == 1){

            //const authData = this.state.backends[this.state.select];
            const authData = this.props.authConn[0];

            const key = authData["type"]+"_"+authData["label"];

            this.props.credentials[key] = authData;
            this.props.onSubmit(authData, this.props.credentials);
          }

The commented out code is what the onSubmit function does in form.js. I pass the filled in dummy authData as a prop called authConn, and have it so that another prop, submitVal, is set to 1 when getParam finds query parameters in the url.

Despite all this, the code does not work. It leads to a blue page with the git fork thing in the top right when I supply it with query parameters. I suspect the javascript dummy object I'm using is not correct. Could you perhaps give me a dummy json for the authData? Should I make a pull request with the code as is and fix it in a following commit?

Thanks in advance for any help,
Merry Christmas!

**Comment by mickael-kerjean** [comment]
As I was working on removing all the glue code between frontend and backend to generate the login form, I had to go through some refactoring and got that feature working mostly as a side effect of supporting some Oauth2 providers. The feature will be publish as soon as the refactoring will be complete. Essentially, it will look like this in the case of FTP:
```
http://demo.filestash.app/login?type=ftp&user=ftpuser&hostname=127.0.0.1&password=ftppassword&path=/root/
```

**Comment by SRugina** [comment]
Wonderful to hear, I eagerly await the release

**Comment by mickael-kerjean** [comment]
should be all working in the demo: 
```
https://demo.filestash.app/login?type=ftp&hostname=xxxx&username=xxxx&password=xxxx&path=/
```

**Comment by pauladams24** [comment]
Perfect! Thanks for this.

**Comment by mickael-kerjean** [comment]
A better option would be to use the link: https://demo.filestash.app/login#type=ftp&hostname=xxxx&username=xxxx&password=xxxx&path=/

**Comment by rinogo** [comment]
Thanks, @mickael-kerjean! Exactly what I needed as well. For the benefit of others, to point users directly to the root of an S3 bucket, try something like this:

https://demo.filestash.app/login#type=s3&access_key_id=(Access Key ID)&secret_access_key=(Secret Access Key)&path=/(Bucket Name)

**Comment by michaelcinquin** [comment]
Hi
this does work : https://demo.filestash.app/login#type=sftp&hostname=somehost&username=test&password=somepassword
… but on my filestash, used with passthrough authentication middleware (with username_and_password as provided by end user, and hostname configured in plugin ([plugin configuration](https://www.dropbox.com/s/opzuwuem99913wk/Screenshot%202023-08-07%20at%2015.39.19.png?dl=0)) , this does not work :
https://somefilestashdomain.com/login#username=test&password=somepassword
nor this
https://somefilestashdomain.com/login#type=sftp&username=test&password=somepassword
nor this
https://somefilestashdomain.com/login#type=sftp&hostname=sftphost.com&username=test&password=somepassword

any idea how I could get auto-login to work with pass-through middleware ?

**Comment by bgencacat** [comment]
> A better option would be to use the link: https://demo.filestash.app/login#type=ftp&hostname=xxxx&username=xxxx&password=xxxx&path=/

Does it still work?

**Comment by bgencacat** [comment]
I can't use it too.
`http://server-ip:8334/login?type=sftp&hostname=sftp-server-ip&port=26617&username=usrname&password=pass`

**Comment by kolserdav** [comment]
@mickael-kerjean,  it's still not working for S3?
