### ISSUE TITLE
Feature Request: Backblaze B2 Support

### ISSUE THREAD

**Issue by blackboxusa** [mickael-kerjean/filestash#122]
Feature Request: Backblaze B2 Support

**Comment by mickael-kerjean** [comment]
It's definitely doable but I don't have the bandwidth to make it happen. You can either:
1) create a pull request with the feature, it will definitely be merged
2) support the project on Patreon, the high tier was made specifically to fit special use case like this

**Comment by mickael-kerjean** [comment]
I'm working on this as we speak. The connector won't be as feature full as the other ones as the API available from Backblaze is lacking in features, the most annoying one being the lack of file renaming

**Comment by mickael-kerjean** [comment]
To enable support for Backblaze: go to the admin console -> dashboard -> add backblaze, the code is available as a plugin: https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_backend_backblaze

There's a few problems with Backblaze as their API lacks quite a few important feature to be feature complete compared to other options:
1. You can't rename a file: that's a limit from their API
2. You can't move a file from a location to another one: that's a limit from their API
3. The file deletion is largely inefficient as you can't recursively delete file or even batch a delete request which if you're using Backblaze to manage thousands of files would generate thousands of requests

**Comment by rnkn** [comment]
Just FYI Backblaze has very recently added a copy/replace API: https://www.backblaze.com/b2/docs/b2_copy_file.html

**Comment by mickael-kerjean** [comment]
That's good news indeed. I would gladly accept a pull request for this as I am busy helping 
 my family getting though hard times

**Comment by rnkn** [comment]
I'm very sorry to hear about your family.

Go is on my list of languages to learn, so I'd be happy to take a look at this at some point.
