### ISSUE TITLE
apache rewrite rule shows blue page with latest filestash

### ISSUE THREAD

**Issue by SRugina** [mickael-kerjean/filestash#125]
Hi,

So I've successfully installed the latest filestash on my ubuntu server, and it works when visiting the IP w/ the port ([http://209.97.136.155:8334/](http://209.97.136.155:8334/)). However, when I switched my apache rewrite stuff to use port 8334 instead of the old 3000 I was using for filestash v0.2.1, the url that used to work now just gives me a blue page: [https://files.thecoderszone.com/](https://files.thecoderszone.com/). Why is this? Am I missing a configuration setting in filestash?

my apache rewrite rules that were working before but with port 8334: 
the conf file:

        ProxyPass / http://localhost:8334/
        ProxyPassReverse / http://localhost:8334/

the .htaccess file:

        RewriteEngine On
        RewriteRule ^$ http://127.0.0.1:8334/ [P,L]

Thanks in advance for any help

**Comment by mickael-kerjean** [comment]
At: https://files.thecoderszone.com/:
![image](https://user-images.githubusercontent.com/13233076/51147917-38564780-18b0-11e9-8bbe-5405e888c02f.png)
A lot of stuff are coming that are unrelated to filestash, stuff like google analytics that I don't have at all and a whole bunch of stuff coming from Cloudflare. I didn't spent any time to make sure filestash is compatible with whatever Cloudflare is injecting. Plus looking at how your page behaves, Cloudflare is doing all sort of stuff to the HTTP headers coming from the browser

If you compare to the one hosted at your IP:
![image](https://user-images.githubusercontent.com/13233076/51147834-dc8bbe80-18af-11e9-976b-4785aefae8cb.png)

My guess is if you disable Cloudflare on filestash, everything will be as expected

**Comment by SRugina** [comment]
Hi,

You were right about Cloudflare being the issue. We replaced it with let's encrypt for that subdomain. We also had to edit the server/middleware/http.go file to allow iframing for our use-case. 

It's all resolved now, thank you for your help!
