### ISSUE TITLE
[Discussion] Plan for Electron App

### ISSUE THREAD

**Issue by HannanAkbar** [mickael-kerjean/filestash#128]
Hi,

It would be great to have Electron app in the roadmap. :+1:

**Comment by mickael-kerjean** [comment]
Hello,

This raise an interesting question related to the creation of a desktop app. I'm quite open to contribute making something like this but some discussions needs to happen before as there's many different approaches

# what is the scope of the desktop application

- embed the server within the desktop app
- create a totally separate client

# which technology to use

I see a lot of debate around Electron with people making a lot of noise about how bad electron is when it comes to resource consumption. From my experience, I see another viable option that is to use a preinstalled chrome or chromium binary and launch a website in application mode. 
![image](https://user-images.githubusercontent.com/13233076/51817324-52ffd600-231e-11e9-9a0d-b92ffe108b74.png)
This provide less control than an Electron app but makes the installer size much smaller with the added benefit of not having to boot up another unnecessary instance of webkit

**Comment by fbartels** [comment]
Even better than electron would be to implement filestash as a pwa. This way all the packaging headaches can be avoided.

**Comment by mickael-kerjean** [comment]
@fbartels: This is already the case. Do you have some improvements in mind?

**Comment by fbartels** [comment]
@mickael-kerjean I must say I have not yet looked too deep into filestash, so I cannot say which points of https://developers.google.com/web/progressive-web-apps/ are already the case. one of the most obvious parts of a pwa are currently missing from filestash (like the app asking you if you want to install it locally).

Just wanted to provide some counter arguments against the need of Electron.

**Comment by AWalton** [comment]
I'd mainly like a desktop app for the ability to edit files on the local filesystem.
