### ISSUE TITLE
Tree unfolding when navigating in vim mode

### ISSUE THREAD

**Issue by alaq** [mickael-kerjean/filestash#130]
When navigating an org file in vim mode (with `j`/`k` for instance), folding is undone, all the content is displayed, instead of going to the next visible heading.

It seems to be [an issue in CodeMirror](https://github.com/codemirror/CodeMirror/issues/3951).

Meanwhile I believe a workaround could be possible, by remapping `j` to `gj` (move cursor by visual line).

This does not happen with the emacs keybindings.

**Comment by mickael-kerjean** [comment]
Thank you for the report. Can you send a pull request if you have a patch for this? I'm not a VIM user myself since I moved to emacs 10 years ago

**Comment by alaq** [comment]
Of course, will do.
