### ISSUE TITLE
Feature request: Progressive download / HTTP Streaming

### ISSUE THREAD

**Issue by grigio** [mickael-kerjean/filestash#131]
Thanks for filestash!
When I try to play a big MP4 video it always starts from the beginning, you can't seek to the middle of the file. Do you think it would be possible to implement this feature at fweb server level?

https://en.wikipedia.org/wiki/Progressive_download

this Go web server seems to have this feature https://github.com/philippgille/serve

**Comment by grigio** [comment]
Sorry I didn't noticed it already is working in that way

**Comment by mickael-kerjean** [comment]
Indeed that would make a great addition to the project. I initially assume those type of features were the value behind HLS, hopefully I was wrong. 

> Do you think it would be possible to implement this feature at fweb server level?

Yes it is. It is not trivial as some backend don't natively support it. For backend that can't support it, it would be perfectly fine to download the entire content and cache it, using the cache version for everything that's relate to progressive download

**Comment by mickael-kerjean** [comment]
This should now be all good. Let me know if you're having issues there

**Comment by grigio** [comment]
OMG! Thanks it works

**Comment by mickael-kerjean** [comment]
Yes it does and thank you for making me discover the world of HTTP range which I had no idea of before tackling this issue, quite an interesting world. 
This first implementation is far from perfect though, for example, RFC7233 speaks about multi range request that sounds pretty cool but as I haven't been able to trigger that behaviour from any of my testing, it's one of the things that's I've totally omit
