### ISSUE TITLE
Add SlickGrid as a grid-based DB editor

### ISSUE THREAD

**Issue by KyleFN** [mickael-kerjean/filestash#132]
I saw your /r/selfhosted comment earlier about an Airtable alternative and I thought you might be interested in [SlickGrid](https://github.com/6pac/SlickGrid). It's a highly scalable grid/spreadsheet-based data editor library and it can basically do [every feature](https://github.com/6pac/SlickGrid/wiki/Examples) I've seen in Airtable (e.g. [here's](https://6pac.github.io/SlickGrid/examples/example4-model.html) filtering, sorting, paging), it just needs the file manager-like functionality that you've already implemented. This would be excellent for viewing and editing databases quickly.

**Comment by mickael-kerjean** [comment]
Hello,

It looks like a cool tech but I fail to see both the value and how could this integrate within the project. If you want to discuss the idea further, please come over on IRC: #filestash, I'm trying to use Github only as a place for bug and feature request

**Comment by KyleFN** [comment]
On what IRC server? I can't find any other links on your website to the IRC channel.

**Comment by AsmoLab** [comment]
Good topic to open as alternatives are really becoming a thing, and more everyday.
At Zenkit, we were also looking for a good Airtable alternative, we then created our own free tool, we'd love to have your opinion:
https://zenkit.com/en/alternatives/Airtable-alternative/
