### ISSUE TITLE
Debian installation guide

### ISSUE THREAD

**Issue by higi** [mickael-kerjean/filestash#133]
Hello, 
is there guide to install it on clean Debian? Without Docker instalation.
are there any security tips?

THX

**Comment by mickael-kerjean** [comment]
Hello,

The overhead of maintaining everyone's favorite linux distro without docker would be too large for what is a hobby project without a team contributing on a regular basis. As a consequence there's 2 options:
1. become a customer (this can be one of the perks, see [here](https://www.filestash.app/pricing))
2. create and maintain the documentation from your side by submitting a pull request to the [documentation](https://www.filestash.app/docs/install-and-upgrade) and testing for every new debian release that nothing got broken

**Comment by mickael-kerjean** [comment]
> security tips

The project was designed to be safely exposed to the internet if needed. There's nothing to worry about when it comes to security

**Comment by higi** [comment]
There is: (without docker)
Getting started - Installation
Filestash can be used in different settings:
    Selfhosting (documentation): install it somewhere you have full control (with docker, without docker, on a server or even android)
-------------------------
So i was just thinking there is some kind of guide,. (sadly there is not) 

BTW how is security handeled? All traffic is encrypted? Is there possible "man in the middle" ? Some kind of fail2ban implemented?
What ports are need to be allowed?

anyway THX for quick update all of u:)
BTW good work with filestash looks great.

**Comment by mickael-kerjean** [comment]
The wiki hasn't been totally migrated to the new website yet: https://www.filestash.app/docs/install-and-upgrade We had some other installation target that got broken alongside upgrade (Android and Ubuntu), maintaining those is a pain and definitely not a hobby of mine.

> BTW how is security handeled?

A lot of measures are set up by the server, for example:
- [http only cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)
- no external libraries are loaded unless the code has been fully read
- proper [content security policy](https://en.wikipedia.org/wiki/Content_Security_Policy)
- disable loading though iframe to remove all sort of nasty attack vector
- disable browsers behavior to sniff content mime type
- enable the browser feature to detect and block other potential XSS
- HSTS (to force SSL) can be enable from a switch toggle within the admin interface
- browser origin is check to make that no external website can trick a user into performing undesirable actions into his instance
- credentials aren't store anywhere on the server (except while using the share feature where those are encrypted and can't be read without the key)
- credentials are store in your browser cookie where it is both encrypted and can't be tampered with (Authenticated encryption)
- all the features that requires encryption use a different encryption key so that even if an attacker finds one, the damage stays minimal

I think there's still a few other ones, those are just the one on top of my head

> All traffic is encrypted? Is there possible "man in the middle" ?

That's the role of SSL, for that the trick is to use Let's encrypt to generate your certificates. Also there's a plan (see upcoming features in the [project homepage](https://www.filestash.app/)) to automatically generate the SSL certificate.

> Some kind of fail2ban implemented?

No. I thought about it but couldn't see a way to make it work without affecting the performance (which is a major concern for the project). I guess the best approach for this is to use fail2ban itself and set it up correctly. From where I sit, it makes more sense to the block traffic at the firewall level than at the application level.

> What ports are need to be allowed?

8334 if you don't use a reverse proxy.

**Comment by higi** [comment]
got it somehow working:D going to send pull request

**Comment by mickael-kerjean** [comment]
> I want to put new logo on frontpage

There's no room for a logo in the frontpage

> move or hide some buttons etc.

What are you trying to achieve exactly, move which buttons, hide which ones? On the login page, we have a way to remove the remember me button, the link to the github repo and you can setup your instance to use as many backend as you want: example my personal SFTP: https://files.kerjean.me/login, also there's way to disable the share mechanism and search button.

> atleast how can i make Docker to build in from my repository. 

The build can be done in many different way if you want to go this way. To get something that best fit your need:
1. What are you trying to achieve? 
2. Is transcoding speed for images important for you?
3. Do you plan to use the feature to see RAW pictures?
3. Are you using the org mode features? (this one needs a few dependencies as well)

**Comment by higi** [comment]
this is how i got it working (a bit messy right now):

export CGO_LDFLAGS_ALLOW '-fopenmp'
 
wget https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz
tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz
export PATH=$PATH:/usr/local/go/bin
mkdir /opt/go
export GOPATH="/opt/go"


must have?:
apt-get install git
apt-get install build-essential
apt-get install curl
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
apt-get install -y nodejs
apt-get install pkg-config
apt-get install glib2.0-dev
apt-get install libexpat1-dev
apt-get install emacs
apt-get install texlive
apt-get install zip
apt-get install libtiff5-dev
apt-get install libpng-dev
apt-get install libgif-dev
apt-get install fftw-dev


maybe?:
apt-get install golang 
apt-get install libjbig-dev
apt-get install libexif-dev
apt-get install librsvg2-dev  tohle asi ne?
apt-get install libglib2.0-dev
apt-get install libc-dev
apt-get install libexpat1-dev 
apt-get install liborc-0.4-dev




mkdir /tmp/deps
cd /tmp/deps
curl -L -X GET https://github.com/libvips/libvips/releases/download/v8.7.0/vips-8.7.0.tar.gz > libvips.tar.gz
tar -zxf libvips.tar.gz
cd vips-8.7.0/
./configure
make -j 8


cd ..
curl -X GET https://www.libraw.org/data/LibRaw-0.19.0.tar.gz > libraw.tar.gz
tar -zxf libraw.tar.gz
cd LibRaw-0.19.0/
make -j 8
make install

cd /opt
git clone --depth 1 https://github.com/mickael-kerjean/filestash
cd filestash
mkdir -p ./dist/data/
mv config ./dist/data/
npm install
npm rebuild node-sass
NODE_ENV=production npm run build


cd /opt/filestash/server/
go get
go build -ldflags "-X /opt/filestash/server/common.BUILD_NUMBER=`date -u +%Y%m%d`" -o ./dist/filestash ./server/main.go


mkdir -p ./dist/data/plugin
go build -buildmode=plugin -o ./dist/data/plugin/image.so server/plugin/plg_image_light/index.go

**Comment by higi** [comment]
and my goal is: 
- secure access to file system (username/password) via web client
- remote (API?) creating users and theirs folders from another server (our application)
- uploading files and folders too
- web client has to be customizable

Crucial is web client, that already implements authentication and can be modified. Filestash

**Comment by mickael-kerjean** [comment]
Interesting, I happen to have a few customers whose has been building some interesting things as well using Filestash. What about we have a call to discuss what you need and how we can help? Say tomorrow at 04:30:00 UTC?

**Comment by higi** [comment]
Hey, can we meet on slack. My english is not good.)

**Comment by higi** [comment]
APP crashing, can u help pls? (after few minutes browsing SFTP)

`                   [detached from 20849.pts-1.storage]
root@storage:/app# screen -r
        /opt/go/src/golang.org/x/crypto/ssh/client.go:62 +0x33
created by golang.org/x/crypto/ssh.NewClient
        /opt/go/src/golang.org/x/crypto/ssh/client.go:61 +0xe5

goroutine 1193 [IO wait]:
internal/poll.runtime_pollWait(0x7fba1d099d60, 0x72, 0xc0004f8658)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000454518, 0x72, 0xffffffffffffff00, 0x13491e0, 0x1b58238)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000454518, 0xc0002b2100, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000454500, 0xc0002b21f1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000454500, 0xc0002b21f1, 0x1, 0x1, 0xc000042898, 0xc0004f8768, 0x7f3505)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e070, 0xc0002b21f1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc0002b21e0)
        /usr/local/go/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:672 +0xd2

goroutine 1196 [IO wait]:
internal/poll.runtime_pollWait(0x7fba1d099950, 0x72, 0xc0004fb658)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000454598, 0x72, 0xffffffffffffff00, 0x13491e0, 0x1b58238)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000454598, 0xc0002b2100, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000454580, 0xc0002b2131, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000454580, 0xc0002b2131, 0x1, 0x1, 0x7df9f1, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e078, 0xc0002b2131, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc0002b2120)
        /usr/local/go/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:672 +0xd2

goroutine 1197 [IO wait]:
internal/poll.runtime_pollWait(0x7fba1d099610, 0x72, 0xc0004fa658)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000144198, 0x72, 0xffffffffffffff00, 0x13491e0, 0x1b58238)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000144198, 0xc0000b3a00, 0x1, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000144180, 0xc0000b3ae1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000144180, 0xc0000b3ae1, 0x1, 0x1, 0xc00058c718, 0xc0004fa768, 0x7f3505)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000358030, 0xc0000b3ae1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc0000b3ad0)
        /usr/local/go/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:672 +0xd2
`

**Comment by higi** [comment]
i did send u invite to slack.
