### ISSUE TITLE
S3 | Access Status: Error

### ISSUE THREAD

**Issue by foundationalnotes** [mickael-kerjean/filestash#134]
After trying the demo the status changed on my S3 bucket to 'Error.'

Any ideas how to resolve this?

<img width="142" alt="screen shot 2019-02-19 at 12 14 13 am" src="https://user-images.githubusercontent.com/36466636/52992303-22233600-33de-11e9-8127-b9094dc65a0b.png">

<img width="311" alt="screen shot 2019-02-19 at 12 22 47 am" src="https://user-images.githubusercontent.com/36466636/52992357-53036b00-33de-11e9-90be-a825418bda1c.png">

**Comment by mickael-kerjean** [comment]
I have no idea what you're referring to, S3 is working fine from my end. Can you give more details:
- What do you refer as "status"?
- Where did you take those screenshots from?
- What does filestash tells you after connecting using your access key id and secret access key?

**Comment by foundationalnotes** [comment]
I will figure it out - S3 is working on my end too, accept for this "error" message on my AWS S3 console.

**Comment by 7404020** [comment]
Hi @foundationalnotes, did you work out how to show the status instead of "Error"? My users are getting the same thing.. Thanks
