### ISSUE TITLE
Can't sign in to google account

### ISSUE THREAD

**Issue by godwinsol** [mickael-kerjean/filestash#135]
I get the following message: 
"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

**Comment by mickael-kerjean** [comment]
Google drive requires some configuration to be set in the application before being used: [see the documentation](https://www.filestash.app/docs/configuration#configure-the-google-drive-connector)

**Comment by mickael-kerjean** [comment]
There's no action from my end here so I'll close the ticket. Feel free to comment back and I'll reopen
