### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by higi** [mickael-kerjean/filestash#137]
Testing random SFTP servers (https://www.wftpserver.com/onlinedemo.htm).
Everithing works great, but after few mins of browsing filestash crash:(
Last i see in console, are there any other logs? i see only /app/log/access.log 
Any steps how to debug crash?

/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000352780, 0xc0002b2761, 0x1, 0x1, 0x0, 0x0, 0x0)
       /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000352780, 0xc0002b2761, 0x1, 0x1, 0x7df9f1, 0x0, 0x0)
       /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e058, 0xc0002b2761, 0x1, 0x1, 0x0, 0x0, 0x0)
       /usr/local/go/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc0002b2750)
       /usr/local/go/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
       /usr/local/go/src/net/http/server.go:672 +0xd2

goroutine 283 [IO wait]:
internal/poll.runtime_pollWait(0x7f43b787b540, 0x72, 0xc000254e58)
       /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000144598, 0x72, 0xffffffffffffff00, 0x13491e0, 0x1b58238)
       /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000144598, 0xc0000b3b00, 0x1, 0x1)
       /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000144580, 0xc0000b3bd1, 0x1, 0x1, 0x0, 0x0, 0x0)
       /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000144580, 0xc0000b3bd1, 0x1, 0x1, 0xc000351118, 0xc000254f68, 0x7f3505)
       /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00024a078, 0xc0000b3bd1, 0x1, 0x1, 0x0, 0x0, 0x0)
       /usr/local/go/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc0000b3bc0)
       /usr/local/go/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
       /usr/local/go/src/net/http/server.go:672 +0xd2
/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0002712c0)
       /usr/local/go/src/sync/cond.go:56 +0x92
golang.org/x/crypto/ssh.(*mux).Wait(0xc0001262a0, 0x0, 0x0)
       /opt/go/src/golang.org/x/crypto/ssh/mux.go:110 +0x82
golang.org/x/crypto/ssh.NewClient.func1(0xc000242730)
       /opt/go/src/golang.org/x/crypto/ssh/client.go:62 +0x33
created by golang.org/x/crypto/ssh.NewClient
       /opt/go/src/golang.org/x/crypto/ssh/client.go:61 +0xe5

goroutine 29 [chan receive]:
golang.org/x/crypto/ssh.(*Session).wait(0xc00023a000, 0xc00019ade0, 0x7df9f1, 0x1b940a0)
       /opt/go/src/golang.org/x/crypto/ssh/session.go:423 +0x7a
golang.org/x/crypto/ssh.newSession.func1(0xc00023a000, 0xc00019ade0)
       /opt/go/src/golang.org/x/crypto/ssh/session.go:593 +0x35
created by golang.org/x/crypto/ssh.newSession
       /opt/go/src/golang.org/x/crypto/ssh/session.go:592 +0xb4

goroutine 86 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc000271350, 0xf)
       /usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc000271340)
       /usr/local/go/src/sync/cond.go:56 +0x92
golang.org/x/crypto/ssh.(*buffer).Read(0xc000167040, 0xc0004c40c8, 0x4, 0x4, 0x0, 0x0, 0x0)
       /opt/go/src/golang.org/x/crypto/ssh/buffer.go:94 +0x1d0
golang.org/x/crypto/ssh.(*channel).ReadExtended(0xc000144300, 0xc0004c40c8, 0x4, 0x4, 0x0, 0x13, 0x0, 0x0)
       /opt/go/src/golang.org/x/crypto/ssh/channel.go:351 +0x1f0
golang.org/x/crypto/ssh.(*channel).Read(0xc000144300, 0xc0004c40c8, 0x4, 0x4, 0x13, 0x0, 0x0)
       /opt/go/src/golang.org/x/crypto/ssh/channel.go:528 +0x60
io.ReadAtLeast(0x1346e20, 0xc00035b000, 0xc0004c40c8, 0x4, 0x4, 0x4, 0x10c3760, 0xc000079e01, 0xc0004c40c8)
       /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x1346e20, 0xc00035b000, 0xc0004c40c8, 0x4, 0x4, 0xc0002466c0, 0xc000079f70, 0xc000079ea0)
       /usr/local/go/src/io/io.go:329 +0x58
github.com/pkg/sftp.recvPacket(0x1346e20, 0xc00035b000, 0x787fe5, 0xc0002467e0, 0xc000079f70, 0x1, 0xe4b959, 0xc000172001)
       /opt/go/src/github.com/pkg/sftp/packet.go:142 +0x7b
github.com/pkg/sftp.(*conn).recvPacket(0xc00035b000, 0xc000079f70, 0xc00000000e, 0xc000172108, 0x1, 0x0, 0x0)
       /opt/go/src/github.com/pkg/sftp/conn.go:22 +0x37
github.com/pkg/sftp.(*clientConn).recv(0xc00035b000, 0x0, 0x0)
       /opt/go/src/github.com/pkg/sftp/conn.go:75 +0xdc
github.com/pkg/sftp.(*clientConn).loop(0xc00035b000)
       /opt/go/src/github.com/pkg/sftp/conn.go:60 +0x5b
created by github.com/pkg/sftp.NewClientPipe
       /opt/go/src/github.com/pkg/sftp/client.go:143 +0x1ef

goroutine 115 [runnable]:
net/http.(*connReader).backgroundRead(0xc0003ae2d0)
       /usr/local/go/src/net/http/server.go:675
created by net/http.(*connReader).startBackgroundRead
       /usr/local/go/src/net/http/server.go:672 +0xd2

goroutine 101 [runnable]:
net/http.(*connReader).backgroundRead(0xc000209710)
       /usr/local/go/src/net/http/server.go:675
created by net/http.(*connReader).startBackgroundRead
       /usr/local/go/src/net/http/server.go:672 +0xd2`

**Comment by higi** [comment]
crash is fixed now, by mutex commit.

THX

**Comment by mickael-kerjean** [comment]
I completely forgot to answer on here but yes the issue should have been fix quite a few weeks ago, let me know if you're still experiencing the same and we'll reopen

**Comment by higi** [comment]
THX amazing work, could u pls look in to https://github.com/mickael-kerjean/filestash-website/issues/4
