### ISSUE TITLE
[Feature request] Rich markdown editor with preview

### ISSUE THREAD

**Issue by moookino** [mickael-kerjean/filestash#139]
Hi @mickael-kerjean,

thanks for your great work!

I have a question if there is possibility to add rich markdown editor with wysiwyg and preview/presentation mode, smth like stackedit, hackmd/codimd, dillinger, hacker-slided, that would be really great, so users would be able to do all the stuff w/o need to spin or use another project, as you already have nice editor, it will be just enchantment of existing solution

**Comment by mickael-kerjean** [comment]
Nothing is impossible, you can pluck whatever component to deal with whatever file extension. However this will have to come from the community as I don't use markdown but org mode. 
If anyone is interested in a pull request, it will definitely be merged

**Comment by mickael-kerjean** [comment]
I have no plans to personally implement it this feature but would be happy to accept a pull request. we can re-open the issue if we have a volunteer for the work.
