### ISSUE TITLE
Docker image failed to launch

### ISSUE THREAD

**Issue by DecWebb** [mickael-kerjean/filestash#141]
I created the docker container on an Open Media Vault installation.

The log reported:
`standard_init_linux.go:178: exec user process caused "exec format error"`

Is it due to the architecture of the systems cpu?

The container details are:
> [
    {
        "Id": "6a39b124f04fd231a48242fb73826d0b7d8af1cfd31d893b9c4e1c0a7803617e",
        "Created": "2019-03-09T17:09:29.472684419Z",
        "Path": "/app/filestash",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2019-03-09T17:28:33.678108268Z",
            "FinishedAt": "2019-03-09T17:29:14.131557547Z"
        },
        "Image": "sha256:05c3faf40437e0ef56019a07be6d1d00933cf6d1bfce7ecc297eaafad40d4036",
        "ResolvConfPath": "/var/lib/docker/containers/6a39b124f04fd231a48242fb73826d0b7d8af1cfd31d893b9c4e1c0a7803617e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6a39b124f04fd231a48242fb73826d0b7d8af1cfd31d893b9c4e1c0a7803617e/hostname",
        "HostsPath": "/var/lib/docker/containers/6a39b124f04fd231a48242fb73826d0b7d8af1cfd31d893b9c4e1c0a7803617e/hosts",
        "LogPath": "/var/lib/docker/containers/6a39b124f04fd231a48242fb73826d0b7d8af1cfd31d893b9c4e1c0a7803617e/6a39b124f04fd231a48242fb73826d0b7d8af1cfd31d893b9c4e1c0a7803617e-json.log",
        "Name": "/filestash",
        "RestartCount": 11,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "filestash_default",
            "PortBindings": {
                "8334/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8334"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "59ec3118edb2683ee4c1f35c6283f90e27197c4730f0576f9efa93932c666566",
                "Source": "/var/lib/docker/volumes/59ec3118edb2683ee4c1f35c6283f90e27197c4730f0576f9efa93932c666566/_data",
                "Destination": "/app/data/config",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "6a39b124f04f",
            "Domainname": "",
            "User": "filestash",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8334/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "GDRIVE_CLIENT_SECRET=<gdrive_secret>",
                "DROPBOX_CLIENT_ID=<dropbox_key>",
                "APPLICATION_URL=",
                "GDRIVE_CLIENT_ID=<gdrive_client>",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOPATH=/tmp/go",
                "CGO_LDFLAGS_ALLOW=-fopenmp"
            ],
            "Cmd": [
                "/app/filestash"
            ],
            "ArgsEscaped": true,
            "Image": "machines/filestash",
            "Volumes": {
                "/app/data/config/": {}
            },
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "3534fbc8c8037b229805a08253e0eb1c9ef0714d01db7693b1c93bb177bb044d",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "filestash",
                "com.docker.compose.service": "app",
                "com.docker.compose.version": "1.23.2",
                "org.label-schema.build-date": "2019-03-07T04:57:52Z",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "46a1175db5b25533277a5c23b8c1eaef447e0fe7",
                "org.label-schema.vcs-url": "https://git.kerjean.me/nuage/nuage.git"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "dcd6cc39ae1f002aed1f0c87f6442d601774f6a3301bc44516415964ffdc26ce",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/dcd6cc39ae1f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "filestash_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "app",
                        "6a39b124f04f"
                    ],
                    "NetworkID": "a88456f83aaf2dc055dbda0ef7ae49543d9ba4479ab2f816a187353d011d0b17",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]

Result of 
`uname -a`
> Linux helios4 4.4.162-mvebu #9 SMP Fri Feb 8 09:12:13 CET 2019 armv7l GNU/Linux

Result of
`getconf LONG_BIT`
> 32

**Comment by mickael-kerjean** [comment]
Hello,

This is definitly an architecture problem as we don't have an ARM build at this stage. I'm closing the ticket in favor of: https://github.com/mickael-kerjean/filestash/issues/142
