### ISSUE TITLE
Request: Armv7 release binaries

### ISSUE THREAD

**Issue by sbrl** [mickael-kerjean/filestash#142]
I don't have the go toolchain installed, and from what I've seen it's really heavy on the disk space.

I'd also really like to able to use filestash on my _Raspberry Pi_.

Could _Armv7_ binaries be provided on release please?

**Comment by mickael-kerjean** [comment]
I've had quite a few requests for this in the last few months as it would make a lot of sense to have an ARM release. The thing is I personally don't have any use for an ARM build and creating such build would require to rent some hardware. To make it happen I see a few options:

- get some people to contribute to the project financially so that I could rent such a server. I just need 2 persons contributing 5$ a month, this would be plenty enough

- get someone who would be willing to create such a build aside from the project where I'd link to this person build

**Comment by herlev** [comment]
I think I might be able to help compiling a release, if you can help provide me with info on how to do so. Disk space won't be a problem for me, as I have my Raspberry Pi connected to a 1TB HDD, where my docker installation is moved to.

**Comment by herlev** [comment]
I just tried building a docker image, which failed when it tried to compile the frontend.

**Info about my Raspberry Pi**
```
$ uname -a
Linux DietPi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
```
**Commands used:**
```
git clone https://github.com/mickael-kerjean/filestash && cd filestash
```
```
docker build docker/prod/
```
This is the output from when it started failing:
```
> node-sass@4.11.0 install /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-arm-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-arm-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.14.2 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:13:12)\n    at F (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:68:19)\n    at E (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:80:29)\n    at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:89:16\n    at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/index.js:42:5\n    at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:13:12)\n    at F (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:68:19)\n    at E (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:80:29)\n    at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:89:16\n    at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/index.js:42:5\n    at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:80:29)
gyp ERR! stack     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/which/which.js:89:16
gyp ERR! stack     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /tmp/go/src/github.com/mickael-kerjean/filestash/node_modules/node-sass
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@0.6.2 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.2.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@2.0.0 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.6.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-10T19_34_38_764Z-debug.log
server/common/cache.go:5:2: cannot find package "github.com/mitchellh/hashstructure" in any of:
        /usr/lib/go/src/github.com/mitchellh/hashstructure (from $GOROOT)
        /tmp/go/src/github.com/mitchellh/hashstructure (from $GOPATH)
server/common/cache.go:6:2: cannot find package "github.com/patrickmn/go-cache" in any of:
        /usr/lib/go/src/github.com/patrickmn/go-cache (from $GOROOT)
        /tmp/go/src/github.com/patrickmn/go-cache (from $GOPATH)
server/common/config.go:6:2: cannot find package "github.com/tidwall/gjson" in any of:
        /usr/lib/go/src/github.com/tidwall/gjson (from $GOROOT)
        /tmp/go/src/github.com/tidwall/gjson (from $GOPATH)
server/common/config.go:7:2: cannot find package "github.com/tidwall/sjson" in any of:
        /usr/lib/go/src/github.com/tidwall/sjson (from $GOROOT)
        /tmp/go/src/github.com/tidwall/sjson (from $GOPATH)
```

**Comment by sbrl** [comment]
Would you be able to cross-compile for ARM on a different architecture? It sounds like a thing that should be possible with a modern language like Go (I assume that's what this is written in?).

If building didn't require a Go compiler (which is really big), then I would be able to provide an automated build via my personal CI system.

**Comment by herlev** [comment]
Okay so now the frontend part succeeds. I changed this line in the Dockerfile
```
apk --no-cache --virtual .build-deps add make gcc g++ curl nodejs git npm && \
```
to this
```
apk --no-cache --virtual .build-deps add make gcc g++ curl nodejs git npm python2 && \
```
Now running `docker build docker/prod/` fails at with this output, after compiling the frontend successfully:
```
# github.com/mickael-kerjean/filestash/server
/usr/lib/go/pkg/tool/linux_arm/link: running gcc failed: exit status 1
collect2: fatal error: cannot find 'ld'
compilation terminated.

stat server/plugin/plg_image_light/index.go: no such file or directory
```

**Comment by mickael-kerjean** [comment]
At that stage, it's just about troubleshooting: see it crash, read the trace, fix and repeat until it all goes ok. The trace is quite informative: `fatal error: cannot find 'ld'` which mean quite literally you need to have a proper linker installed

**Comment by V1dev** [comment]
I fixed it by installing binutils-gold and the image now builds successfully.

**Comment by herlev** [comment]
I fixed it by installing binutils-gold and now the image compiles successfully. However when running the server on the raspberry pi and accessing it from my pc I get [this](https://github.com/mickael-kerjean/filestash/issues/127) issue. I don't know if this is a security feature, to only allow setting up the admin account from the same device the server is hosted on. If it is, then I don't know how I'm supposed to setup the admin account, as my raspberry pi is running in headless mode.

**Comment by mickael-kerjean** [comment]
That's the exact reason I have a CI server => avoid publishing a release that's broken. If you docker build, you bypass that protection and shouldn't expect stability. Making a proper stable build would require investing on an ARM server to be used specifically for the build but considering I have 0 need for an ARM build, this will have to come from donation, point in case, to date nobody has donate for making such a purchase.

**Comment by mickael-kerjean** [comment]
Since @herlev pull request, this is how you can make it work on ARM:

# Create your own stable ARM build

1. `git clone https://github.com/mickael-kerjean/filestash && cd filestash`
2. Visit #filestash on freenode, we have a bot that will tell you which commit can be used in production:
`Build success: https:// github.com/mickael-kerjean/filestash/commit/8aea4b82f8858a6e0a35d58823e10b1cf6c0437f`
3. `git checkout the_name_of_the_commit`
4. `docker build docker/prod/`

# Maintain your own build

Everytime on IRC you see a message along the line of:
```
Build success: https://github.com/mickael-kerjean/filestash/commit/8aea4b82f8858a6e0a35d58823e10b1cf6c0437f
```
You can safely checkout to the new commit and recreate your build. 

# Conclusion

This is quite a pain overall, maintenance won't be as simple as `docker pull xxxx` like with the other release. This is due to lack of funding, if you want to make it simpler to both install and maintain, we'd need a proper ARM build server = funding. If someone is willing to pay for this, feel free to comment and we'll make it better. Budget required is slightly under 10$ / month

**Comment by sbrl** [comment]
....I don't have docker installed :-(

**Comment by mickael-kerjean** [comment]
The doc has all the relevant links to get through the installation, it's literally a < 2 minutes job. 
I'm not keen on maintaining on my free time hundreds of different linux distribution with each possible version, this would be a rabbit hole that would kill all my plans for new features.

**Comment by sbrl** [comment]
Fair enough. If I have time (and find a use for filestash - I ended up using a webdav implementation and hooking it up to a pre-existing Nextcloud installation for my original purpose), I might investigate the feasibility of compiling myself automatically. That won't be for a good while though, because I'm currently busy with University.

If anyone else has armv7 builds running, I'd love a copy 🙂

**Comment by herlev** [comment]
Hey @mickael-kerjean, does `git checkout the_name_of_the_commit` have any effect at all when using `docker build docker/prod/`? Since the newest version of the repo gets cloned again when building the docker image.

From docker/prod/Dockerfile:
```
git clone --depth 1 https://github.com/mickael-kerjean/filestash && \
```

**Comment by sbrl** [comment]
I've taken a little look, but I can't find any non-docker information. The docs link me from the wiki to the website, and the website only contains compilation info for Docker.

**Comment by PedroC1999** [comment]
Sorry to revive this,

when running the instructions to compile for armhf, I am running into the error message:

/usr/share/tinytex/bin/x86_64-linux/tlmgr: not found

which halts the operation. I see the x86_64 and assume its another dependency that is setup for non arm processors. Any way I can get around this?

Many thanks

**Comment by benruijl** [comment]
I have the same issue as @PedroC1999  on my Rapsberry Pi 3B+, armv7.

**Comment by mickael-kerjean** [comment]
I bought a raspberry pi just to fix this and got it working. Basically:
```
make build_init
make build_frontend
make build_backend
```
assuming you have already install golang and a few other dependencies as shown [here](https://github.com/mickael-kerjean/filestash/blob/master/.drone.yml)

**Comment by benruijl** [comment]
Amazing work! I will test it soon :smile:

**Comment by amilino** [comment]
I cannot make it work on RPi. Stuck on step number 3, because I don't have other machine to build it and to build it on RPi doesn't work.

**Comment by ViRb3** [comment]
For the eager ones, ARM (armhf) build is available [here](https://github.com/ViRb3/filestash/releases/download/v0.41/filestash_Linux-armhf.tar).

**Comment by amilino** [comment]
Nice, and how to install armhf on Raspberry?

**Comment by amilino** [comment]
Ok, it is just about extracting and running the file. All good.

**Comment by amilino** [comment]
There are some issues with armhf on Raspberry Pi. Like port cannot be changed and reverse proxy is not working. Any idea how and if armhf can be used on RPi? I just extracted the package and run executable...

**Comment by ViRb3** [comment]
I got it working on my Raspberry Pi 4 using Docker. I put Filestash in a container and nginx in another container and I had it reverse proxy without any issues. Granted, I didn't check if changing the port works as it is unnecessary if using Docker. The only problem I had was #234, which shouldn't be specific to the RPi.

**Comment by amilino** [comment]
I don't use docker nor nginx.
Does someone know how to install it normally together with apache?

**Comment by sbrl** [comment]
> Does someone know how to install it normally together with apache?

I don't use Apache (it's horribly slow), but you'll probably want to create a new virtual host and reverse-proxy it through to Filestash.

**Comment by amilino** [comment]
> > Does someone know how to install it normally together with apache?
> 
> I don't use Apache (it's horribly slow), but you'll probably want to create a new virtual host and reverse-proxy it through to Filestash.

Tried today with nginx. Also not able to compile it for RPi (stuck on number 3: create the frontend build: make build_frontend).

Can someone elaborate a bit more how to compile it? It is mentioned to use another machine.

I really like this application and would like to use it.

**Comment by belibug** [comment]
What is the latest status on this, official docker image still dont include arm support. Please add arm support so we can host it on raspberry pi.

**Comment by FrancescoSaverioZuppichini** [comment]
news?

**Comment by FrancescoSaverioZuppichini** [comment]
> I got it working on my Raspberry Pi 4 using Docker. I put Filestash in a container and nginx in another container and I had it reverse proxy without any issues. Granted, I didn't check if changing the port works as it is unnecessary if using Docker. The only problem I had was #234, which shouldn't be specific to the RPi.

Could you please share the docker file?

**Comment by amilino** [comment]
> > I got it working on my Raspberry Pi 4 using Docker. I put Filestash in a container and nginx in another container and I had it reverse proxy without any issues. Granted, I didn't check if changing the port works as it is unnecessary if using Docker. The only problem I had was #234, which shouldn't be specific to the RPi.
> 
> Could you please share the docker file?

Just as an alternative you can use Filebrowser. Development again started and it is working awesome.
`https://github.com/filebrowser/filebrowser`

**Comment by FrancescoSaverioZuppichini** [comment]
@amilino cool, I will try. In the end, they are all more or less the same thing

**Comment by dzusr** [comment]
This is my Dockerfile. I compiled it successfully. Please refer to: https://github.com/dzusr/filestash/blob/master/docker/Dockerfile
