### ISSUE TITLE
Date format of Webdav

### ISSUE THREAD

**Issue by penguinsam** [mickael-kerjean/filestash#143]
I found the date is displayed in invalid format using webdav as shown:

![image](https://user-images.githubusercontent.com/6859350/54178621-74351400-44d1-11e9-8920-0d0c33271ecb.png)

**Comment by mickael-kerjean** [comment]
The problem should have been fix with last week commit. Let me know if there's any issues with it and we'll reopen / fix

**Comment by penguinsam** [comment]
Checked fixed, thanks so much
