### ISSUE TITLE
box.net support

### ISSUE THREAD

**Issue by jeroenpardon** [mickael-kerjean/filestash#147]
Is box.net support something you would consider adding? They used to support Webdav but unfortunately it has been deprecated. A crappy move / decision but I do have quite a lot of free storage there. Would be great to have this integrated in filestash.

**Comment by mickael-kerjean** [comment]
Pull request is welcome if someone want to tackle this

**Comment by mickael-kerjean** [comment]
I have no plans to personally implement it this feature but would be happy to accept a pull request. we can re-open the issue if we have a volunteer for the work.
