### ISSUE TITLE
Can't enter sftp pass in GUI

### ISSUE THREAD

**Issue by jeroenpardon** [mickael-kerjean/filestash#150]
- after setup go to /admin/dashboard
- Add SFTP connection
- Enter label, hostname, username (i pasted in the values, but manually entering seems to have the same result)
- Password value can't be entered, clicking the field does enable/disable

Ended up adding the password in config.json

**Comment by mickael-kerjean** [comment]
Hello,

I'm not sure what you are referring here, filling the data within /admin/dashboard will prefill the form with whatever you want
![127 0 0 1_8334_admin_dashboard](https://user-images.githubusercontent.com/13233076/55297984-c042fb00-5476-11e9-84aa-2bd0b59e69c4.png)
will show this on the frontoffice side:
![127 0 0 1_8334_login(iPhone 4)](https://user-images.githubusercontent.com/13233076/55297993-ca64f980-5476-11e9-9c99-9b169a75a81f.png)

**Comment by jeroenpardon** [comment]
I am not talking about the frontend, what I am talking about is the steps I mentioned in the description. I enter a label, hostname and username, and when I get to the password field here:

![screenshot](https://i.imgur.com/T1V7UEn.png)

 I literally cannot enter anything in the input field, as in typing will not enter the characters. Tested in Chrome and Safari on MacOS.

The only way for me to get the password in there is to manually edit the json file.

**Comment by mickael-kerjean** [comment]
The above commit should have fixed it. Let me know if you still have the problem and we'll reopen
