### ISSUE TITLE
WebDAV path not set as default path in UI

### ISSUE THREAD

**Issue by rikroe** [mickael-kerjean/filestash#151]
When setting a custom path for WebDAV (via the admin or the login interface), I can login correctly but the path gets added to the frontend URI. 

For example, ``path`` = ``/shared_folder`` results in URI ``filestash.example.org/files/shared_folder``, which returns a `Oops! Unkown path` error. 
If I manually remove the ``shared_folder`` part from the adress bar, everything is correct and the default folder of the filestash UI is set to ``shared_folder`` (which is correct, as there is no shared_folder in shared_folder).

The shared_folder part is added to the URI again after each refresh.

**Comment by mickael-kerjean** [comment]
I can't replicate your behavior from my end where the path parameter work as expected. Please send more details about what you're doing so that I can reproduce the problem you're referring:
- what backend are you connecting to?
- can you replicate this from the demo application?
- when you refer as shared folder, do you refer as a shared link made from filestash?

**Comment by rikroe** [comment]
The backend is a Synology NAS running it's WebDAV component. I can reproduce the issue on demo.filestash.app, same issue here. 
Let me clarify the folder structure (all on the WebDAV server and accessible):
```
/ (WebDAV root)
├── shared_folder/
│   ├── file1.txt
│   └── file2.txt
├── another_folder/
│   ├── and_another_folder/
│   └── somefile.txt
```

Basically, when I enter `/shared_folder` in filestash's login input in _Path_, I expect it to use this folder as root for the UI, i.e. I am not able to access `another_folder` within filestash without logging out and changing the _Path_ parameter. This works as expected.

However, what does not work is as follows: Directly when logging in, the parameter of `/shared_folder` is added to the browser URL, resulting in a default URL of `https://demo.filestash.app/files/shared_folder/`. Here I get the (correct) file not found error message. I would expect a URL like  `https://demo.filestash.app/files/`, without the added _Path_ parameter.

If I manually remove _shared_folder_ from the browser URL, everything again works as expected and I can access subfolders or files (like _file1.txt_). 

Hope this helps you.

**Comment by rikroe** [comment]
Found a work around - just add that part of the path you want to have as root to the original adress (i.e. ``https://some.dav.org/shared_folder`` works as expected as well. 

However this is inconsistens, e.g. with SFTP where the _Path_ parameter is used to define the root folder.

**Comment by mickael-kerjean** [comment]
I found a reproduction for the issue and fixed it, thank you for the report!
