### ISSUE TITLE
Locahost - Pihole + Filestash

### ISSUE THREAD

**Issue by Rustymage** [mickael-kerjean/filestash#154]
Morning,

I've been using Filestash for a week or so in a docker container (running on an Intel NUC) with no issues. Yesterday I come home to find thousands of DNS requests originating from the NUC in my Pihole GUI (Raspberry Pi powered).

<img width="486" alt="Screenshot 2019-04-13 at 07 29 37" src="https://user-images.githubusercontent.com/19926955/56075690-6c151080-5dbe-11e9-9caa-bd4fa5e82670.png">

I did a little digging and found them to only occur with the Filestash container is running.

Here is a photo of when it started:

<img width="1002" alt="Screenshot 2019-04-13 at 07 29 28" src="https://user-images.githubusercontent.com/19926955/56075691-6c151080-5dbe-11e9-8117-de93107cab97.png">

I'm not sure where to go from here and how to make it stop. 

Can anyone help? I can provide logs/settings if requested, I'mjust not sure what's useful right now.

Thanks in advance.

Rusty

**Comment by mickael-kerjean** [comment]
Hello,

That's interesting, Filestash doesn't make any request to the outside when telemetry is disable (which is the default). What is this localhost.cable.virginmedia.net domain? 

>  can provide logs/settings if requested

Yes please, if you could send me your logs by email that would be awesome, Filestash by default doesn't go in contact with any outside server, the application is completly selfcontained (at the exception of telemetry request if you enable it)

**Comment by Rustymage** [comment]
localhost.cable.virginmedia.net doesn't go anywhere - my ISP is Virgin Media and the PiHole reports that the origin point of the request is the Intel NUC (with Filestash running).

Which logs would you like? There's none in the container (/var/log) for Filestash.

I've attached a few screen grabs.

I ran nslookup on the Pihole device, hence why I think it referes to itself.

The second screenshot is the pihole.log file. You can see it's relentless.

The third is the recent queries.

It could be a mixture of things, not a direct issue with Filestash, but when the container is stopped the issues cease. It's also strange that it started yesterday, while I was at work. I should add that it's been running fine for the past few days.

<img width="601" alt="Screenshot 2019-04-13 at 08 24 22" src="https://user-images.githubusercontent.com/19926955/56076195-1fcdce80-5dc6-11e9-9ea2-0278e5f53046.png">
<img width="804" alt="Screenshot 2019-04-13 at 08 27 52" src="https://user-images.githubusercontent.com/19926955/56076196-1fcdce80-5dc6-11e9-8387-795726e20493.png">
<img width="974" alt="Screenshot 2019-04-13 at 08 25 40" src="https://user-images.githubusercontent.com/19926955/56076197-1fcdce80-5dc6-11e9-95b7-abdca1e5cb3e.png">

**Comment by mickael-kerjean** [comment]
It's not very clear to me at this point. How would the container knows about localhost.cable.virginmedia.net? Did you configure it somewhere? Eg: is it written somewhere in your setup? What are you trying to do?

Also, does the issue start as soon as you start the container? 

> Which logs would you like? There's none in the container (/var/log) for Filestash.

The log is getting written under: `/app/data/log/access.log`. To export the log:
```
 docker exec -ti -u 0 filestash sh
apk --no-cache add curl
curl --upload-file /app/data/log/access.log https://transfer.sh/filestash.log
# the transfer.sh should give you a URL file your filestash log
```

**Comment by Rustymage** [comment]
> It's not very clear to me at this point. How would the container knows about localhost.cable.virginmedia.net? Did you configure it somewhere? Eg: is it written somewhere in your setup? What are you trying to do?

Not setup, no changes before the problem started, hence the confusion - I have a reverse proxy infront with basic auth but that hasn't caused a problem before. That's also running on the NUC using Docker.

> Also, does the issue start as soon as you start the container?

Yes, as soon as it starts. I've recorded a screencast of it. See here: https://drive.google.com/file/d/1XK2q7E1O7InJIdbfXtHRThauW-JOQof-/view?usp=sharing

I've just checked the log and I've got loads of:

`2019/04/13 08:35:29 ERROR Invalid access from host: localhost:8334
2019/04/13 08:35:29 INFO HTTP 403 GET    0.1ms /about
2019/04/13 08:35:29 ERROR Invalid access from host: localhost:8334
2019/04/13 08:35:29 INFO HTTP 403 GET    0.1ms /about
2019/04/13 08:35:29 ERROR Invalid access from host: localhost:8334
2019/04/13 08:35:29 INFO HTTP 403 GET    0.1ms /about
2019/04/13 08:35:29 ERROR Invalid access from host: localhost:8334
2019/04/13 08:35:29 INFO HTTP 403 GET    0.1ms /about`

What's the above trying to do? Is it reaching out on the incorrect port?

Cheers

**Comment by Rustymage** [comment]
I've recreated the container and deleted the old config volume and the problem has ceased, the only changes I made were to add an SFTP service and the hostname, everything else was the same...

Although the issue is closed, I'd be very interested in at least having your thoughts on the access.log to assist if the problem crops back up or to help anyone else who may find themselves having this issue.

Cheers!

**Comment by mickael-kerjean** [comment]
Your log says they were access to the /about page (the question is what made this request or who?). The following error is showing the request made on /about by whatever did that request got block because the host http header doesn't match what you have specified in your config, see [here](https://github.com/mickael-kerjean/filestash/blob/ea48dbe128917c9338ea61586c6fdfacd776e6d9/server/middleware/http.go#L52-L58)

**Comment by mickael-kerjean** [comment]
As I was looking at some unrelated things, I found [the culprit](https://github.com/mickael-kerjean/filestash/blob/master/server/main.go#L137-L151) which was introduce in order to get a better message on Stdout when the application starts up. In some certain circumstances (with your previous config that define the general->host I guess) it results in a infinite loop ... My bad, I'll fix this ASAP

**Comment by mickael-kerjean** [comment]
Bug solved with the above commit, I'm closing, let me know if you are still experiencing the same issue and we'll reopen

**Comment by Rustymage** [comment]
Thanks for the updates and I'm glad a bug was found!

**Comment by Rustymage** [comment]
Will this update the docker image?

**Comment by mickael-kerjean** [comment]
Yes, you can see the commit that's getting push to the Docker hub after CI in [here](https://irc.filestash.app/), there's a bot called blipblip that shout: `Build success: https://github.com/mickael-kerjean/filestash/commit/xxxxxxxxx`
