### ISSUE TITLE
[Feature Request] Reverse Proxy Authentication

### ISSUE THREAD

**Issue by bkanuka** [mickael-kerjean/filestash#156]
This would allow Nginx to authenticate the user, and then pass the authenticated username via a header onto filestash. This way nginx can handle all the authentication (which it already does for all my services).  Typical headers used for this are `X-WEBAUTH-USER` or `REMOTE_USER`.

**Comment by mickael-kerjean** [comment]
Hello,

Sounds like a cool feature, can you create a pull request?

**Comment by bkanuka** [comment]
No :( I wish I could help but I've never used Go. Just wanted to leave this as a feature request in case it inspires someone else to pick it up.

**Comment by IBlackI** [comment]
Sadly I have no experience using go, but I would second this issue.

**Comment by ONL** [comment]
Hi @bkanuka , I am trying to understand your request as to decide, whether I could attemt implementing it. Which parts of filestash do you want to use the login for? Can you describe your use case in more detail?

**Comment by mickael-kerjean** [comment]
I have no plans to personally implement it this feature but would be happy to accept a pull request. we can re-open the issue if we have a volunteer for the work.
