### ISSUE TITLE
Crypto/aes: invalid key size 11

### ISSUE THREAD

**Issue by spaibs** [mickael-kerjean/filestash#158]
Hi,
I am using the docker build on my server, but after some time (It works for 1 to 2 days) the message "Crypto/aes: invalid key size 11" shows up when I try to login with my SFTP credentials.
Do you know what is going on?

**Comment by mickael-kerjean** [comment]
The secret key needs a predefined number of characters: either 16, 24 or 36 (see [here](https://golang.org/pkg/crypto/aes/#NewCipher)), yours is 11 characters long and that can't work

**Comment by spaibs** [comment]
Which config do you mean?
But why does it work for two days and then suddenly stops working?

Thanks

**Comment by mickael-kerjean** [comment]
> Which config do you mean?

When navigating in `/admin/configure`, under general => secret key

> But why does it work for two days and then suddenly stops working?

Well something got changed somewhere
