### ISSUE TITLE
Upload without drag and drop

### ISSUE THREAD

**Issue by pjeanjean** [mickael-kerjean/filestash#160]
Hello,

I just installed `filestash` on my server (and I like it so far), but I am a bit surprised that I can't find any Upload button on the UI...
Am I missing something, or is it intended to only be able to upload using drag'n'drop?

I just want to add that most of my devices don't have a file manager, so I can only use it as a file viewer/editor right now :/

**Comment by pjeanjean** [comment]
I just noticed that I do get an upload button in responsive mode...
Would it be possible to force the page to always display its responsive version?

**Comment by mickael-kerjean** [comment]
Hello,

The idea behind Filestash is to avoid all possible bloat. As such on:
- desktop: the only way to upload is through drag and drop
- non desktop: an upload button appear for all those devices where drag and drop isn't possible

> Would it be possible to force the page to always display its responsive version?

It wouldn't be something I would want to have. However you can create a pull request with such a feature. If you want to go the pull request way, you'd have to create an entry in the admin console, and enable the upload button if your config entry is enable while keeping the current behavior as the default one

**Comment by pjeanjean** [comment]
> The idea behind Filestash is to avoid all possible bloat. 
I actually like this answer, and this is one of the main reasons I chose Filestash for my setup.

However, I still think that having an upload button (even on desktop) is an important feature (moreso when the button is well integrated in the UI, like the one in Filestash).
So I made a pull request as you suggested, feel free to review it.
