### ISSUE TITLE
NFS/Samba support

### ISSUE THREAD

**Issue by timchengx** [mickael-kerjean/filestash#163]
Hi,
Currently I use filestash with ftp to remote access my server's local filesystem.

As I know #103 there is no plan to support local filesystem.
So I want to ask is it possible to support some local file sharing protocol such as NFS or SAMBA that can make filestash like a portal to access other internal network data?

Thanks!

**Comment by mickael-kerjean** [comment]
Love the idea. I'm not very familiar with the internals of NFS and SAMBA, would you be willing to help?

**Comment by timchengx** [comment]
I can try the Samba part. But I'm not familiar with Samba/NFS either. Progress might be very slow.

**Comment by mickael-kerjean** [comment]
Sounds good to me
