### ISSUE TITLE
Cannot preview PDF files in the browser (error 401)

### ISSUE THREAD

**Issue by scambier** [mickael-kerjean/filestash#167]
Hello,

I'm using Filestash with an SFTP backend (Filestash runs from the same server), and the browser cannot display the PDF files.

![image](https://user-images.githubusercontent.com/3216752/58937743-90b0b780-8773-11e9-94f5-0003e608c22e.png)

`PDF.js v2.0.673 (build: 31012570)
Message: Unexpected server response (401) while retrieving PDF "https://[redacted].filestash.app/api/files/cat?path=[redacted].pdf".`

However, I can download the file.

**Comment by mickael-kerjean** [comment]
Hello,

I can't replicate your error and I'm away with my family for the next few weeks. Feel free to send a pull request

**Comment by scambier** [comment]
Hello, the problem seems to be solved now, but I didn't change anything.
