### ISSUE TITLE
Instructions on setting up minio as storage backend?

### ISSUE THREAD

**Issue by acrylix** [mickael-kerjean/filestash#170]
Hello there, 

Wondering if there's any details on how to setup minio as the storage backend, coudn't find any related information in the docs, and I didn't see a minio specific connector available. 

Thanks in advance!

**Comment by mickael-kerjean** [comment]
Minio compatibility comes with the S3 backend, where in the S3 backend, the endpoint URL correspond to your Minio instance. For example, if you want to use the minio demo instance: https://demo.filestash.app/login#type=s3&access_key_id=Q3AM3UQ867SPQQA43P2F&secret_access_key=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG&endpoint=https://play.minio.io:9000/

**Comment by alexkutsan** [comment]
And how to configure the bucket that I want to connect?
