### ISSUE TITLE
Link to install instructions is dead

### ISSUE THREAD

**Issue by vext01** [mickael-kerjean/filestash#172]
The following link from the README.md is dead:
https://www.filestash.app/docs/install-and-upgrade

**Comment by mickael-kerjean** [comment]
I can't find any page with this link, were did you find it?

**Comment by vext01** [comment]
It's on the github landing page (installation):
![image](https://user-images.githubusercontent.com/604955/60043103-32625f00-96b7-11e9-9cb3-e5fb6ab78b55.png)

![image](https://user-images.githubusercontent.com/604955/60043126-40b07b00-96b7-11e9-8f3b-604355768981.png)

**Comment by HarryRogue** [comment]
Same here. 

"Forbidden

You don't have permission to access /projects/filestash/website/docs/install-and-upgrade on this server.
Apache/2.4.18 (Ubuntu) Server at www.filestash.app Port 80"

htaccess problem ?

**Comment by vext01** [comment]
In the meantime, can someone tell me how to build this?

(I'd like to try and port filestash to OpenBSD)

**Comment by mickael-kerjean** [comment]
the URLs from the README were missing a slash at the end, should be all good now, let me know if you find another broken link

**Comment by vext01** [comment]
There's another dead link on https://www.filestash.app/docs "see the documentation":
![image](https://user-images.githubusercontent.com/604955/60113616-166bc580-976a-11e9-8d83-b08174e2d034.png)

On another note, I was hoping to find build instructions. Are there any?

**Comment by mickael-kerjean** [comment]
Go this one to. Also you can see the build commands [here](https://www.filestash.app/docs/install-and-upgrade/#alternative-installation-methods)
