### ISSUE TITLE
log options

### ISSUE THREAD

**Issue by higi** [mickael-kerjean/filestash#178]
Hello,

are there any logs with filestash? / API

i want monitor: 
* user logged in
* user logged off
* user uploaded file/folder name
* user downloaded file/folder name
* user deleted file/folder name

is there any API with i could use to send thees data? or some kind of log i could keep parsing.

THX

**Comment by mickael-kerjean** [comment]
Hello, 
Yes there's some log file store under `/app/data/state/log/access.log`. Using a bit of bash you can get the information you want:
- user logged in: `cat access.log | grep session | grep POST`
- user logged off: `cat access.log | grep session | grep DELETE`
- user uploaded file: `cat access.log | grep "/api/files/cat" | grep POST`
- user uploaded folder: `cat access.log | grep "/api/files/mkdir"`
....
...

**Comment by higi** [comment]
THX, for info:)

we try to build in API for thees

**Comment by mickael-kerjean** [comment]
I don't see any pending actions here, I assume the issue is solve. Feel free to reopen if there's something missing
