### ISSUE TITLE
766 MB and rising 😳 what's the disk space requirements to build filestash?

### ISSUE THREAD

**Issue by rnkn** [mickael-kerjean/filestash#179]
So I wanted to build filestash from source (sans most of the plugins) following the instructions here: https://github.com/mickael-kerjean/filestash/pull/136/files

The non-Go dependencies are all A-okay. Everything was tiptop until...
~~~
% cd server
% go get
~~~
This was taking an unusually long time, so ^C and...
~~~
% go get -v
~~~
*and the onslaught began...* My $GOPATH ballooned out to 766 MB and just kept growing! It was not unlike the leadup to Chernobyl.

I've only built a couple of Go programs before, and each time I've noticed they are *incredibly shockingly disproportionately large* — but my thinking, as it always ought to be, is that maybe I'm doing something gravely wrong. It just seems uncanny that only the Go dependencies to build should approach 1GB... right? *Right?*

Any schooling on this would be much appreciated.

**Comment by dolanor** [comment]
In my GOPATH, some project do take a lot, and most of it is stored in the history of git of those projects.
It can be very big projects, or just projects with some mistake (git commit with some binary in it)
Which is why go modules makes sense to not get the history with it. It's way faster for large projects and let your disk usage low (in the $GOPATH/pkg/mod directory).

**Comment by mickael-kerjean** [comment]
I've never tried to optimise on this and never got actual numbers as disk space is usually no issue to me. As an example, my GOPATH contains 3.7G of stuff.

Also dolanor is 100% right, using go modules would make a lot of sense, I plead guilty as I never spent the time to figure out go modules yet.

**Comment by rnkn** [comment]
For me it was because I was on mobile data, thinking "gee this is taking a while." If go is cloning every dependency, can `got get` fetch a shallow clone?

**Comment by mickael-kerjean** [comment]
>  If go is cloning every dependency, can got get fetch a shallow clone?

Not at this stage, but it is the way forward indeed. Fixing this requires to use the relatively new feature from Golang call go modules (that didn't exist when this code base was created ) and also requires some change on the code base. This will be done either by a PR or when I can set aside some time to learn about this go module thing and make it all work

**Comment by rnkn** [comment]
Sounds cool 👍
