### ISSUE TITLE
add support for azure blobs

### ISSUE THREAD

**Issue by prabirshrestha** [mickael-kerjean/filestash#180]

**Comment by mickael-kerjean** [comment]
Hello,
I have no need for supporting any azure things myself. However feel free to create such a plugin and make a PR as this would be a great addition to Filestash, especially if the integration is done by someone who is working at Microsoft

**Comment by prabirshrestha** [comment]
Might be worth using this https://godoc.org/gocloud.dev/blob and get free backends for s3, azure, google and file and memory blobs for free.
