### ISSUE TITLE
Persist config in docker-compose/documentation

### ISSUE THREAD

**Issue by rikroe** [mickael-kerjean/filestash#183]
It would be nice if either he official docker-compose file or the documentation itself would include volumes for config persistency. The old structure mentioned #113 has changed some time ago.

Example:
```
    volumes:
        - /local/path/filestash/config/:/app/data/state/config/
        - /local/path/filestash/db/:/app/data/state/db/
```

**Comment by mickael-kerjean** [comment]
Hello,

You're right, at this stage I'm still trying to figure out how to structure things to be both future proof and convenient. This is the structure I have my head at this time:
```
|- cache (all sort of cache specific folders to make things faster)
|- public (all the static files that are sent to the browser)
|- state
    |- certs
        |- ssl (certificate and keys for running an HTTPS server)
        |- tor (all the tor specific stuff that are generated by the TOR tool)
    |- config
    |- log
        |- access.log
    |- db
       |- share.sql (database for shared links)
       |- search (contains all the index for full text search)
           |...
           |...
```
The idea being that the `state` folder is the one you want to persist on the docker-compose.yml. However, before heading this way, I would love some feedbacks:
- Is such a folder structure really convenient?
- Is there some better options when it comes to how those folders are laid out?
- Is the naming of those folders good? Can it be improve? Any suggestions?

**Comment by rikroe** [comment]
Thanks for the quick reply :) I can understand fully understand your point. Storing everything you want to persist in one folder makes sense to me. 

However for naming purposes I would change `state` to `storage`. However thats just my understanding. State sounds more like 'current state' instead of 'persistent storage' to me. For easier reading, I keep with `state` for this post.

I would change the structure below the `state` folder a little bit: 
```
|- state
    |- certs
        |- ssl (certificate and keys for running an HTTPS server)
        |- tor (all the tor specific stuff that are generated by the TOR tool)
    |- config
        |- config.json
        |- share.sql (database for shared links)
    |- log
        |- access.log
    |- search (contains all the index for full text search)
       |...
       |...
```

Take me as an example: I just want to persist `config.json` and `share.sql`. I don't use full text search or certs (own reverse proxy) and I'd be fine if the access logs are deleted on re-creation of the container.
If `config.json` and `share.sql` are in one folder, I would only need to persist `state/config`, if I want to persist everything, then I can map `state`.

**Comment by whalehub** [comment]
@mickael-kerjean Any update on this?

**Comment by mickael-kerjean** [comment]
This isssue is simply waiting for a pull request. To move forward, we need to:
1. set the path in Filestash as per the model given by @rikroe which I very much like. I would just suggest that the search.sql is in its own folder search as to ensure one can persist exactly what is needed depending on the use case
2. create the migration script from old to new path
3. update the docker-compose.yml file to reflect those changes

**Comment by whalehub** [comment]
bump
