### ISSUE TITLE
unable to add sources in the dashboard

### ISSUE THREAD

**Issue by oz123** [mickael-kerjean/filestash#184]
I have successfully installed filestash behind an nginx reverse proxy, as documented.

When I try to add new sources in the dashboard the UI keeps refreshing itself, and I can't delete or add new sources.

I tested this in Chrome and Firefox, both show the same behaviour.

**Comment by mickael-kerjean** [comment]
Hello,
This is a bug coming from the original design assuming the latency between server and client is ideal. The above commit remove that feature. I'm closing but feel free to reopen if there's still issues with this

**Comment by oz123** [comment]
Thank you so much.
