### ISSUE TITLE
Not Allowed only on WebDav login

### ISSUE THREAD

**Issue by atahanacar** [mickael-kerjean/filestash#186]
Hi

I'm getting response `{"status":"error","message":"Not Allowed"}` when I'm trying to connect to my WebDav server (Nextcloud). This doesn't happen when I try to connect to a SFTP server, and I can successfully login. The log doen't show any errors. I have no idea how the investigate this issue any further.

The instance is running on Docker behind an Apache reverse proxy. I have the same problem even when not using a reverse proxy.

Thanks

**Comment by mickael-kerjean** [comment]
Hello,

Trying from my end using a demo instance of [nextcloud](https://try.nextcloud.com/) from the [demo of filestash](https://demo.filestash.app) gets me the expected behavior:
![demo filestash app_files_](https://user-images.githubusercontent.com/13233076/62507310-41583780-b847-11e9-9754-7e4ee580d591.png)

Can you send a way to reproduce this?

**Comment by atahanacar** [comment]
I have no idea how to reproduce this issue. It's a fresh install, and the log shows no errors when I get the error. It is not caused by my nextcloud instance, I know because the demo can connect to it just fine. Are there any logs other than admin/api/log?

**Comment by mickael-kerjean** [comment]
> I have no idea how to reproduce this issue.

Having a way to reproduce an error is central in fixing it. Without reproduction there's not much I can do

>  Are there any logs other than admin/api/log?

There's just 1 log and you can download it from the admin console under `/admin/activity`

> I know because the demo can connect to it just fine

If the demo connects fine there's an issue in your installation and without reproduction it's hard to do anything

**Comment by atahanacar** [comment]
Ok, so I have installed filestash on 2 more servers, both worked fine. However, that one server always gives that error. I've tried reinstalling, I even reinstalled docker but something causes an error but I don't think it is caused by filestash.
