### ISSUE TITLE
[Feature Request] Minio documentation

### ISSUE THREAD

**Issue by robmarkcole** [mickael-kerjean/filestash#188]
Hi
apologies for raising an issue, I tried freenode chat but nobody home.
I wish to use Minio but my effort to configure it always results in `incorrect password` error despite being correct. Therefore I suggest the docs would benefit from covering configuring Minio. My own failed attempt is below.
Many thanks

![image](https://user-images.githubusercontent.com/11855322/63156935-c1cc2480-c00d-11e9-9699-7a60050f6fbe.png)

**Comment by mickael-kerjean** [comment]
I've answered on IRC, please don't use Github for support. If someone else is having the same problem and ends up reading this issue, you can find solutions via the searchable IRC logs [here]( https://support.filestash.app/?q=Minio)
