### ISSUE TITLE
[bug] Unknown Path navigating paths with a comma

### ISSUE THREAD

**Issue by dbogdanov** [mickael-kerjean/filestash#191]
I am testing the web demo of Filestash with an SFTP server and I get lots of "Unknown Path" errors for all paths containing commas. Is there a workaround?

**Comment by mickael-kerjean** [comment]
Hello,
That's interesting, never tried that kind of thing before. I'll look it up when I got some time, thank you for the report

**Comment by mickael-kerjean** [comment]
This should be solve with ae2ef413b36bce77949a36017184a4c4294cb59b. Feel free to comment back if there's still issues and I'll reopen
