### ISSUE TITLE
[Feature Request] display and manage file permission

### ISSUE THREAD

**Issue by tomboe311** [mickael-kerjean/filestash#192]
Hi @mickael-kerjean,

I would prefer to display and manage the file permissions.

Display in the overview near the date.
Manage: select file and click on "change permission" next to "Remove"

related to #43

**Comment by mickael-kerjean** [comment]
The topic of permission is a tricky one. My current view on the topic is:
1. it should come as an option to be enabled from the admin console as to avoid complicating the UX
2. it has to be designed very carefully as every backend got a different way to do it. At this stage, I'm not sure what's the best abstraction to be use to get it to work everywhere

Also, if it was to ever see life, the server has some capability to generate forms on the client using [this API](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_backend_dav/index.go#L53-L76). If someone is up to the task, feel free to experiment and create some pull request
