### ISSUE TITLE
[Feature Request] Download directory or multiple files

### ISSUE THREAD

**Issue by tomboe311** [mickael-kerjean/filestash#193]
Hi @mickael-kerjean 

Is it possible to download a directory or multiple files?

**Comment by mickael-kerjean** [comment]
Not at the moment but feel free to implement it and create a pull request

**Comment by DillonB07** [comment]
Is this feature still up for consideration?
I would love this. If it had this then it would be just as good(if not better) than ForkLift and Filezilla or just desktop apps in general.
