### ISSUE TITLE
[bug] empty date after creating file or directory

### ISSUE THREAD

**Issue by tomboe311** [mickael-kerjean/filestash#194]
Hi @mickael-kerjean 

If I create a file or diretory via filestash the date isn't displayed. When I click through the directories, it is displayed again.

See:
![peekDAN26Z](https://user-images.githubusercontent.com/25898733/63918138-630aa000-ca3c-11e9-9393-c47318b6ebed.gif)

**Comment by mickael-kerjean** [comment]
Hi, this was a shortcut, feel free to make a pull request
