### ISSUE TITLE
[Feature Request] compression

### ISSUE THREAD

**Issue by projay11** [mickael-kerjean/filestash#196]
Hi I thought I would be good if you were able to compress and uncompress files/folders this would allow for the easy download and upload of folders or multiple files

**Comment by mickael-kerjean** [comment]
Hi, I personally have no use for this so this will have to come from the community. Pull request is more than welcome. From a technical perspective, this can be build as a plugin using the ProcessFileContentBeforeSend hook like in [here](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_light/index.go#L115)

**Comment by projay11** [comment]
didnt mean to close sorry. i have been trying to build my own version using the source code but when i try to build the backend i get lots of undefined references references from libresize. i have tried to compile my own libresize.a but still the same issue
any ideas?

**Comment by mickael-kerjean** [comment]
If you have problem with those, an option is to disable the plugin that use them which is the image plugin. To do that, you can comment [this line](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/index.go#L6).

Also I gave more pointers to someone on IRC that should help [here](https://support.filestash.app/2019-09-01.log)

**Comment by BobCashStory** [comment]
any update on this i need it too :)

**Comment by mickael-kerjean** [comment]
This is still awaiting for a pull request
