### ISSUE TITLE
[Feature Request] Add IIQ Files to config.json by default

### ISSUE THREAD

**Issue by mgolub2** [mickael-kerjean/filestash#197]
Phase one IIQ files should be able to be processed by libraw like leaf MOS files, and it would be nice to have them included by default.

**Comment by mickael-kerjean** [comment]
I'm not familiar with IIQ files. Can you send me a few ones to give it a try?

**Comment by mickael-kerjean** [comment]
I haven't received anything. I'm closing until there's enough feedback to get something actionable.
