### ISSUE TITLE
[Feature Request] Add S3 signature version config 

### ISSUE THREAD

**Issue by drinksober** [mickael-kerjean/filestash#198]
S3 have many auth signature version, can we add signature config in S3 advance option?
all the auth signature version definition in [auth type](https://github.com/boto/botocore/blob/f602fe60b7373629e20b0bfb3d3ca5380e203daf/botocore/auth.py#L859)

In my case, I have many self hosted S3 server, a part of server host by [minio](https://min.io), and another part of server host by ceph, they have diff signature version. so, I want to add auth signature version in S3 config.

Thx...

**Comment by mickael-kerjean** [comment]
All good to me, can you send a pull request ?
