### ISSUE TITLE
[Feature Request] Add onedrive support

### ISSUE THREAD

**Issue by NavePnow** [mickael-kerjean/filestash#199]
The fliestash will be more perfect with supporting onedrive.

**Comment by mickael-kerjean** [comment]
Can you send a pull request for it? Personally, I have neither a need and willingness to make it work on my free time.

**Comment by mickael-kerjean** [comment]
This is a duplicate of https://github.com/mickael-kerjean/filestash/issues/199 
I'm closing this one. Pull request are welcome to make it happen
