### ISSUE TITLE
[bug] Incorrect date on files

### ISSUE THREAD

**Issue by thomasjsn** [mickael-kerjean/filestash#200]
I'm seeing rather strange file dates;

![image](https://user-images.githubusercontent.com/6061006/65599191-8b36e180-df9d-11e9-8f10-5b248567e348.png)

It seems to be correct on folders, but it's very strange for files. I'm using Minio as a backend, and the dates are correctly shown there:

![image](https://user-images.githubusercontent.com/6061006/65599258-c0dbca80-df9d-11e9-8c49-ac57ccc0fcca.png)

It's only correct on the disk;
```
-rw-r--r-- 1 thomasjsn thomasjsn 3.2M Apr 15 22:47 IMG_20190415_224739.jpg
-rw-r--r-- 1 thomasjsn thomasjsn 2.8M Apr 15 22:48 IMG_20190415_224809.jpg
-rw-r--r-- 1 thomasjsn thomasjsn 2.9M Apr 15 22:51 IMG_20190415_225104.jpg
```

Docker host locale:
```
$ cat /etc/default/locale
LANG=en_US.UTF-8
```

Storage host locale:
```
#  File generated by update-locale
LANG="en_US.UTF-8"
LANGUAGE="en_US:en"
```

Ideas?

**Comment by mickael-kerjean** [comment]
That's interesting, can someone send me some demo account I could use from my end to try and fix this?

**Comment by zph** [comment]
@mickael-kerjean I'm not able to set you up with an account on that trial server :(. But if we can't solve it via some debugging, I could see about setting up a full dummy instance.

I'm browsing the code and trying to run locally to test a hunch... but ran into a local dev issue (Which I posted as a patch on separate repo).

My hunch is that timestamps are being processed twice for S3. Is that happening here https://github.com/mickael-kerjean/filestash/blob/master/server/model/backend/s3.go#L129-L137 and https://github.com/mickael-kerjean/filestash/blob/master/server/ctrl/files.go#L62 ?

The other potentially useful debugging info is: https://cl.ly/6178c1f9506b

For an example file:
1. Genuine Mtime per S3 Console: 2018/10/18 7:59:43 AM GMT+0100
2. Filestash display of datetime: 2097-06-07
3. Filestash JS data representation in React: 4021447095178 (which when parsed with `new Date()` yields representation 2097 datetime.

Other findings:
* I wondered if this was an Int overflow, but doesn't seem like it per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER. Even if sent from Golang to Js as Nanosec, it's not large enough to overflow.

* The canonically correct way to convert Nano -> Milli seems to be 
`t := time.Now().UnixNano() / (int64(time.Millisecond)/int64(time.Nanosecond))`

When I can investigate more, I'll compare how timestamps are stored and passed for other backends, with assumption that this is limited to S3.

**Comment by zph** [comment]
Posted what tested well as a fix locally 👍
