### ISSUE TITLE
[bug] Missing image navigation, when using private or incognito mode

### ISSUE THREAD

**Issue by thomasjsn** [mickael-kerjean/filestash#201]
When I am logged in I can browse images using the image navigation bar, and with the arrow keys;

![image](https://user-images.githubusercontent.com/6061006/65601252-026e7480-dfa2-11e9-9805-c9cd36a824fa.png)

If I open the image using the share URL, in a private session or incognito mode the navigation bar is not present. And I can not navigate using the arrow keys either.

![image](https://user-images.githubusercontent.com/6061006/65601374-42cdf280-dfa2-11e9-82f7-6389f39d5d8e.png)

Happens both with Firefox and Chrome. I would expect the behavior to be the same, a bit puzzled as to why it's not...

**Comment by mickael-kerjean** [comment]
Thank you for the report, you're right, there seem to be something wrong. Can you manage to fix it and send a pull request?
