### ISSUE TITLE
[bug] Video playback fails when there is comma in the filename

### ISSUE THREAD

**Issue by itsnotv** [mickael-kerjean/filestash#203]
I am connecting with SFTP. If the video file name has a comma character, the video player fails to play the video.

This is the error message.
```
The media could not be loaded, either because the server or network failed or because the format is not supported.
```

In the video title, comma is replaced with "%2C", every other special char shows up correctly except comma.

URL encoding issue?

**Comment by itsnotv** [comment]
I feel the changes in #159 are breaking this. The link url is encoded twice. If I decode and post the url, the video plays fine.

**Comment by mickael-kerjean** [comment]
Correct. I'm visiting some of my family at the moment, will dig deeper when I get back or if you want it done faster, pull request is also more than welcome

**Comment by mickael-kerjean** [comment]
This should be solve with ae2ef413b36bce77949a36017184a4c4294cb59b. Feel free to comment back if there's still issues and I'll reopen
