### ISSUE TITLE
[bug]  Cannot create share link

### ISSUE THREAD

**Issue by kewvention** [mickael-kerjean/filestash#206]
Upgraded to latest version of filestast. Now when i try to share a file, it throws the error:
WARN search::initschema execute error(attempt to write a readonly database)
Im using the docker build.
I attempted to configure the MYSQL section in the admin page, but it does not save.

**Comment by mickael-kerjean** [comment]
> attempt to write a readonly database

Filestash is trying to write into a file but failed at doing so as it's not writable. My gut feel is this is not a bug of Filestash but a permission problem with [`/app/data/state/db/search/`](https://github.com/mickael-kerjean/filestash/blob/f5f0f30cea7d4f1d2ef7b7c462c0eaa682a59615/server/model/search.go#L342). As a side note the entire folder under `/app/data/state/` should be writable by the user filestash

**Comment by kewvention** [comment]
Does it's apply to the docker build. I merely upgraded the docker version of the app and don't have any mount points assigned.

**Comment by kewvention** [comment]
think i found the problem. inside the docker container itself, the directory doesnt belong to filestash anymore, but _apt:systemd_journal
no clue how it became that since i just pulled the latest image and redeployed. now trying to update the permissions but i dont have the root password to do so

**Comment by mickael-kerjean** [comment]
> doesnt belong to filestash anymore, but _apt:systemd_journal

That's very odd, the demo server which is created using the command written in the documentation has this:
```
filestash@8b8ab240a5df:/app$ ls -Rlah data/state/db/ | grep -v sql
data/state/db/:
total 80K
drwxr-x--- 3 filestash filestash 4.0K Oct  8 10:57 .
drwxr-x--- 5 filestash filestash 4.0K Aug 15 10:12 ..
drwxr-x--- 2 filestash filestash  20K Oct  9 11:28 search

data/state/db/search:
total 12M
drwxr-x--- 2 filestash filestash  20K Oct  9 11:28 .
drwxr-x--- 3 filestash filestash 4.0K Oct  8 10:57 ..
```

> but i dont have the root password to do so

The image is made in a way than me too I don't have it neither. Instead you can enter your container with the option `-u 0` which say to docker log me in not with the default user but the one which has an id of  0 (which is root)

**Comment by kewvention** [comment]
ended up deleting the entire image and pulling it again. this time it worked and all is good now. upgrading from an older image didnt work however.
