### ISSUE TITLE
[bug] After Docker restart admin password is invalid

### ISSUE THREAD

**Issue by Rustymage** [mickael-kerjean/filestash#208]
- description of the bug
After successfully installing and running filestash in a docker container, on a windows computer, the instance works as expected. With persistent storage attached, the instance does not allow admin login after a restart. The SFTP login on the front end (that worked previously) now claims invalid key size.

- step by step instructions to reproduce the bug
Install filestash. Setup and check SFTP works. Restart container, try to login.

- observed behaviour
Admin password is invalid and SFTP login says invalid key size.

- expected behaviour
Login should be allowed.

**Comment by mickael-kerjean** [comment]
Hello thank you for the report. I'm away at the moment, it will take a few more days to get back and look at this.

**Comment by mickael-kerjean** [comment]
I can't replicate the error, restarting the container doesn't get me any error using SFTP

> on a windows computer

As mention on the documentation, Filestash only support installation on Linux as there's no kind of testing happening on Windows. Also, considering the project doesn't have any paying customer at the moment, I'm not keen on giving Microsoft a fee from my own pocket to make it happen

**Comment by Rustymage** [comment]
Hi,

I have restarted the container fresh and I don't seem to have the issues again. The only difference is that I now have to insert the SFTP password to 'login' and get access to the folder structure. Before I used the 'remember me' function of Filestash.

Perhaps it was that!

The persistent storage was a docker volume linked to /app/data or whatever it is, I can't remember off hand right now.

Anyway, awesome software :)

Cheers

**Comment by mickael-kerjean** [comment]
> docker volume linked to /app/data

I might know what has gone wrong then:
```
- Filestash initally set a secret_key in `/app/data/state/config/config.json` which is used for all sort of features that use cryptography.
- When using as a volume `/app/data`, only root or your user could write to the config.json, the user from the containers can't do anything to it and can't set up the secret_key that it needs to run properly
- result => you experience weird things
```

In essence, try to volume only `/app/data/state/config/config.json` and give config.json the relevant access right so that the application can write into this file

> Anyway, awesome software :)

Good to see it is getting some love!!

**Comment by mickael-kerjean** [comment]
Also, I'll soon publish a fix that will log when something like this happen again so that it can be fix
