### ISSUE TITLE
[bug] org-mode html export error

### ISSUE THREAD

**Issue by JohnWang1023** [mickael-kerjean/filestash#209]
When exporting an org-mode file the following text is displayed.

{"status":"error","message":"Emacs has quitted: 'exit status 255'"}

```
~/filestash$ sudo docker-compose up

filestash is up-to-date
Attaching to filestash
filestash | 2019/10/23 00:34:20 INFO Filestash v0.4rc starting
filestash | 2019/10/23 00:34:20 INFO [http] starting ...
filestash | 2019/10/23 00:34:21 INFO [http] listening on :8334
filestash | 2019/10/23 00:40:56 ERROR stdout: | stderr:Loading /etc/emacs/site-start.d/00debian.el (source)...
filestash | Please install htmlize from https://github.com/hniksic/emacs-htmlize
filestash | 
filestash | 2019/10/23 00:40:56 INFO HTTP 400 GET 3571.3ms /api/export/private/text/html/ORG_FILES/TODO.org

```

**Comment by mickael-kerjean** [comment]
Hello, 
Can you provide a small org document that can trigger this error?

**Comment by JohnWang1023** [comment]
I figured out what the solution is. I downloaded htmlize from https://github.com/hniksic/emacs-htmlize to /app/data/state/config in the docker container and I add `(require 'htmlize)` to emacs.el.

**Comment by mickael-kerjean** [comment]
Effectively, thank you for the report. This should be fix by the above commit
