### ISSUE TITLE
[bug] Accessing Windows SFTP Creates Malformed Path

### ISSUE THREAD

**Issue by xcjs** [mickael-kerjean/filestash#210]
This is similar to #53 but not quite.

After logging into a Windows SFTP host, the user directory loads without a problem. However, as soon as I click on a directory, the colon in the path is replaced by %3A. This means that:

     https://host/files/C:/Users/Me/Subdirectory/

becomes:

    https://host/files/C%3A/Users/Me/Subdirectory/

This creates an "Unknown path" error. It seems like the %3A is being passed to the filesystem lookup instead of being converted to a colon.

If it makes a difference, I am using the Docker release.

**Comment by xcjs** [comment]
As an additional note, I have confirmed that replaced the %3A with a colon manually in the URL does load the directory as intended.

**Comment by mickael-kerjean** [comment]
This should be solve with ae2ef413b36bce77949a36017184a4c4294cb59b. Feel free to comment back if there's still issues and I'll reopen
