### ISSUE TITLE
[bug] .mov files not recognied

### ISSUE THREAD

**Issue by prabirshrestha** [mickael-kerjean/filestash#211]
When opening .mov files I get the following error.

<img width="958" alt="Screen Shot 2019-11-11 at 11 27 29 PM" src="https://user-images.githubusercontent.com/287744/68650991-2a2a8500-04db-11ea-9eab-42944e4a0e38.png">

**Comment by mickael-kerjean** [comment]
At this stage, Filestash doesn't support format your browser can't handle and .mov isn't something browser can typically read. This limitation is the reason [the landing page](https://www.filestash.app/) showcase video transcoding as a feature in the roadmap. When this feature lands, it will handle a much larger choice of video format including .mov files

**Comment by prabirshrestha** [comment]
Here is the browser console log.

```
GET https://somedomain.com/api/files/cat?path=%2Fphotos%2F2010%2F03%2F20%2FIMG_0069.p2.MP4 net::ERR_ABORTED 500 (Internal Server Error)
chunk_video_2_6db0456a19390825d90f.js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. i {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}
```

I'm using using webdav connectin from filestash talking with a remote crypted rclone backed by azure blogs.

This is the response header for the request.

```
Request Method: GET
Status Code: 500 Internal Server Error
Referrer Policy: same-origin
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 117
Content-Type: video/mp4
Date: Fri, 15 Nov 2019 12:06:56 GMT
Server: nginx/1.17.3
Set-Cookie: download=; Path=/; Max-Age=0
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
```

I'm on a mac so my browser does support the .mov. If I download it and run it will work.

**Comment by mickael-kerjean** [comment]
> Status Code: 500 Internal Server Error

I'm aware of this one as I've been hunting it since quite a few hours already, will provide a fix when ready

> I'm on a mac so my browser does support the .mov. If I download it and run it will work.

Interesting, I wasn't aware this was working on a mac.

**Comment by mickael-kerjean** [comment]
> GET https://somedomain.com/api/files/cat?path=%2Fphotos%2F2010%2F03%2F20%2FIMG_0069.p2.MP4 net::ERR_ABORTED 500 (Internal Server Error)

71f9b24bf71c38633a83158e0f95adea8740a152 should address this
