### ISSUE TITLE
[bug] map for image not loading

### ISSUE THREAD

**Issue by prabirshrestha** [mickael-kerjean/filestash#212]
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data:".

IMG_6760.c.JPG:1 Refused to load the image 'https://maps.wikimedia.org/osm-intl/11/1819/805.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".
<img width="286" alt="Screen Shot 2019-11-11 at 11 33 55 PM" src="https://user-images.githubusercontent.com/287744/68651225-d10f2100-04db-11ea-85f2-26a4a3fceb7b.png">

**Comment by mickael-kerjean** [comment]
Hello,

Thanks for the report. This has already been fix in 5496796a12916526ea16e1c91b51ca04cfc1ffcd
Although the build hasn't been pushed yet as additional issues got caught along the way by CI but if you create your own build, you won't have that error
