### ISSUE TITLE
[Feature Request] Sorting directories first, but lexicographically

### ISSUE THREAD

**Issue by dumblob** [mickael-kerjean/filestash#214]
Any plans to add yet another sorting flavor - namely separately sorting directories first and then separately files (i.e. combination of the current `sort by type` and `sort by name`)?

Currently if one chooses sorting based on name, directories and files will end up mixed. I think many people are not used to this (including myself), so I'm creating this tracking issue for that :wink:.

Btw. filestash looks like a really nifty software - it's easy to setup (except for slightly misleading error messages like "invalid password" when the SFTP directory was actually set to an invalid path or "connection refused" when actually the host wasn't reachable at all due to incorrect DNS translation) and seems to do nearly everything needed (though I'd wish to switch on/off hidden files visibility interactively/on_demand in each folder and not as a system-wide option).

**Comment by mickael-kerjean** [comment]
Sounds like a great idea. Can you create a pull request for it?

**Comment by dumblob** [comment]
I'm glad you find the idea fitting. I'll see how I'm on it with my time (I need to dive into the code first, which will take time) - currently it seems after Christmas, there might be a short time window :wink:.

**Comment by mickael-kerjean** [comment]
Sounds good to me. The sorting you want to get better is done [here](https://github.com/mickael-kerjean/filestash/blob/ae2ef413b36bce77949a36017184a4c4294cb59b/client/pages/filespage.helper.js#L21-L38)
