### ISSUE TITLE
[bug] Password fields not obfuscated on login page on Firefox mobile

### ISSUE THREAD

**Issue by williewillus** [mickael-kerjean/filestash#217]
![Screenshot_20191220-234218_Firefox](https://user-images.githubusercontent.com/2015032/71303750-b8b7df00-2382-11ea-8ef3-9bbf7e609dbb.jpg)

Description: title
Steps: navigate to demo.filestash.app on Firefox mobile and type in a password field
Observed: input shown as plain text, keyboard suggestions active
Expected: input obfuscated as dots

**Comment by williewillus** [comment]
Firefox mobile version: latest on Play Store at time of writing: 68.3.0

**Comment by williewillus** [comment]
Seems to work fine on desktop firefox 71

**Comment by mickael-kerjean** [comment]
I can't replicate this, can you create a pull request?

**Comment by lorenzgith** [comment]
The password field one the login page is not correctly defined as such. Even password managers cannot recognize the password field in its current form

**Current:**
`<textarea type="text" rows="1" name="password" placeholder="Password" autocomplete="new-password" class="component_textarea"></textarea>`

**The correct element would be:**
`<input type="password">`

**Screenshot**
![Screenshot from 2020-02-19 08-55-15](https://user-images.githubusercontent.com/58948651/74813893-60577c00-52f6-11ea-880e-77a1281c3d9d.png)

**Comment by mickael-kerjean** [comment]
It's made like this everywhere else. With SFTP, we wanted to allow people to copy and paste private key to login and because private keys have multi lines the input password type was causing issues (Unfortunatly there's no password type on textarea ...). There might be a workaround to go back to the input type password but the current solution should still hide your password as you type, I don't know what's going differently on your device

**Comment by lorenzgith** [comment]
Does it make sense to display several lines if the entered text is hidden anyway?

**Comment by mickael-kerjean** [comment]
It's not about display but about being able to copy and paste a private key and get it to connect

**Comment by lorenzgith** [comment]
Ah okey I see, makes sense.
How about two different input fields?
One for passwords and one for keys.

**Comment by mickael-kerjean** [comment]
This would have been the easy route. That option got discarded because of the poor user experience. The best solution here is to fix what you're seeing which I can't replicate from my end
