### ISSUE TITLE
Reverse proxy - nyan cat screen of death

### ISSUE THREAD

**Issue by codewithzac** [mickael-kerjean/filestash#218]
Hi!

Having difficulties with both nginx and apache as a reverse proxy for filestash. For nginx, I've tried using the configuration shown at https://www.filestash.app/docs/install-and-upgrade/. For apache, I tried the following fairly standard config:

```
ProxyPass / http://localhost:8334/
ProxyPassReverse / http://localhost:8334/
```

When I'm using Apache - in the browser, I get what I can only describe as a "nyan cat screen of death" - the cat races across the screen and the rainbow 'tail' stays on the screen. The error message in the Network tab appears to be "Couldn't boot Filestash" - I'm also seeing HTTP 400 errors in the browser Network tab when trying to get the config file, so I'm guessing there's a missing parameter somewhere in the config.

The error message when I'm using nginx is "400 Bad Request: malformed Host header". No nyan cats for me :(

I tried changing the logging to DEBUG, but there's nothing in the error log. The configure tab has the correct hostname per what I'm trying to reverse proxy from. I've tried leaving this blank, but I get the same error.

Any suggestions?

**Comment by mickael-kerjean** [comment]
The `Couldn't boot Filestash` message is given when it can't receive some of the data coming from the server as it seem to give "400 Bad Request: malformed Host header". I think your problem comes from [there](https://www.filestash.app/docs/install-and-upgrade/#once-you-are-up-and-running) => your `General -> host` config in the admin console. 

I'm closing this ticket as this is clearly a support query and we're moving away from github for support to IRC: https://support.kerjean.me/ Feel free to ask your questions in there instead

**Comment by amilino** [comment]
I would also like to know how to configure it to work under Apache with reverse proxy.

**Comment by codewithzac** [comment]
I submitted a pull request to have the documentation updated, however here's my working config for Apache:

`
<VirtualHost *:443>
  ServerName your.filestash.url
  ServerAdmin your@email.address

  ErrorLog /path/to/error.log
  CustomLog /path/to/access.log combined

  Header unset X-Content-Type-Options

  ProxyPreserveHost On
  ProxyPass / http://localhost:8334/
  ProxyPassReverse / http://localhost:8334/

</VirtualHost>
`

You'll need to add whatever you use for your SSL config.

**Comment by amilino** [comment]
This is what I am using at it doesn't work:

> <VirtualHost *:20080>
> 	Header unset X-Content-Type-Options
> 	ProxyPreserveHost On
> 	<Location "/filestash/">
> 		ProxyPass http://localhost:8334/
> 		ProxyPassReverse http://localhost:8334/
> 	</Location>
> </VirtualHost>

**Comment by codewithzac** [comment]
To the best of my knowledge, `ProxyPass` directives aren't valid in a `Location` context: https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass

**Comment by amilino** [comment]
It is working perfectly normal inside Location node.

**Comment by codewithzac** [comment]
Don't know then I'm sorry - I can only tell you what works for me.

If you're getting a 404 in the Apache logs, something isn't being found by the proxy. Is Filestash actually running on port 8334?

**Comment by amilino** [comment]
Yes it is working on 8334 perfectly fine. That is very strange, anyway thank you for fast reply and sharing your experience.

**Comment by amilino** [comment]
Ok, I moved a little bit, added assets for location:

```
	Header unset X-Content-Type-Options
	ProxyPreserveHost On
	<Location "/filestash/">
		ProxyPass http://localhost:8334/
		ProxyPassReverse http://localhost:8334/
	</Location>
	<Location "/assets/">
		ProxyPass http://localhost:8334/assets/
		ProxyPassReverse http://localhost:8334/assets/
	</Location>
```

Now I have errors for things that are created on the fly in JS.
```
app_be848094ea64b18bb5f5.js:2 GET http://192.168.188.201:20080/overrides/xdg-open.js net::ERR_ABORTED 404 (Not Found)
app_be848094ea64b18bb5f5.js:2 GET http://192.168.188.201:20080/api/config 404 (Not Found)
```

**Comment by amilino** [comment]
Ok finally it is working with new virtual host. I can live with that. 👍
