### ISSUE TITLE
[bug] Can't connect a git repository

### ISSUE THREAD

**Issue by Tobix99** [mickael-kerjean/filestash#219]
Hey,
I've tried the self hosted docker solution as well as the demo to connect a git repo to filestash. Every time I tried to add a GitLab/GitHub repo it gives me the "Invalid password" error on the bottom left in the browser and no log info whatsoever (tried setting it to DEBUG, but didn't change anything).

I'm using the latest Firefox.

The expected behaviour is to add the git repo.

**Comment by mickael-kerjean** [comment]
Can you give reproduction steps? It works from my end on the demo instance: https://demo.filestash.app/login?type=git&repo=https://github.com/mickael-kerjean/nuage_org_demo

**Comment by Tobix99** [comment]
So I executed
`sudo docker run -d --name='Filestash' -p 8334:8334 machines/filestash` and naviagted to localhost:8334

There I created an admin password and selected no to **not** expose anything. Then I switched to the landing page and entered my GitHub-Test repo and my GitHub credentials. After that, the error "Invalid Password" occurs on the bottom right.

**Comment by Tobix99** [comment]
I found the error:

If the repo is empty it gives me the "Invalid Password" error. I've added a md file to my empty repo and now I log in and can edit everything.

Thanks for your help! Maybe edit the error message, so that it don't state the "Invalid Password" error message.
