### ISSUE TITLE
[poll] feature-request: deep syncthing integration

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/filestash#220]
Today, Filestash has a basic integration mechanism in place exposing a syncthing instance to an admin. Want a deeper integration? Something real simple an fully integrated your users can use without being an admin? 

We will make it happen if we reach 100 :+1:

**Comment by alpakaxaxa** [comment]
Using syncthing with filestash makes so much sense. A deeper integration would be fantastic

**Comment by grigio** [comment]
Filestash + Syncthing is the best software combo possible!

**Comment by abh153k** [comment]
+1. Currently syncthing doesn't have any option to browse files from a browser, afaik

**Comment by wx-Yao** [comment]
Hey thanks for the great project!:) I've been searching for this for a while. Is there any workaround we can use to do some "tricky integration" now? I really really love the integration can happen. but now i just need a way to set things up.

btw the bot tagged this thread as "wont fix", which should be misleading .... can someone make it feature request or something?

**Comment by guizmoau** [comment]
+1

**Comment by mickael-kerjean** [comment]
> btw the bot tagged this thread as "wont fix", which should be misleading .... can someone make it feature request or something?

The bot is closing stale issues and this one hasn't seen much activity for a while. If this happen again, please comment, I'd be happy to reopen again.

> I've been searching for this for a while. Is there any workaround we can use to do some "tricky integration" now?

As of today, the integration is very bare bone as it only do a reverse proxy to syncthing to avoid anyone from the internet accessing your syncthing interface. If you're interested in a deeper integration that hook into the syncthing API, a PR would be awesome :smile:

**Comment by guizmoau** [comment]
it is not working for me at the moment and can't login to syncthing via /admin/syncthing

my syncthing server is accessible via the adress as configured in filestash at http://localip:8384

**Comment by mickael-kerjean** [comment]
By default, the feature is disable. To get it to work, you need to:

1. set it up from the admin console

2. restart Filestash

3. acess it from `/admin/syncthing`

If that's not working on your side, can you send some steps to reproduce what you're seeing?

**Comment by guizmoau** [comment]
Done !
It still doesn't work.

I don't have a "standard" setup as I am not using docker...
My syncthing server is installed and functionning properly tho

**Comment by poVoq** [comment]
Maybe this could be a simple first step to access Syncthing shares:
https://github.com/VictorNine/syncthingclient
