### ISSUE TITLE
[Feature Request] Preview threshold

### ISSUE THREAD

**Issue by msmicker** [mickael-kerjean/filestash#221]
Can a size limit be set to determine whether to preview a full file or preview a portion? I am sharing larger content and larger text based files are failing.

**Comment by mickael-kerjean** [comment]
Not at this stage. How large are those files? 

When it comes to handling large files, a few solutions got discussed in the past:
1. doing some server side compression. The feature is awaiting for a pull request, see issue #196
2. disable the preview. We've recently add the capability for a plugin to decide which application should be open by the browser depending on the document mime type. This is used by the [openoffice plugin](https://github.com/mickael-kerjean/filestash/blob/c2990e77d9e5d79a376a953cde9a9d05889cf967/server/plugin/plg_editor_onlyoffice/index.go#L89-L98)
