### ISSUE TITLE
[bug] Syncthing description in config wrong

### ISSUE THREAD

**Issue by pagdot** [mickael-kerjean/filestash#224]
Propably after copy-pasting code the description didn't get changed for syncthing:

![grafik](https://user-images.githubusercontent.com/2229858/73771109-f54a6900-477d-11ea-92fc-51ed5357006f.png)

Error in [server/plugin/plg_handler_syncthing/index.go:29](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_handler_syncthing/index.go#L29)

**Comment by mickael-kerjean** [comment]
thank you for the report, you're right that was a copy and paste residue which should be fix now
