### ISSUE TITLE
[Feature Request] Show 'Create File/Directory' link on 404 page

### ISSUE THREAD

**Issue by dmayle** [mickael-kerjean/filestash#226]
Hi, I'm testing out Filestash as a wiki replacement, where the workflow tends to go Write -> Link -> Write.

Right now, if I add a link and click on it, I receive the 404 page, and clicking the home link brings me to the root of the repo.  Creating articles this way is tedious, as you have to collect a list of unreferenced links and then go to the respective folders and create the new documents so that the links work.

This is a request to show the 'Create' link that would allow the user to create a new file or directory using the current name.

I understand that a recursive create-to-root might not be a good idea, so limiting this to the case where the parent directory already exists is fine.

**Comment by mickael-kerjean** [comment]
That would effectively be a great feature. Care to work on it?

**Comment by dmayle** [comment]
I don't yet have a development environment for filestash.  I may take a crack at it, but it won't be until March, at least.

**Comment by mickael-kerjean** [comment]
Sounds good. From a development environment perspective, it should be painless: https://github.com/mickael-kerjean/filestash/blob/master/CONTRIBUTING.md#building-from-source
