### ISSUE TITLE
[bug] Video playback broken when transcoding is turned off (MIME type mismatch)

### ISSUE THREAD

**Issue by ViRb3** [mickael-kerjean/filestash#234]
I disabled video transcoding from the admin panel, and now whenever I try to open a video file I get a blank page. Opening the browser console, I can see the following error:
```
The resource from “https://<redacted>/overrides/video-transcoder.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by mickael-kerjean** [comment]
Looks like a bug, thank you for the report, will try to solve this one whenever I can put some time aside

**Comment by mickael-kerjean** [comment]
The above commit should be fixing it. Thank you for the report! 
Let me know if there's something wrong and we'll reopen
