### ISSUE TITLE
[Feature Request] show upload percentage and add the option to cancel upload

### ISSUE THREAD

**Issue by santy-mvzg** [mickael-kerjean/filestash#235]
hello good morning, as the title says, it would be good in the ftp part to add an option that shows the% of the upload act of the file and the option to cancel the upload of the same.
Thank you

**Comment by mickael-kerjean** [comment]
Sounds good to me. Can you work it out and create a pull request?

**Comment by santy-mvzg** [comment]
Hi Mickael, sorry for the delay. I don't know much how it's done, I discarded the project and when I tried to compile it, it gave me errors, and about the "go" language, I don't know about it, that's why I could write it as a "Feature Request". If I fit a little more, I would definitely love to help, since I think it's a very good project.
Greetings.
