### ISSUE TITLE
Not able to change port

### ISSUE THREAD

**Issue by amilino** [mickael-kerjean/filestash#236]
I am not able to change the port. What I did was changing the port in admin section what is then reflected into config.json file.

When I start application by running executable I get this every time:
`2020/03/01 15:59:33 INFO Filestash v0.4rc starting`
`2020/03/01 15:59:33 INFO [http] starting ...`
`2020/03/01 15:59:35 INFO [http] listening on :8334`

What am I doing wrong?

**Comment by mickael-kerjean** [comment]
I have no idea and I can't replicate what you're getting. Can you elaborate and give all the steps you're going through?

**Comment by amilino** [comment]
This is what I did on my Raspberry Pi 4:
```
wget https://github.com/ViRb3/filestash/releases/latest/download/filestash_Linux-armhf.tar
tar xvf filestash_Linux-armhf.tar --strip-components 2 -C ~/filestash
/home/pi/filestash/filestash
```

and this is how part of my config.json file looks like:
```
{
    "general": {
        "name": null,
        "port": 20084,
        "host": null,
```

**Comment by mickael-kerjean** [comment]
This isn't the documented way to install Filestash

**Comment by amilino** [comment]
What is then documented way to do it on RPi?

**Comment by mickael-kerjean** [comment]
Support for Raspberry pi isn't official as I don't have the necessary hardware to create the build. The steps to create the build yourself on the pi is shown [there](https://github.com/mickael-kerjean/filestash/issues/142#issuecomment-576127077).

**Comment by amilino** [comment]
Can you extend executable to accept port as a parameter? That would save me...
