### ISSUE TITLE
[bug] Dockerfile mounts the wrong volume out-of-the-box

### ISSUE THREAD

**Issue by PeterCxy** [mickael-kerjean/filestash#238]
I followed what is described on <https://www.filestash.app/docs/install-and-upgrade/>, which stated that installation via Docker is the only supported method, to install my own instance of Filestash. However, I was set back right away by a mysterious `404 Not Found` that popped up as soon as I tried to open the admin interface for the very first time.

After a lot of digging around, I realized that the Dockerfile mounts a volume at `/app/data` by default, while this path also contains all the resources other than just configurations. Mounting a volume here makes all of them go away and hence the 404 error. It seemed to me that the correct path to mount the volume should be at `/app/data/state`, which, by the name, should store everything that needs to be persisted.

Another issue is that, after mounting volume at the (presumably) correct path, the user interface failed to show any file icons. I checked `F12` and noticed that all `Content-Type` were set to `application/octet-stream`, which would not work for an icon in SVG format. I found the issue #126 talked about the same problem, and there I got the solution to put the new `mime.json` at `/app/data/config/mime.json`, but it turned out that this path is now gone -- it should now be `/app/data/state/config/mime.json`. This is within the `/app/data/state` directory that we just persisted by mounting a volume at! Can we maybe move this file to another location so that mounting a volume for persistence will not override it?

Otherwise, a very elegant and useful product. I came here due to the shutdown of the Go `filebrowser` project, and so far very happy with it except for the two issues mentioned above.

**Comment by PeterCxy** [comment]
Also the OnlyOffice included in the `docker-compose.yml` does not seem to really work. I'm still figuring out how to make it actually work.

**Comment by mickael-kerjean** [comment]
This doesn't seem to be a bug but an issue on how docker is being used. By default with docker, mounting a volume will literally wipe out everything sitting on the container side and replacing that data with what you have in your host. In such scenario, wiping out all the configurations, Filestash can't even load properly and is throwing all the errors you are experiencing.

To fix that volume problem, you need to use `docker cp` which as the name imply will give you a way to copy files from a containers into a host so that you can then create the volume the way you want

**Comment by PeterCxy** [comment]
No, this was not a support request. The issue was that the Dockerfile by default uses a volume at `/app/data` which is incorrect at least for the latest version of filestash. It seems to have been fixed by a commit 6 days ago though.
