### ISSUE TITLE
Videos not playing at all

### ISSUE THREAD

**Issue by amilino** [mickael-kerjean/filestash#239]
Not abe to play mp4 videos. Used sftp connection and demo site as well.

No JS error message. Any idea how to debug it?

**Comment by mickael-kerjean** [comment]
Sounds like a bug. Fixing it mean first I need to replicate it. Can you share the steps you went through for me to replicate it from the demo site?

**Comment by amilino** [comment]
https://demo.filestash.app/login
Choose WebDav
Address: http://1raspberrypi.mooo.com:20080/debugging/
Username: test
Password: test123

Try to play Christmas Fireplace Pluto TV 720.mp4 file.

**Comment by amilino** [comment]
Any news?

**Comment by amilino** [comment]
Closing this on my end due to lack of response and as I am no longer using this project.
