### ISSUE TITLE
Network drive - doc

### ISSUE THREAD

**Issue by azukaar** [mickael-kerjean/filestash#241]
I setup an instance connecting to S3, and created a sharing link, but unlike what the README mention, I cannot use it as a windows' network drive.
The documentation does not seem to mention any additional step to get this working. Any ideas? 
Thanks !

**Comment by mickael-kerjean** [comment]
Thank you for the report.

> The documentation does not seem to mention any additional step to get this working. 

The whole idea of the network drive via shared link is to literally get it to work magically with no additional steps. The links are full fledge webdav server that should in theory be picked up by your file manager.

> I cannot use it as a windows' network drive.

I've been testing it on a mac and from linux, not windows at this stage. I guess I'll need to get a deeper look on Windows specifically. Another option is for someone to create a pull request.

**Comment by azukaar** [comment]
Okay thanks for the response, so I can confirm the link don’t work on Windows as of now
