### ISSUE TITLE
[Feature Request] add support to view raw file with / paths

### ISSUE THREAD

**Issue by prabirshrestha** [mickael-kerjean/filestash#242]
Currently to view raw we need to set the path like this. `https://filestash.com/api/files/cat?path=%2Fapps%2Findex.html`. Would it be possible to have a raw mode that looks something like this `https://filestash.com/api/files/raw/apps/index.html`. I would like to host some static files for personal use that contains html, javascript and css but without firing up an enter website and would just like to use filestash. Besides the download button I would like to have "View in raw browser mode".

**Comment by mickael-kerjean** [comment]
I love the idea. That's roughly how the org mode export is working at the moment with some more emacs related features. eg: [this document](https://demo.filestash.app/view/getting_started.org?share=WE7TGjN) can be exported into [html](https://demo.filestash.app/api/export/WE7TGjN/text/html/getting_started.org)

The full things isn't there yet but I'd gladly accept a pull request that's adding that functionality
