### ISSUE TITLE
[support] How to run docker machines/filestash?

### ISSUE THREAD

**Issue by lockwiser** [mickael-kerjean/filestash#245]
Hello,

```
~# docker run -d machines/filestash
Unable to find image 'machines/filestash:latest' locally
latest: Pulling from machines/filestash
704f4240fcc9: Pull complete
bc2facc4e598: Pull complete
cb6c57ed3559: Pull complete
Digest: sha256:5dcd3a81ea7185753d76c6d7de5b07e6ab829cf36475e64f09375ecf2b8a1022
Status: Downloaded newer image for machines/filestash:latest
df09db80f601e201903e84b7eabe8dc42aa3080fe9c21144af1cc8e91d4f9228
```

`IP:8334` - Not work

How to run a docker container?

**Comment by lockwiser** [comment]
`onlyoffice/documentserver   latest              61f7051ea308        2 weeks ago         2.14GB`
2.14GB - very large.Is it possible not to use documentserver?

**Comment by lockwiser** [comment]
I just run
```
    docker run \
        -d \
        --name filestash \
        --restart always \
        --network mynet \
        -p 80:8334 \
        machines/filestash
```
and everything works.
Tell me, what functions do I lose if I do not use onlyoffice/documentserver?

**Comment by mickael-kerjean** [comment]
Please, don't create tickets on github for support. Instead, you can either:
- visit the community support on freenode #filestash. A searchable archive is available at https://support.filestash.app If you don't already have an IRC client, you can try this link: https://kiwiirc.com/nextclient/#irc://irc.freenode.net/#filestash?nick=guest??
- register for enterprise support at https://www.filestash.app/pricing/#support
