### ISSUE TITLE
[support] How to add custom style?

### ISSUE THREAD

**Issue by lockwiser** [mickael-kerjean/filestash#246]
Hello,

Its possible include custom css style?

**Comment by mickael-kerjean** [comment]
Please, don't create tickets on github for support. Instead, you can either:
- visit the community support on freenode #filestash. A searchable archive is available at https://support.filestash.app If you don't already have an IRC client, you can try this link: https://kiwiirc.com/nextclient/#irc://irc.freenode.net/#filestash?nick=guest??
- register for enterprise support at https://www.filestash.app/pricing/#support
