### ISSUE TITLE
[Feature Request] Really awesome project here, anyone got it running behind nginx?

### ISSUE THREAD

**Issue by aaronnewsome** [mickael-kerjean/filestash#247]
So glad I stumbled upon this project. Really great work. I've spent a great deal of time trying to get it up and running the way I need to use it. Still running into issues here and there. Given the state of the documentation (or lack of), it really is just a matter of a LOT of trial and error trying to get things working right.

If I run the machines/filestash image directly with DOCKER on my laptop, everything works reasonably well. At one point, I even had the Onlyoffice editors working too.

Problem is that when I spin it up in my kubernetes cluster and put it behind my nginx proxy, things just break. Right away, I notice that the Folder icons were missing when accessing Filestash via nginx reverse proxy. Some other weirdness starts to happen too.

I didn't really start this issue to post about the struggles I'm having. I'm really looking for anyone who has this up and running behind nginx reverse proxy + SSL, with Onlyoffice editors working AND folder icons working correctly.

If so, would you mind sharing the pertinent parts of your configs. It sure would save me from even more trial and error troubleshooting.

**Comment by w0k3** [comment]
The nginx configuration is quite simple, use something like this. You shouldn't use a Feature Request for such questions though.

> Technical support is only available at https://support.filestash.app

```
server {
  listen [::]:443 ssl;
  listen 443 ssl;

  server_name filestash.example.com;

  ssl_certificate /etc/letsencrypt/live/filestash.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/ffilestash.example.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Origin '';

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    proxy_pass http://127.0.0.1:8334;
    proxy_read_timeout 86400;
  }
}

server {
  listen 80;
  listen [::]:80;

  server_name filestash.example.com;

  return 301 https://$host$request_uri;
}
```

**Comment by w0k3** [comment]
The nginx configuration is quite simple, use something like this. You shouldn't use a Feature Request for such questions though.

> Technical support is only available at https://support.filestash.app

```
server {
  listen [::]:443 ssl;
  listen 443 ssl;

  server_name filestash.example.com;

  ssl_certificate /etc/letsencrypt/live/filestash.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/filestash.example.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Origin '';

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    proxy_pass http://127.0.0.1:8334;
    proxy_read_timeout 86400;
  }
}

server {
  listen 80;
  listen [::]:80;

  server_name filestash.example.com;

  return 301 https://$host$request_uri;
}
```

**Comment by acivitillo** [comment]
Can you give us some info on your docker setup? How are you orchestrating the containers? I had exactly the same problem and decided to create a sub-domain. So I have `cloud.assyem.com` instead of `assyem.com/filestash`.

The issue here is that most of filestash assets are served on the root url. Take a look at the cloud icon for instance, it is served like so `filestash.yourdomain.com/assets/logo/apple-touch-icon.png`.

If you are trying to run an nginx location `yourdomain.com/filestash` it would work for the index page, but it would be broken for the assets icons, which is the weirdness you probably noticed.

@w0k3 has the right setup with `server_name filestash.example.com`, using a sub-domain.

Also I am new to orchestrators but I noticed nginx is very hard to use as a reverse proxy to a cluster, I use Fabio instead (http://assyem.com/installing-filestash-with-nomad.html).
