### ISSUE TITLE
[Feature Request] i18n

### ISSUE THREAD

**Issue by w0k3** [mickael-kerjean/filestash#248]
Hello,

I'd like to localize Filestash to my native language, are there any plans for actual i18n support?

I have only found a hack (`switch(navigator.language.split("-")[0])`) for German weekdays  (906e94b831fed402a813e6fdcfc60f2c58b7d760) and no proper i18n support (e.g. JSON files for locales)...

**Comment by mickael-kerjean** [comment]
This would be quite awesome indeed. Any chance you'd help with German once the setup is made?

**Comment by w0k3** [comment]
Sure, my German is not tip-top though. I definitely can provide Slovak and Czech, maybe Russian too.

**Comment by mickael-kerjean** [comment]
status update on i18n, some language take more space than other and the layout can sometimes break when labels are too long: [example in French](https://archive.kerjean.me/public/2020/demo.filestash.app_files_(iPhone%205_SE).png). Any suggestions on working this out?

**Comment by w0k3** [comment]
It's common in other languages too, the easiest but not always best solution is to shorten the translation (abbreviations, synonyms...), slightly more advanced solution involves some compromises in the layout to add some space for translations. The possibly trickiest solution would enable CSS overrides in translations - but this can break future releases for certain translations and adds many moving parts.

**Comment by w0k3** [comment]
Some CSS modifications are to be expected anyway, for example right-to-left support for certain languages...

**Comment by mickael-kerjean** [comment]
Yep, abbreviations did work without breaking the layout. At the moment, the translation is getting pulled from a JSON that looks like this: https://github.com/mickael-kerjean/filestash/blob/45e386984904390acb7d8f8b1eefee5d717e6a97/client/locales/fr.json

As of right now, the idea is to keep things simple by creating another json with the same schema for other languages

**Comment by mickael-kerjean** [comment]
It's all working now, to add a new translation you can:
1. create a new json file under: https://github.com/mickael-kerjean/filestash/tree/master/client/locales
2. fill the newly created json with the translated values: https://github.com/mickael-kerjean/filestash/blob/master/client/locales/fr.json
3. register your new translation to the frontend in [here](https://github.com/mickael-kerjean/filestash/blob/master/client/index.js#L83)

**Comment by mickael-kerjean** [comment]
I made translation in about 40 different languages from google translate, if you want to contribute to make something better, feel free to make a PR to anything from: https://github.com/mickael-kerjean/filestash/tree/master/client/locales
