### ISSUE TITLE
[bug] SFTP advanced admin settings not working

### ISSUE THREAD

**Issue by pagdot** [mickael-kerjean/filestash#249]
I have multiple issues with the advanced settings:

- I don't know what the left checkbox does
  When configuring a SFTP backend it isn't clear, which of the two checkboxes in the for the advanced setting does. The left one (labeled 1 in the picture) seems to do nothing, the right one (2) expands the advanced settings.
- Most settings don't seem to get saved
  I've tried to setup a custom path, but when reloading the page both checkboxes (1 and 2) get unchecked and if I check them again my setting for the path is missing. Only the checkbox for the path is still checked. When trying to login as a user on the sftp backend I'm at the default path (my home directory)

![grafik](https://user-images.githubusercontent.com/2229858/78557798-bf734080-7811-11ea-82a2-c8cda33c2508.png)

Some Infos:
- I'm running the filestash off of  the *machines/filestash* docker image
- SFTP target runs Ubuntu 18.04

**Comment by mickael-kerjean** [comment]
> I don't know what the left checkbox does

This is to setup the login screen:
- left checkbox checked:
![screenshot_20200407_224634](https://user-images.githubusercontent.com/13233076/78670852-bd000c00-7921-11ea-8843-ab1d524c1fc5.png)
- left checkbox unchecked:
![screenshot_20200407_224643](https://user-images.githubusercontent.com/13233076/78670875-c4271a00-7921-11ea-8291-f7fce9bebc13.png)

> the right one (2) expands the advanced settings.

that's correct

> I've tried to setup a custom path, but when reloading the page both checkboxes (1 and 2) get unchecked and if I check them again my setting for the path is missing. Only the checkbox for the path is still checked

Interesting, this sounds like a bug but I can't replicate it. Do you have some step by step I can reproduce to trigger the bug?

**Comment by pagdot** [comment]
Just replicated in on my local machine with:
Ok, just tested a little more. It seems to use the directory if the admin page doesn't get reloaded.
Only relative paths seem to work. Absolute paths always cause "error: not allowed".

When the dashboard gets loaded (doesn't matter if it is a new session/tab/browser or the same one) the setting gets lost again.

1. Run container with `docker run --rm -it -p 8334:8334 machines/filestash`
2. Set admin password
3. Click on "don't expose" (shouldn't matter tough. On my server I've set it to "handle it myself")
4. Open Dashboard, click on "OK" on data usage popup
5. remove all backends (should not matter)
6. add sftp backend
7. set hostname to valid target
8. try to connect in second tab -> works
9. Set path in advanced settings
10. Connect again in second tab: works dependent if the path exists and it is a relative path
11. Reload admin dashboard tab: right advanced checkbox is unchecked -> settings hidden
12. Connect again in second tab: works, but without custom path
13. Click on right checkbox to open advanced settings in admin dashboard -> path checkbox is checked, but path field is empty

I've tested it with both Firefox and Chromium and came to the same results.

I've also captured the network traffic in the firefox developer console. It seems like on page load, a config gets send using the api with the path set to `null`.

**Comment by pagdot** [comment]
Tested it again and it seems to be working now :)
