### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Ressort-Informatik** [mickael-kerjean/filestash#250]
Hello everybody
Does anyone have this problem too?
Once Filestash is installed, it works for 3-4 weeks.

After 3-4 weeks the settings are suddenly reset and when I go to the admin panel I can no longer log in.

This error message appears:
![image](https://user-images.githubusercontent.com/61539032/79449870-48ddfc00-7fe4-11ea-93fe-1003b525c64e.png)

I have deleted and re-set Filestash several times, but that doesn't help.

**Comment by mickael-kerjean** [comment]
Thank you for the report. I've never seen such error before. This seem to be your operating system saying Filestash it can't write in its own config file. Do you confirm you still have some hard drive space left?

**Comment by Ressort-Informatik** [comment]
Thank you for your response!

Yes, actually I should have enough memory.

I have now set up a new server and installed Filetash on it. I will get in touch in about 3-4 weeks whether it worked this time or not.
