### ISSUE TITLE
[bug] Crash on logout

### ISSUE THREAD

**Issue by pagdot** [mickael-kerjean/filestash#253]
Just managed to crash filestash. I'm not 100% sure how....

I was connected with an sftp server.

Steps which may (or may not) have triggered the crash:
1. Create shareable link to file
2. Delete shared file
3. Add file to folder again (from outside of filestash)
4. Reload like a mad man because the directory still doesn't show the file
5. Tried to open share link of the deleted file (does work, but download fails)
5. Login out (maybe it will show after a new login) -> crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdb5046]

goroutine 776 [running]:
github.com/mickael-kerjean/filestash/server/model/backend.Sftp.Close(0x0, 0x0, 0x27c9580, 0x1b1f640)
	/go/filestash/server/model/backend/sftp.go:253 +0x26
created by github.com/mickael-kerjean/filestash/server/ctrl.SessionLogout
	/go/filestash/server/ctrl/session.go:99 +0x303
```

**Comment by mickael-kerjean** [comment]
Thank you for the report. There seem to be a weird edge case where Filestash tries to close a non existing SFTP connection but I can't replicate the problem. Can you make a screenshare to show the defect?
