### ISSUE TITLE
[bug] : Download limit at almost 4gb.

### ISSUE THREAD

**Issue by xrhstosmour** [mickael-kerjean/filestash#256]
Hello, i have a problem whe downloading any file from the dashboard. When the file is bigger than 4 gb the download fails at 4gb and the file is corrupted. Is there any limit which can be changed ?

**Comment by pagdot** [comment]
Can you download big files from other sources/Where do you try to download the file to?

**Comment by xrhstosmour** [comment]
The sources are at a remote server in which i have installed filestash via docker image. I am trying to download the file to my personal computer. I have not any problem with my internet connection nor can i see anything at the filestash or machines logs, that is why i asked for any existed limit.

**Comment by pagdot** [comment]
~The one thing that comes to my mind with 4GB limit is the file size limit of the FAT32 partition scheme.~

Just tried downloading a 17Gb file and it finished ("successfully") at 4.6GB. There really seems to be a bug...

**Comment by xrhstosmour** [comment]
Yeap that is what is happening to me too.

**Comment by mickael-kerjean** [comment]
Thank you for the report! I see 2 possible source for the error:
- something going wrong with one of the backend. Which one are you using?
- the server closing the HTTP connection before the file has complete the transfer. How long did it take to upload the file?

**Comment by xrhstosmour** [comment]
I am using the stfp backend. The file was created from my server it is a backup so i did not upload it.

**Comment by pagdot** [comment]
I'm also using the SFTP backend. I've just ran it twice from the command line using curl:

```bash
$ time curl https://example.com/api/files/cat\?path\=%2Ffile.tar.gz\&share\=YvioaTn --output /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2543M    0 2543M    0     0  4485k      0 --:--:--  0:09:40 --:--:-- 6244k
curl  --output /dev/null  7,51s user 11,02s system 3% cpu 9:40,62 total

$ time curl https://example.com/api/files/cat\?path\=%2Ffile.tar.gz\&share\=YvioaTn --output /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1989M    0 1989M    0     0  3486k      0 --:--:--  0:09:44 --:--:--  8334
curl  --output /dev/null  5,57s user 8,55s system 2% cpu 9:44,28 total
```

**Comment by mickael-kerjean** [comment]
I tried to replicate the error without success by:

1. creating a file that's 8GB on my local machine and filled with random data
```
head -c 8G </dev/urandom > large.dat
cat large.dat | md5sum
# a6760fbceecbd846cc72b66288dbb408
```
2. create a shared link that point to my local machine using the SFTP from openssh server
3. download the file using curl:
```
time curl 'http://127.0.0.1:8334/api/files/cat?path=/large.dat&share=cbxIDWS' > curl.dat
# ...
#real	1m18.745s
#user	0m2.926s
#sys	0m17.166s
```
4. test the downloaded file has the same hash as earlier:
```
cat curl.dat | md5sum
# a6760fbceecbd846cc72b66288dbb408  -
```

**Comment by xrhstosmour** [comment]
I do not the problem is with curl though because i also can download the whole file via ssh. I face the problem only when trying to download via the sftp backend.

**Comment by pagdot** [comment]
> the server closing the HTTP connection before the file has complete the transfer. How long did it take to upload the file?

It sounds like a timout issue. @mickael-kerjean  maybe try to limit the download speed with `--limit-rate 200K` or something.

**Comment by mickael-kerjean** [comment]
Yep it does sound like a timeout. Somehow, the connection will close at some point. Maybe adding some more configuration to be able to change that setting would do the job

**Comment by xrhstosmour** [comment]
So what should i do ?

**Comment by pagdot** [comment]
If we just set a timeout we would have guaranteed issues at a specific file size.
We could scale the timeout with the filesize: Basetimeout + timeout * sizeOfFile

I don't know if filestash has access to the file transfer speed of a download. 
If so, it could use it in the equation or detect if the transfer-speed is 0 kB/s or something.

**Comment by mickael-kerjean** [comment]
@pagdot This sounds good in theory but good luck to get something to work like this in practise. Some server don't necessarily report sizeOfFile and bandwidth might be tricky to measure as well. An easier win would be in getting a configurable timeout that would sit in the admin console so that you can up the default if needed
@xrhstosmour a PR would be awesome

**Comment by pagdot** [comment]
@mickael-kerjean I just thought about asking why it doesn't report the filesize to the browser while downloading. Now I know the answer. Now I really understand the struggle

**Comment by xrhstosmour** [comment]
@mickael-kerjean I am not sure i am able to fix this issue but i ll give it a try.

**Comment by mickael-kerjean** [comment]
Before someone dig too much, I haven't been able to replicate the error to date but did discover from another report someone else reporting the same symptom (#262) but the root error was a proxy configuration problem. There's even someone who wanted to created a PR to enforce a limit at the reverse proxy level (https://github.com/mickael-kerjean/filestash-website/pull/14).

A way to test this is to export your instance on the internet and make a test with curl.

**Comment by xrhstosmour** [comment]
I will give them a try although my problem is only while downloading and nor uploading files.
