### ISSUE TITLE
HTTPS cert for filestash.app

### ISSUE THREAD

**Issue by wmantly** [mickael-kerjean/filestash#257]
The HTTPS cert on your website has expired and the server is configured to not allow insecure requests.

**Comment by mickael-kerjean** [comment]
Yep, my mistake, the website was out for about 30 minutes as I forgot to renew the SSL certificates. The issue is that I can't manage to find a way to renew wildcard certificate from a cronjob with certbot :disappointed: so it's a manual job that's done about every 2 to 3 months
