### ISSUE TITLE
Writing documentation for setting up filestash with nomad and issue with previews

### ISSUE THREAD

**Issue by acivitillo** [mickael-kerjean/filestash#259]
I am setting up filestash with nomad and writing down the docs for it: https://gist.github.com/acivitillo/10abee46d3068f14a8839e317f8fb3c3

I plan to contribute this docs when they are ready to filestash. I think filestash would benefit from this setup because users might need to spin up various services on their server and nomad is an easier way of doing it compared to Kubernetes.

At this point I managed to make everything work, including persisting filestash app state. I am having some issues with the previews, however. You can see in the image below what's happening.

I am not sure yet what this is but I think it is docker related, not nginx or nomad. It seems that `asset/icons` is not made available for some reason.

![image](https://user-images.githubusercontent.com/54931660/81784661-7c397b00-94fd-11ea-882e-d7e05cc34d87.png)

**Comment by acivitillo** [comment]
OK I was able to set this up, wrote down my steps into this PR: https://github.com/mickael-kerjean/filestash-website/pull/15

**Comment by mickael-kerjean** [comment]
Awesome work! Can you host this documentation either on medium, github, pastebin or on your blog and create a link from the documentation instead? There's a section of the doc that is dedicated to alternative installation methods provided by members of the community: https://www.filestash.app/docs/install-and-upgrade/#alternative-installation-methods

**Comment by acivitillo** [comment]
Thanks! It's done, I sent you a new PR.
