### ISSUE TITLE
[bug] S3 config deleted whenever I refresh admin/dashboard

### ISSUE THREAD

**Issue by dungdm93** [mickael-kerjean/filestash#261]
I use filestash as s3 browser for Ceph Object Storage, so the configuration something like this:
![S3 config](https://user-images.githubusercontent.com/6848311/82071180-f1749e00-96ff-11ea-9835-68b3037aec02.png)
Configs already save into `/app/data/state/config/config.json` and I also logged in to filestash.  
But whenever I refresh `admin/dashboard` page, configs are reset to default.  
So my suggestion/feature request is have `SAVE` button instead of auto-save.

**Comment by anvarknian** [comment]
same here

**Comment by mickael-kerjean** [comment]
I can't replicate what's you're seeing from my end. Can you make a screenshare or something that would show how to replicate it?

**Comment by dungdm93** [comment]
I just use [docker-compose](https://github.com/mickael-kerjean/filestash/blob/master/docker/docker-compose.yml) file from repo, and config as screenshot as you see above.

**Comment by mickael-kerjean** [comment]
That's my point, I can't replicate the behavior that you're observing and without being able to replicate it, it's hard to fix the underlying problem.

**Comment by dungdm93** [comment]
Here is screencasting: https://youtu.be/HoVD1wYvV44

**Comment by mickael-kerjean** [comment]
great, thank you very much! I'll try to replicate this to understand what's wrong
