### ISSUE TITLE
[bug] large file fails to upload

### ISSUE THREAD

**Issue by gnagnu** [mickael-kerjean/filestash#262]
Hi there!

I'm running a Filestash instance (via Docker) and it's working fine except when I try to upload large files (>100MB). I'm using S3 storage. 

After drag and dropping the file, I get the wheel for a few minutes, and then an error. 

When looking at the network requests in Chrome, I'm seeing that this request is failing (timeout?)
https://files.gowheeltheworld.com/api/files/cat?path=filename.mp4
with status:
(failed)net::ERR_CONNECTION_CLOSED

![Annotation 2020-05-15 145344](https://user-images.githubusercontent.com/2963018/82099312-e9930a80-96bb-11ea-9429-807993fcb3e9.jpg)

Thanks!

**Comment by gnagnu** [comment]
Sorry I was able to fix that.
I'm using a proxy and it was limiting the maximum file size

**Comment by jeeftor** [comment]
What proxy was you using?
