### ISSUE TITLE
[Feature Request] support for HEIC format

### ISSUE THREAD

**Issue by AlamoudiAM** [mickael-kerjean/filestash#264]
**Thank you Mickael for this awesome project.**

### Feature Request
Previewing a photo of HEIC extension.

### Possible Solution
conversion/transcoding using ImageMagick or ffmpeg.

**Comment by mickael-kerjean** [comment]
I don't have any of that stuff and don't personally need it either. 
If you're interested, that would make for a great PR though. This might be as easy as letting the current image resizing plugin know about HEIC by setting the relevant image mimetype in  [mime.json](https://github.com/mickael-kerjean/filestash/blob/master/config/mime.json) and tweak a bit around [here](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_light/index.go#L183)

**Comment by mickael-kerjean** [comment]
I've dug the topic of HEIC to see how that thing works and to put it lightly HEIC sounds like a massive piece of shit ([1](https://news.ycombinator.com/item?id=14489987), [2](https://github.com/libvips/libvips/issues/671#issuecomment-344247078))

My position today is to wait and see how others are doing it as there's no plan to change the current license of Filestash to accomodate support for HEIC images.

**Comment by maxexcloo** [comment]
Are there any pointers you could give for adding this (even via a hack?)

I need HEIC support to browse all my iOS created photos and this app has by far the fasted thumbnailing support!
