### ISSUE TITLE
[bug] AWS SFTP not working upload and file creation

### ISSUE THREAD

**Issue by attila4523** [mickael-kerjean/filestash#265]
Hello,
I connected the self hosted or managed filestash to the AWS SFTP server. 
It created the file list, but when I want to upload a file or touch a file, I get an error.

The API respose: `{"status":"error","message":"Operation not supported"}`.

And I see this error lines in the logs:
```
2020/05/19 18:21:58 INFO HTTP 501 GET   33.3ms /api/files/touch?path=%2Ftest
2020/05/19 18:58:48 INFO HTTP 403 POST   63.1ms /api/files/cat?path=%2F1234%2Findex.html
```

The interesting thing is that it works with a simple ssh server.
I can connect to the AWS SFTP server with the other apps or command line.

**Comment by mickael-kerjean** [comment]
Can you send me a testing account I can use to replicate this? I never heard about such problem before

**Comment by attila4523** [comment]
Hello,
I sent the credential your mail address that i saw in your profile.
Thanks for help.

**Comment by babdulkarim** [comment]
any updates on this?

**Comment by mickael-kerjean** [comment]
The SFTP implementation made by Amazon is custom made and has some corners cut with the specs. That's fixable but I won't be working this out on my free time.

If there's a need for this, you can either:
1. create a PR

2. sponsor the work. If you want to go this way, you can contact me at mickael@kerjean.me
