### ISSUE TITLE
[Feature Request] Upload status + drag-n-drop area

### ISSUE THREAD

**Issue by brockfansler** [mickael-kerjean/filestash#266]
Could the entire page be a drag-n-drop zone for file uploads?
Is there a way to have an upload status + cancel as well?

I'm deploying a Filestash to some non-technical users and finding a great cost-saving solve with a QNAP RAID + Dynamic DNS setup. Since they are most familiar with GDrive + Dropbox their habits with web based file browsers have become semi-ingrained.

**Comment by mickael-kerjean** [comment]
Yes this can all be done. The reason this isn't here already is it's not trivial to implement and would take quite some time to work right. Ultimately, there's 2 options:

1. someone create a PR

2. someone pay for the feature

**Comment by mickael-kerjean** [comment]
FYI, an awesome contributor did work on something along those lines: https://github.com/mickael-kerjean/filestash/pull/267
That should land into master pretty soon

**Comment by mickael-kerjean** [comment]
Merged, the uploader is now much much better than before thanks to @sazarkin
