### ISSUE TITLE
[bug] Logging in results in "Not Allowed" error

### ISSUE THREAD

**Issue by babdulkarim** [mickael-kerjean/filestash#268]
* Description
When I log in to a Git server on my self hosted filestash application, it results in a "Not Allowed" error. Looking at the docker logs, it says:

2020/05/22 23:18:18 ERROR Invalid access from host:
2020/05/22 23:18:18 INFO HTTP 403 POST    0.2ms /api/session

* Step by step instructions to reproduce the bug
Go to [my website](https://sadboyz.org/login) and try to login to a Git server of yours.

* Observed behavior
403 error when logging in
* Expected behavior
Successfully login to Git server.

**Comment by mickael-kerjean** [comment]
That's interesting. What does the log says?

**Comment by babdulkarim** [comment]
the log says:

2020/05/22 23:18:18 ERROR Invalid access from host:
2020/05/22 23:18:18 INFO HTTP 403 POST 0.2ms /api/session

If you go to the [my site,](https://sadboyz.org/login) then you can reproduce the bug.

**Comment by mickael-kerjean** [comment]
That's covered in the [install guide](https://www.filestash.app/docs/install-and-upgrade/#preparing-your-instance) where you need to go to the admin console and set your host value in the configure screen to `sadboyz.org`

**Comment by babdulkarim** [comment]
I already did that, so that's not the problem.

**Comment by mickael-kerjean** [comment]
> 2020/05/22 23:18:18 ERROR Invalid access from host:

That's all [here](https://github.com/mickael-kerjean/filestash/blob/0167930d7ce1d92591ee82c9a89eae762d85b3ac/server/middleware/http.go#L88-L91), again sometihng isn't right with your host value in the admin console. Can you send a screenshot of what you have from the configure screen in the admin console?

**Comment by babdulkarim** [comment]
![screenshot](https://user-images.githubusercontent.com/22579878/82830633-4e045580-9e84-11ea-931d-17f9ff870c52.PNG)

Here you go! By the way, I set up the certificate for the website to be valid as non www if that matters.

**Comment by babdulkarim** [comment]
I just fixed it. My host in my nginx conf was www.sadboyz.org not sadboyz.org
