### ISSUE TITLE
[bug] tls received record with version 3030

### ISSUE THREAD

**Issue by acivitillo** [mickael-kerjean/filestash#269]
I get the following message when I click on "New File". Is this possible incorrect setup of SSL on my end? Not sure what it is.

Also, any way to disable such notifications to non admin users?

![image](https://user-images.githubusercontent.com/54931660/82786666-51d4af80-9e65-11ea-9117-13006d55e955.png)

**Comment by mickael-kerjean** [comment]
I've never encountered such an error. What does the log says?
