### ISSUE TITLE
[Feature Request] org-roam

### ISSUE THREAD

**Issue by babdulkarim** [mickael-kerjean/filestash#271]
First of all, thank you for building filestash and supporting org-mode, including the built-in emacs editor. Aside from fleshing out more org-mode features on the web interface, have you thought about integrating [org-roam](https://github.com/org-roam/org-roam) on top of org-mode?

**Comment by mickael-kerjean** [comment]
I didn't know org-roam before your message, looks quite interesting! 

At this stage, I'm quite busy working on some other features. The most exciting one in the org-mode field is a complete revamp of the editor to make it more approachable as a solution to create entire wikis:

![screenshot_20200612_084224](https://user-images.githubusercontent.com/13233076/84446367-aad77c80-ac88-11ea-9296-7485e36b8179.png)
