### ISSUE TITLE
[Feature Request] Live Photos

### ISSUE THREAD

**Issue by andyjhall** [mickael-kerjean/filestash#273]
Hi guys,

Is there any chance of adding support for Live Photos? There’s an awesome project which already makes these work in the browser:

https://github.com/DavidAnson/live-photo-web

Apple also looks to have some sort of implementation:

https://developer.apple.com/live-photos/

**Comment by mickael-kerjean** [comment]
Hey,
I'm not an iphone user. Can you work on a PR?

**Comment by andyjhall** [comment]
Looks like it would require a modification to the way the file list is rendered, basically if a folder has a JPG and a MOV file have the same name then only the JPG should be shown (and given an extra tag so that onclick plays the MOV file). 

Ill take a look through the source now and see if I can figure out where abouts this would go
