### ISSUE TITLE
[Feature Request] Allow LDAP self-signed certificates

### ISSUE THREAD

**Issue by NoxInmortus** [mickael-kerjean/filestash#275]
Hello,

When trying to connect to a LDAP in TLS when the ldap server use a self-signed certificate, we can see the following error :

```
LDAP result code 200 "Network Error": x509: certificate signed by unknown authority
```

An option to be able to allow self-signed certificates would be very appreciated.

**Comment by mickael-kerjean** [comment]
Hey, such a feature sounds good to me. Can you try to work it out and create a PR?

**Comment by NoxInmortus** [comment]
Hello @mickael-kerjean, thanks for your answer.

Sadly i'm not a developer and wont be able to do that myself.

Regards
