### ISSUE TITLE
[bug] Filestash ignores short SSH private keys

### ISSUE THREAD

**Issue by edgar-vincent** [mickael-kerjean/filestash#279]
1) **Description of the bug**:
- For SFTP backends, Filestash considers that the content of the "Password" field is a private key if it is over 1000 characters in length (see [this line](https://github.com/mickael-kerjean/filestash/blob/f30787785c1b38577f75a2d48dbe3f44f44a4d1f/server/model/backend/sftp.go#L58)). However, some keys (like ed25519 keys) can be shorter. If one uses such a key, SSH authentication fails.

2) **Steps to reproduce**
-  Generate an ed25519 key, check that its length is under 1000 characters with `wc -c id_ed25519`
and add it to ~/.authorized_keys
- Configure the SFTP backend with a private key by pasting it in the "Password" field
- Try to connect to the host

3) **Observed behaviour**
- The connection fails with an "invalid account" error. 

4) **Expected behaviour**
- It should connect successfully.

5) **Suggestion to fix**
- Remove the "passphrase" field (which, at the moment, is a text field, which doesn't make much sense anyway)
- Add a "private key" field (which would make it easier for users to understand its purpose anyway) of type "long_password".
- Use key authentication if the "private key" field is not empty, and use the content of the "password" field as the passphrase

By the way, is there logging of any kind for this backend? No error appeared after my unsuccessful attempts to connect.

Thanks a lot for your work!

**Comment by mickael-kerjean** [comment]
The above commit should improve how private key are detected in the password field without making the kind of assumptions we had before

**Comment by edgar-vincent** [comment]
Thanks for such a quick fix.

Out of curiosity, wouldn't it be possible to to something like: 

```
signer, err := ssh.ParsePrivateKey(key_bytes)
	if err != nil {
		// do stuff
	}
        else {
              // error
        }
```
instead of using regular expressions? Or would that be unsafe?

Thanks again!

**Comment by mickael-kerjean** [comment]
It's a bit more complicated:
1. the ParsePrivateKey is just one of the function available to parse a private key, there's more to it with ParsePrivateKeyWithPassphrase for example where each function support different set of ciphers and a lot of weird edge case
2. some errors are legit you'd have to detect which error is an actual error from which one is there because the key isn't a private key, that sounds like a maitenance nightmare to me

**Comment by mickael-kerjean** [comment]
It looks like there's no action needed on this ticket. Feel free to comment if we need to reopen
