### ISSUE TITLE
[Feature Request] Hardware Accelerated Video decoding and Encoding

### ISSUE THREAD

**Issue by fallenczar** [mickael-kerjean/filestash#280]
Hi,
any chance you could enable hw accelerated video decoding and encoding in filestash. since you are using ffmpeg, this should be trivial.
docker container can use the GPU by adding host rendering device  /dev/dri to it.

**Comment by mickael-kerjean** [comment]
Hi, 
I would have assumed harware acceleration is used when it's available but I'm not a domain expert when it comes to video encoding / decoding. Can you make a PR for this?

**Comment by fallenczar** [comment]
file stash is definitely not using hw acceleration for trans-coding.
hw acceleration (for intel devices (VAAPI)) can be enabled by following this guide :
[https://trac.ffmpeg.org/wiki/Hardware/VAAPI]
for further examples on how to configure your env file please see:
[(https://github.com/linuxserver/docker-jellyfin)]

**Comment by mickael-kerjean** [comment]
That's not how it works. If you need it, create a PR for it or donate the necessary hardware to the project so we have some basis on which to test this out when I have some free time.

Blindly follow a guide and call it a day without being able to see it in action isn't an acceptable solution.
