### ISSUE TITLE
[Feature Request] Additional options for "Editor" shares (Deny file deletion)

### ISSUE THREAD

**Issue by coxtor** [mickael-kerjean/filestash#282]
Hi, I love the sharing function, it would be great if it would be possible to implement following additional feature for the editor share, e.g. as an "advanced checkbox".
"Deny file deletion", giving an editor the possibility to only create directories, upload files and download them, however deny the deletion of existing files.

**Comment by mickael-kerjean** [comment]
Hey,
I don't really see the point of such feature but if you need it and can work on a PR, we will merge it
