### ISSUE TITLE
[Feature Request] upload button

### ISSUE THREAD

**Issue by babdulkarim** [mickael-kerjean/filestash#286]
I don't have a GUI file manager so it would be handy to have an upload button that prompts for a file other than having an area to upload files.

I see a button on mobile but not desktop.

**Comment by mickael-kerjean** [comment]
Hey, there's an option in the admin console to have that upload button available in desktop as well as mobile and not just mobile only as is the default.

**Comment by mahdiG** [comment]
> Hey, there's an option in the admin console to have that upload button available in desktop as well as mobile and not just mobile only as is the default.

Hi. Why not enable the upload button by default? I remember at first I was confused about how to upload and I had to google to learn there's a drag & drop feature
