### ISSUE TITLE
[bug] $URL_DESTINATION is not valid: '' when using example docker-compose.yml

### ISSUE THREAD

**Issue by bhammack** [mickael-kerjean/filestash#287]
# description of the bug
Using the self-hosted installation guide found at https://www.filestash.app/docs/install-and-upgrade/, I run docker-compose on the example yml file which should create the starter environment. However, the container immediately bombs out and enters a restart-loop, citing the following error message in the logs:

`$URL_DESTINATION is not valid: ''`

If I set this env variable to something in the docker-compose the value does show in the logs. It seems that `https://<my-subdomain-here>` is considered a valid url, but that didn't yield any further solutions.

# step by step instructions to reproduce the bug
Follow the installation instructions provided on the website: https://www.filestash.app/docs/install-and-upgrade/
```
mkdir filestash && cd filestash
curl -O https://downloads.filestash.app/latest/docker-compose.yml
docker-compose up -d
```

# observed behavior
The container immediately fails, citing the log message above.

# expected behavior
Standard operating procedure

**Comment by bhammack** [comment]
I searched the repository for usage of URL_DESTINATION (which I suspect is related to the internal proxy), but couldn't find a mention of it.

**Comment by mickael-kerjean** [comment]
I recently made some changes to some reverse proxy settings which contain this URL_DESTINATION params. This might have been some bad timing where you did something in the very same time I was working on the website and updating some stuff (I don't really take the time for blue green deployment or anything like that as this is my side project at the moment)

Anyhow, the error should be gone now. Can you confirm?

**Comment by bhammack** [comment]
Yep sounds like it - pulled the latest docker image and it's working now. Thanks for the quick response!
