### ISSUE TITLE
[bug] Oops! Unknown Path

### ISSUE THREAD

**Issue by sebastianfelipe** [mickael-kerjean/filestash#288]
Hi!

I connected a Amazon S3 like provider (Wasabi). I realised, that every folder is loaded, but, when I click on one folder, it has a 404 error. That is very strange, because, if I create a folder directly on Wasabi or through Filestash web app, then I can get access into that folder. Is very strange and I don't understand why.

Every content I'm uploading to Wasabi right now, is using "pkgcloud" nodejs component.

I'm not sure that is a thing about permissions, because every file and every folder has set the same permissions, so I cannot understand why this happened. I just cannot get in. Another thing, is that I try access the same folder, but through 2 different Filestash apps, from 2 different hosts, so the problem is basically, that I cannot get into folders that are not created in Filestash or not created on Wasabi.

Thanks,
Sebastián.

P.S: I used the docker version with the docker-compose file.

After made some research, I realised that is possible to get access to a file putting a full path, but it cannot be possible to access, through the intermediary paths, that is the main problem. You cannot know how to get access to the final image if you can't enter to the intermediary buckets.

**Comment by mickael-kerjean** [comment]
Wasabi isn't in the list of supported backends.

I did contact them about 2 years ago hoping I could get some sort of testing account from which the integration could be tested but they refused to do any giveaway. So I've lost interest as I'm not willing to give my credit card information to 
 to every single cloud storage provider and pay each monthly fees.

**Comment by sebastianfelipe** [comment]
I understand. Well, I have the logs so I contacted Wasabi to know what happened. Using the aws-cli everything is fetched fine, so I'm not sure if it is something of Wasabi or something related with AWS S3 API in general. I'm gonna try with the AWS S3 and if it happens the same, probably there would be a bug.

A question, do you have some WIKI to get the project run without docker? I know that works with GO, but how can I make it run locally and get some debug on it on my own?

I'm interested in know about the /api/files/ls endpoint you have implemented. Know what request is sent to the S3 API.

Thanks!
Sebastián.

**Comment by mickael-kerjean** [comment]
> so I'm not sure if it is something of Wasabi or something related with AWS S3 API in general.

I have no idea. In my experience working out with a few S3 compatible sotrage, they all in a subtle way behave slightly differently from one another.

> I'm gonna try with the AWS S3 and if it happens the same, probably there would be a bug.

If you find any issue with AWS S3, please report it :)

> A question, do you have some WIKI to get the project run without docker?

No, distribution on Linux isn't simple, some people like flatpack, some deb, some swear by yum, ..... 
With every release come it sets of problem and using docker is my way or shielding myself against all those potential problems I don't want to deal with on my free time.

If you really need to get things running outside docker, there's some [enterprise plan](https://www.filestash.app/pricing/) where we can create and support things with all sort of customisation.

> I know that works with GO

In theory in a perfect world, in practise it's not that simple. This project has some C dependencies for some libraries that would be way to slow in pure Golang, things like image resizing and transcoding with libvips and libraw.

> but how can I make it run locally and get some debug on it on my own?

[This](https://github.com/mickael-kerjean/filestash/blob/master/CONTRIBUTING.md#building-from-source) should be a good starting point

> I'm interested in know about the /api/files/ls endpoint you have implemented

Internal API are subject to change but if you're willing to dig a little, here are some hints:
- the [list of middleware](https://github.com/mickael-kerjean/filestash/blob/master/server/main.go#L53) the request go through
- the [entrypoint](https://github.com/mickael-kerjean/filestash/blob/master/server/ctrl/files.go#L35) and the most [important call](https://github.com/mickael-kerjean/filestash/blob/master/server/ctrl/files.go#L50)
- [a LS on S3](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_backend_s3/index.go#L120-L188), the [most important call](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_backend_s3/index.go#L158-L162)
-

**Comment by sebastianfelipe** [comment]
After all these days, I finally could test it out. On AWS S3 it fails too, so the problem is in Filestash internal requests.

To replicate this case, you just to upload something with forcing its path (is like a mkdir -p). I'm using pkgcloud to do that on nodejs. Well, basically, I can navigate very well using the AWS S3 as in Wasabi console. Also can access to everything using the aws-cli s3, but using Filestash, there's the problem I'm commenting you, so it must be some kind of error around there.

Is there an account, S3 account yours or something with a provisory key to upload a test content for you to try to navigate and see what happened?

Thanks!
Sebastián.

**Comment by hanswieheiri** [comment]
I am using AWS S3 and docker build `2138bf0` is the most recent version that still works.

**Comment by mickael-kerjean** [comment]
> Is there an account, AWS S3 account, yours, with a provisory key to upload a test content 

You can use this testing minio instance: 
https://demo.filestash.app/login?type=s3&access_key_id=Q3AM3UQ867SPQQA43P2F&secret_access_key=zuf%2BtfteSlswRu7BJ86wekitnifILbZam1KYY3TG&region=us-east-2&encryption_key=&endpoint=https%3A%2F%2Fplay.minio.io%3A9000%2F

If you can replicate what's going on in there, we might be able to get to the end of it

**Comment by sebastianfelipe** [comment]
That will work. I assure you that. Because the problem is with S3 or S3 like. With Minio is different. Before right my post I tried with Minio without problem. MinIO has another kind of file system rather than the real S3 or Wasabi or another S3 like. MinIO will work, S3 don't. I thought I explained this to you before.

**Comment by mickael-kerjean** [comment]
> MinIO has another kind of file system rather than the real S3 or Wasabi or another S3 like
> so the problem is in Filestash internal requests

S3 is an SDK thats is wrapping some REST APIs, no more no less. What's happening is that vendors are implementing those APIs (Minio, Wasabi, Digital Ocean space, openio, ...) and claim they are S3 compatible but let's not forget S3 isn't a standard in that there's no RFC, instead the standard is the SDK and Filestash [uses that SDK](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_backend_s3/index.go#L4-L9).

I'd welcome a PR that solve a potential problem but as of right now I have neither a PR that address this nor a way to even reproduce what you're describing.

**Comment by sebastianfelipe** [comment]
That's why I asked you to provide an Amazon S3 or Wasabi S3. I could post the same to MinIO and Amazon S3 and compares.

**Comment by mickael-kerjean** [comment]
Not gonna happen

**Comment by sebastianfelipe** [comment]
I just tried to help to debug what's going on in a fast and direct way. It seems like you hate your own project. Best support ever.

**Comment by mickael-kerjean** [comment]
Wow. Let me be clear with you then:

1. AWS got my credit card information. With the pricing of S3, giving away some accounts could cost me thousands of dollars like [this guy](https://news.ycombinator.com/item?id=23956671). Why would I take such a risk? I did suggest you few ways to work it out but using my own S3 account is a no no.

2. "Best support ever": Have you considered that the messages I've sent you took a lot of of my time already not to mention I don't earn a dime from you. Such comment is unhelpful, disrespectful and not welcome.
