### ISSUE TITLE
[bug] File size is not changed when lines are deleted with the integrated editor

### ISSUE THREAD

**Issue by kafeinnet** [mickael-kerjean/filestash#289]
Hi,

### description of the bug:

I just installed filestash, it works perfectly except for one annoying bug with the text file editor. Files are not truncated when the size is reduced.

### step by step instructions to reproduce the bug:

1. create a file of 10 lines or so of random text (the number is not important)
1. delete some lines
1. save the file

### observed behavior:

The file size is not reduced, it still contains the deleted lines and the following alert shows up.

![image](https://user-images.githubusercontent.com/4932189/85788263-fb40e680-b72c-11ea-8a0f-8b80b7a5588f.png)

### expected behavior:

The file size should be changed.

### addidional information

I installed the docker version. This bug is present with at least the emacs-like editor and the vim-like editor.

\fab

**Comment by mickael-kerjean** [comment]
I can't replicate what you're seeing. Can you create a screenshare while using the demo instance: https://demo.filestash.app ?

I've tried to reproduce using this backend: https://demo.filestash.app/login?type=s3&access_key_id=Q3AM3UQ867SPQQA43P2F&secret_access_key=zuf%2BtfteSlswRu7BJ86wekitnifILbZam1KYY3TG&region=us-east-2&encryption_key=&endpoint=https%3A%2F%2Fplay.minio.io%3A9000%2F

**Comment by kafeinnet** [comment]
I can't reproduce the bug on the demo instance and I can't share my screen because of security reasons with my company.

But here is a screencast of the bug I just made.

![filesizebug2](https://user-images.githubusercontent.com/4932189/85827518-bc3f7f00-b786-11ea-9423-2355c03398b0.gif)

I pulled the image (machines/filestash:latest) before recording this just to be sure.

Maybe that's relevant but the data are stored on a GlusterFS volume in a swarm docker cluster.

**Comment by mickael-kerjean** [comment]
> But here is a screencast of the bug I just made.

Awesome thanks! 
(Just curious, which software did you use for making a GIF like this? This is pretty cool)

> Maybe that's relevant but the data are stored on a GlusterFS volume in a swarm docker cluster.

Yes, it's very likely the error is somehow given by the backend. I've never use GlusterFS myself at this point. Can you send a testing account from which I could replicate what the error you're having?

**Comment by kafeinnet** [comment]
> Awesome thanks!
> (Just curious, which software did you use for making a GIF like this? This is pretty cool)

I used ScreenToGif https://www.screentogif.com/. That's a pretty neat (and opensource) desktop recording software.

> Yes, it's very likely the error is somehow given by the backend. I've never use GlusterFS myself at this point. Can you send a testing account from which I could replicate what the error you're having?

Yep, I can do that. I'll setup it this monday.
