### ISSUE TITLE
[bug]   $URL_DESTINATION is not valid: ''

### ISSUE THREAD

**Issue by NoxInmortus** [mickael-kerjean/filestash#290]
Hello, my filestash container has been updated 8 days ago, and since the containers fails with
```
 $URL_DESTINATION is not valid: ''
```
error

any hints ?

thanks

**Comment by mickael-kerjean** [comment]
This sounds very much the same as https://github.com/mickael-kerjean/filestash/issues/287

**Comment by NoxInmortus** [comment]
Indeed, pulled the latest image, works good
