### ISSUE TITLE
[Feature Request] copy entire folder in the same level

### ISSUE THREAD

**Issue by changchichung** [mickael-kerjean/filestash#291]
awesome project !

I need to provide this file manager for users to create some documents based on a "template folder" which include some template files (markdown or yaml )

something like 
```
root
 - template_folder
 ```
and I want users to copy the template_folder and rename to what they want and saved under root.

but I see no such funtion like "copy" in filestash.

is it possible to add copy funtion to filestash ?

**Comment by mickael-kerjean** [comment]
That's correct, there's no copy feature at this stage. Nothing impossible though, but that would require quite a bit of time and considering I have no direct need for this, there's 2 options:

1. work it out on your side and create a PR when you're done

2. sponsor the development of that feature
