### ISSUE TITLE
[bug] 重启docker之后admin密码失效

### ISSUE THREAD

**Issue by Shen-Yu** [mickael-kerjean/filestash#293]
- description of the bug
重启docker之后admin密码失效

- step by step instructions to reproduce the bug
win10下面，docker重启后登陆/admin界面

- observed behavior
密码失效，500错误，提示invalid key

- expected behavior
能成功登陆admin

**Comment by Shen-Yu** [comment]
另外，我怎么才能修改密码？

**Comment by mickael-kerjean** [comment]
I can't replicate this. Can you provide a screenshare? The password is stored encrypted in the config.json file. What does this file contain when you have the error?

**Comment by Shen-Yu** [comment]
i can't find config.json file, it's only a  docker-compose.yml file in my directory. and how can i change password? thanks !
![image](https://user-images.githubusercontent.com/13065982/88356337-06be1680-cd9a-11ea-847e-9bb00d197271.png)
![image](https://user-images.githubusercontent.com/13065982/88356350-16d5f600-cd9a-11ea-8d60-a3a0c04bd0ff.png)

**Comment by mickael-kerjean** [comment]
> i can't find config.json file, it's only a docker-compose.yml

I don't have my laptop around right now but the config.json is located within the container created by docker-compose. To access it you need to either do a `docker cp <container> ...` or `docker exec -ti filestash bash` and find that file under `/app/data/state/config/`

> how can i change password?

The only way to do this today is to manually update the config.json that's located within the container under `/app/data/state/config/config.json` and:

1. remove the admin password

2. restart the container where you will be redirected to the setup

**Comment by Shen-Yu** [comment]
thanks ! i'v found config.json file, but my password seem absolutely right, it's still 500 error after i call /admin/api/session, there are sceenshots:

![image](https://user-images.githubusercontent.com/13065982/88357825-34598e80-cd9f-11ea-9f53-bf655e699dc1.png)
![image](https://user-images.githubusercontent.com/13065982/88357833-3e7b8d00-cd9f-11ea-8c48-49b43a407a0d.png)

**Comment by Shen-Yu** [comment]
after restart docker, i'm now fixed, but there is another error below:
![image](https://user-images.githubusercontent.com/13065982/88448642-861f1900-ce72-11ea-85a7-727a68fa61c6.png)

**Comment by mickael-kerjean** [comment]
Something weird is going on and I can't replicate it. 
Is it possible that Backblaze is blocked in your contry and you're trying to use Backblaze from there?
Can you try to:
```
curl https://api.backblazeb2.com/b2api/v2/b2_authorize_account -u "APPLICATION_KEY_ID:APPLICATION_KEY"
```

**Comment by Shen-Yu** [comment]
well, i think it's probably my docker's problem, thanks, i'v wrote a web version: [B2Viewer](https://github.com/Shen-Yu/b2-viewer)
