### ISSUE TITLE
[Feature Request] 希望作者能做一个web版

### ISSUE THREAD

**Issue by Shen-Yu** [mickael-kerjean/filestash#294]
希望能出一个web版，不用任何依赖，因为docker在中国速度很慢，本地搭建需要下载不少东西，而且还有各种登陆不进去的问题。另外，希望对backblaze的支持更加完善，谢谢。

**Comment by mickael-kerjean** [comment]
You shouldn't have problem to create a version without docker. Docker is mostly used as a convenience layer to facilitate distribution across every possible linux distribution.

As for Backblaze, I'm not sure what you are referring to but if you see some issues, a PR would be awesome
