### ISSUE TITLE
[Feature Request] clean cache  button in admin console

### ISSUE THREAD

**Issue by changchichung** [mickael-kerjean/filestash#295]
I run filestash in docker and configure to clone a github repo.
when something in filestash changed , filestash will automatic go the push job , which is great.
but if there are something updated in the repo , users can not see the change immediatelly
I think that might be something about filestash cache.

I see there is no such "clean cache" thing in admin console , so I have to do a docker restart to show the changes.

I think it's good to add a "clean cache" option in admin console to prevent such situation .

**Comment by hsum** [comment]
+1 This would be very useful.  Are there any current workarounds aside from restarting the docker container?

**Comment by mickael-kerjean** [comment]
No workaround bug a PR would be awesome
