### ISSUE TITLE
[Feature Request] Google TeamDrive and/or MyDrive-Shortcut Support

### ISSUE THREAD

**Issue by leram84** [mickael-kerjean/filestash#297]
Since teamdrives offer much more flexibility and are rapidly becoming the default storage method for large amounts of data, it would be very beneficial to support them with the google drive integration. I tried creating a shortcut of a teamdrive inside MyDrive to see if filestash might be able to read from there, and while the root TD folder can be seen in MyDrive (in filestash), selecting it results in:

```
Oops!
Googleapi: got HTTP response code 400 with body: {"error":{"errors":[{"domain":"global","reason":"badRequest","message":"The requested conversion is not supported.","locationType":"parameter","location":"convertTo"}],"code":400,"message":"The requested conversion is not supported."}}
```

**Comment by mickael-kerjean** [comment]
It sounds good to me. I don't use google drive anymore, can you work it out via a PR?
