### ISSUE TITLE
Windows path bug

### ISSUE THREAD

**Issue by johanthegreat** [mickael-kerjean/filestash#299]
Using filestash on windows seem to differ somewhat from other platforms. On the way to getting Filestash to run I found some issues one of which is that localhost:8334 did no list any files, instead "There is nothing here".

Windows uses backslash _(with Paths)_ and the GO function "Filepath.Join" is platform dependant, there fore it produces different results depending on platform. On Windows the "basePath" became "\ /" which obvoiusly generates an error. 

This is solved by adding Go "filepath.ToSlash()", as the following:

```
func PathBuilder(ctx App, path string) (string, error) {
	if path == "" {
		return "", NewError("No path available", 400)
	}
	sessionPath := ctx.Session["path"]
	basePath := filepath.ToSlash(filepath.Join(sessionPath, path))
	if path[len(path)-1:] == "/" && basePath != "/" {
		basePath += "/"
	}
	if strings.HasPrefix(basePath, ctx.Session["path"]) == false {
		return "", NewError("There's nothing here", 403)
	}
	return basePath, nil
}
```

**Comment by mickael-kerjean** [comment]
You are correct, thank you!
Can you make a PR with this exact change or should I?

**Comment by mickael-kerjean** [comment]
Haven't got any news so I pushed your fix, thank you!
