### ISSUE TITLE
[bug] Error uploading a folder

### ISSUE THREAD

**Issue by santy-mvzg** [mickael-kerjean/filestash#300]
The error occurs when you drag a folder, to upload it, by ftp. if they are files they are uploaded perfectly.

Attached image of the error.

Thank you very much.

![Sin título](https://user-images.githubusercontent.com/21013835/89717209-864b0880-d98a-11ea-9ec1-308cc3f38e44.png)

**Comment by mickael-kerjean** [comment]
I can't replicate this error with an empty directory. Can you replicate the steps you need to go through using the demo website: https://demo.filestash.app/

**Comment by santy-mvzg** [comment]
Thanks for answering, there I am attaching a video of the error. the error occurs when you upload a folder with files inside, not with an empty folder.
https://youtu.be/qbhwxOLTcF4

**Comment by mickael-kerjean** [comment]
Can you share a copy of the folder that generates this error?

**Comment by santy-mvzg** [comment]
any folder that has a file in it generates this error. It is not the folder that alone, the one that generates it.

**Comment by santy-mvzg** [comment]
hello good day mickael, the problem is not solved yet .. keep throwing the same error when uploading a folder with files inside.

Regards.

**Comment by mickael-kerjean** [comment]
I haven't run the CI/CD process yet, the commit is there, it just needs a build and some of my servers have been playing up recently (= the build hasn't run there yet)

**Comment by santy-mvzg** [comment]
hello good morning, is it possible to integrate a menu with the right click to the page?
I integrated one but it is difficult for me to capture the file where the mause is.

I am attaching a photo to give you an idea of ​​what I'm talking about and the code so you can see.
File: filespage.js

import ContextMenu from 'devextreme-react / context-menu';
import notify1 from 'devextreme / ui / notify';

import {contextMenuItems as items} from './data.js';
// ------------------------------
 return (
            <div className = "component_page_filespage">
              <BreadCrumb className = "breadcrumb" path = {this.state.path} currentSelection = {this.state.selected} />
              <SelectableGroup onSelection = {this.handleMultiSelect.bind (this)} tolerance = {2} onNonItemClick = {this.handleMultiSelect.bind (this, [])} preventDefault = {true} enabled = {this.state.is_search === false} className = "selectablegroup">

              <React.Fragment>
                <div className = "page_container" id = "root">
<ContextMenu
dataSource = {items}
width = {200}
target = "# root"
onItemClick = {itemClick} />

             <div ref = "$ scroll" className = "scroll-y">
              <InfiniteScroll pageStart = {0} loader = {$ moreLoading} hasMore = {this.state.files.length> 70}
                                    initialLoad = {false} useWindow = {false} loadMore = {this.loadMore.bind (this)} threshold = {100}>
                      <NgShow className = "container" cond = {!! this.state.is_search || ! this.state.loading}>
                        <NgIf cond = {this.state.path === "/"}>
                          <FrequentlyAccess files = {this.state.frequents} />
                        </NgIf>
                        <Submenu path = {this.state.path} sort = {this.state.sort} view = {this.state.view} onSearch = {this.onSearch.bind (this)} onViewUpdate = {(value) => this .onView (value)} onSortUpdate = {(value) => this.onSort (value)} accessRight = {this.state.metadata || {}} selected = {this.state.selected}> </Submenu>
                        <NgIf cond = {! This.state.loading}>
                          <FileSystem path = {this.state.path} sort = {this.state.sort} view = {this.state.view} selected = {this.state.selected}
                                      files = {this.state.files.slice (0, this.state.page_number * LOAD_PER_SCROLL)} isSearch = {this.state.is_search}
                                      metadata = {this.state.metadata || {}} onSort = {this.onSort.bind (this)} onView = {this.onView.bind (this)} />
                        </NgIf>
                      </NgShow>
                    </InfiniteScroll>
                    <NgIf cond = {this.state.loading === true}>
                      <Loader />
                    </NgIf>
                    <MobileFileUpload path = {this.state.path} />
                  </div>
                </div> </React.Fragment>
// ------------------------------------------------ ---------

the menu works correctly, what I am not being able to do is distinguish between a file or folder, and hence give the options.

If it is necessary to pay so that the code can be implemented, let me know.


thanks.
________________________________
De: Mickael <notifications@github.com>
Enviado: sábado, 26 de septiembre de 2020 23:10
Para: mickael-kerjean/filestash <filestash@noreply.github.com>
Cc: santiago martinez <petrini_santi@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [mickael-kerjean/filestash] [bug] Error uploading a folder (#300)


I haven't run the CI/CD process yet, the commit is there, it just needs a build and some of my servers have been playing up recently (= the build hasn't run there yet)

**Comment by santy-mvzg** [comment]
hello good morning, is it possible to integrate a menu with the right click to the page?
I integrated one but it is difficult for me to capture the file where the mause is.

I am attaching a photo to give you an idea of ​​what I'm talking about and the code so you can see.
File: filespage.js

import ContextMenu from 'devextreme-react / context-menu';
import notify1 from 'devextreme / ui / notify';

import {contextMenuItems as items} from './data.js';
// ------------------------------
 return (
            <div className = "component_page_filespage">
              <BreadCrumb className = "breadcrumb" path = {this.state.path} currentSelection = {this.state.selected} />
              <SelectableGroup onSelection = {this.handleMultiSelect.bind (this)} tolerance = {2} onNonItemClick = {this.handleMultiSelect.bind (this, [])} preventDefault = {true} enabled = {this.state.is_search === false} className = "selectablegroup">

              <React.Fragment>
                <div className = "page_container" id = "root">
<ContextMenu
dataSource = {items}
width = {200}
target = "# root"
onItemClick = {itemClick} />

             <div ref = "$ scroll" className = "scroll-y">
              <InfiniteScroll pageStart = {0} loader = {$ moreLoading} hasMore = {this.state.files.length> 70}
                                    initialLoad = {false} useWindow = {false} loadMore = {this.loadMore.bind (this)} threshold = {100}>
                      <NgShow className = "container" cond = {!! this.state.is_search || ! this.state.loading}>
                        <NgIf cond = {this.state.path === "/"}>
                          <FrequentlyAccess files = {this.state.frequents} />
                        </NgIf>
                        <Submenu path = {this.state.path} sort = {this.state.sort} view = {this.state.view} onSearch = {this.onSearch.bind (this)} onViewUpdate = {(value) => this .onView (value)} onSortUpdate = {(value) => this.onSort (value)} accessRight = {this.state.metadata || {}} selected = {this.state.selected}> </Submenu>
                        <NgIf cond = {! This.state.loading}>
                          <FileSystem path = {this.state.path} sort = {this.state.sort} view = {this.state.view} selected = {this.state.selected}
                                      files = {this.state.files.slice (0, this.state.page_number * LOAD_PER_SCROLL)} isSearch = {this.state.is_search}
                                      metadata = {this.state.metadata || {}} onSort = {this.onSort.bind (this)} onView = {this.onView.bind (this)} />
                        </NgIf>
                      </NgShow>
                    </InfiniteScroll>
                    <NgIf cond = {this.state.loading === true}>
                      <Loader />
                    </NgIf>
                    <MobileFileUpload path = {this.state.path} />
                  </div>
                </div> </React.Fragment>
// ------------------------------------------------ ---------

the menu works correctly, what I am not being able to do is distinguish between a file or folder, and hence give the options.

If it is necessary to pay so that the code can be implemented, let me know.


thanks.
________________________________
De: santiago martinez <petrini_santi@hotmail.com>
Enviado: sábado, 24 de octubre de 2020 11:36
Para: mickael-kerjean/filestash <reply@reply.github.com>
Asunto: RE: [mickael-kerjean/filestash] [bug] Error uploading a folder (#300)

hello good morning, is it possible to integrate a menu with the right click to the page?
I integrated one but it is difficult for me to capture the file where the mause is.

I am attaching a photo to give you an idea of ​​what I'm talking about and the code so you can see.
File: filespage.js

import ContextMenu from 'devextreme-react / context-menu';
import notify1 from 'devextreme / ui / notify';

import {contextMenuItems as items} from './data.js';
// ------------------------------
 return (
            <div className = "component_page_filespage">
              <BreadCrumb className = "breadcrumb" path = {this.state.path} currentSelection = {this.state.selected} />
              <SelectableGroup onSelection = {this.handleMultiSelect.bind (this)} tolerance = {2} onNonItemClick = {this.handleMultiSelect.bind (this, [])} preventDefault = {true} enabled = {this.state.is_search === false} className = "selectablegroup">

              <React.Fragment>
                <div className = "page_container" id = "root">
<ContextMenu
dataSource = {items}
width = {200}
target = "# root"
onItemClick = {itemClick} />

             <div ref = "$ scroll" className = "scroll-y">
              <InfiniteScroll pageStart = {0} loader = {$ moreLoading} hasMore = {this.state.files.length> 70}
                                    initialLoad = {false} useWindow = {false} loadMore = {this.loadMore.bind (this)} threshold = {100}>
                      <NgShow className = "container" cond = {!! this.state.is_search || ! this.state.loading}>
                        <NgIf cond = {this.state.path === "/"}>
                          <FrequentlyAccess files = {this.state.frequents} />
                        </NgIf>
                        <Submenu path = {this.state.path} sort = {this.state.sort} view = {this.state.view} onSearch = {this.onSearch.bind (this)} onViewUpdate = {(value) => this .onView (value)} onSortUpdate = {(value) => this.onSort (value)} accessRight = {this.state.metadata || {}} selected = {this.state.selected}> </Submenu>
                        <NgIf cond = {! This.state.loading}>
                          <FileSystem path = {this.state.path} sort = {this.state.sort} view = {this.state.view} selected = {this.state.selected}
                                      files = {this.state.files.slice (0, this.state.page_number * LOAD_PER_SCROLL)} isSearch = {this.state.is_search}
                                      metadata = {this.state.metadata || {}} onSort = {this.onSort.bind (this)} onView = {this.onView.bind (this)} />
                        </NgIf>
                      </NgShow>
                    </InfiniteScroll>
                    <NgIf cond = {this.state.loading === true}>
                      <Loader />
                    </NgIf>
                    <MobileFileUpload path = {this.state.path} />
                  </div>
                </div> </React.Fragment>
// ------------------------------------------------ ---------

the menu works correctly, what I am not being able to do is distinguish between a file or folder, and hence give the options.

If it is necessary to pay so that the code can be implemented, let me know.


thanks.
________________________________
De: Mickael <notifications@github.com>
Enviado: sábado, 26 de septiembre de 2020 23:10
Para: mickael-kerjean/filestash <filestash@noreply.github.com>
Cc: santiago martinez <petrini_santi@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [mickael-kerjean/filestash] [bug] Error uploading a folder (#300)


I haven't run the CI/CD process yet, the commit is there, it just needs a build and some of my servers have been playing up recently (= the build hasn't run there yet)
