### ISSUE TITLE
[bug] Build fails on go 1.10.  Specify go version requirements in CONTRIBUTING.md

### ISSUE THREAD

**Issue by subdavis** [mickael-kerjean/filestash#304]
# Bug

Build fails on go 1.10

```
~$ make build_backend
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ CGO_CFLAGS_ALLOW='-fopenmp' go build -mod=vendor --tags "fts5" -ldflags "-X github.com/mickael-kerjean/filestash/server/common.BUILD_DATE=`date -u +%Y%m%d` -X github.com/mickael-kerjean/filestash/server/common.BUILD_REF=`git rev-parse HEAD`" -o dist/filestash server/main.go
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:12: recipe for target 'build_backend' failed
make: *** [build_backend] Error 2
```

```
~$ go version
go version go1.10.4 linux/amd64
```

Upgraded to go 1.14.9 and build is still failing.  See attached build log.

[buildlog.txt](https://github.com/mickael-kerjean/filestash/files/5212750/buildlog.txt)

# System details

```
~$ neofetch
            .-/+oossssoo+/-.   
        `:+ssssssssssssssssss+:`           --------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.5 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: Precision 5820 Tower X-Series 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.20.17-042017-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 8 days, 31 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2245 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 2160x3840, 3840x2160 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: LXDE 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: i3 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Adwaita [GTK3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Adwaita [GTK3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-7820X (16) @ 4.300GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA NVIDIA Corporation Device 1ec7 
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD Radeon PRO WX 3100 
      -+sssssssssssssssssyyyssss+-         Memory: 16204MiB / 31870MiB 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.                                       

```

**Comment by subdavis** [comment]
I've now tried to build with 1.13.15 and 1.12.17 and both have failed in the same way, so I dug around in the drone config and found that a good number of instructions for building have been left out.....

On another note: Building a docker image where your binary gets pulled from docker hub 1) totally defeats the point of reproducable builds in docker and 2) scares me a little bit.

I don't understand why you'd ever construct a docker image in this way.

Use multi-stage build and have this as your build stage....

``` dockerfile
FROM golang:1.12-stretch as builder

ENV CGO_LDFLAGS_ALLOW="-fopenmp"
ENV GO111MODULE="on"

WORKDIR /app
COPY . /app
RUN apt-get update > /dev/null && apt-get install -y libglib2.0-dev curl make > /dev/null
RUN make build_init
RUN make build_backend
RUN chmod -R o+r+w+x ./dist/data
```

**Comment by mickael-kerjean** [comment]
> Building a docker image where your binary gets pulled from github 1) totally defeats the point of reproducable builds in docker

The intent of the Dockerfile in the repo isn't to create a reproducible build. The way things work right now is:
- the CI create the build and run the test
- the build is signed and sent to an Apache server
- the docker image is being created from that build artifact. I didn't want to create a Dockerfile that would create yet another build as this would make CI much longer to run

> 2) scares me a little bit because you're pulling a remote binary in a shady way.

It's not shady, the binary artifact is created at build time and encrypt via GPG to mitigate an attack where someone own that server and replace that artifact with something nefarious.

Anyhow, all those are legit remarks but there's reasons for why things look the way they are.

> Anyway, I can't build unless I remove plg_image_light for whatever reason

`plg_image_light` require [those C libraries](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_light/deps) that you can either compile yourself or directly pull from the artifact server via `make build_init`
