### ISSUE TITLE
[bug] can't set ONLYOFFICE_URL

### ISSUE THREAD

**Issue by ScrumpyJack** [mickael-kerjean/filestash#310]
I have tried to set the ONLYOFFICE_URL as a variable passed to docker, and I have configured the OnlyOffice server from the admin page
APPLICATION_URL=filestash.example.com
ONLYOFFICE_URL=https://onlyoffice.example.com

Confirmed both are correct in the admin interface

Opening a document returns the error "[error] Can't reach the onlyoffice server"

Browser debug shows:

Step 1: HTTP GET https://filestash.example.com/path/to/ducument 200 OK
Step 2: open iframe /api/onlyoffice/iframe 200 OK and the iframe calls 
Step 3: looks like it results in redirect with a 302 for https://filestash.example.com/web-apps/apps/api/documents/api.js
Step 4: is a 404 because https://filestash.example.com/web-apps/apps/api/documents/api.js does not exist

It should be calling https://onlyoffice.example.com/web-apps/apps/api/documents/api.js 

Any ideas?

Here is the iframe that calls the OO API

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <style> body { margin: 0; } body, html{ height: 100%; } iframe { width: 100%; height: 100%; } </style>
    <div id="placeholder"></div>
    <script type="text/javascript" src="/onlyoffice/static/web-apps/apps/api/documents/api.js"></script>
    <script>
      if("DocsAPI" in window) loadApplication();
      else sendError("[error] Can't reach the onlyoffice server");

      function loadApplication() {
          new DocsAPI.DocEditor("placeholder", {
              "token": "foobar",
              "documentType": "text",
              "type": "desktop",
              "document": {
                  "title": "draft.doc",
                  "url": "http://10.0.6.163:8334/onlyoffice/content?key=key",
                  "fileType": "doc",
                  "key": "key"
              },
              "editorConfig": {
                  "callbackUrl": "http://10.0.6.163:8334/onlyoffice/event",
                  "mode": "edit",
                  "customization": {
                      "autosave": false,
                      "forcesave": true,
                      "compactHeader": true
                  },
                  "user": {
                      "id": "lc4d3bgdfd2bQdtdmLcY",
                      "name": "me"
                  }
              }
          });
      }
      function sendError(message){
          let $el = document.createElement("p");
          $el.innerHTML = message;
          $el.setAttribute("style", "text-align: center; color: white; opacity: 0.8; font-size: 20px; font-family: monospace;");
          document.body.appendChild($el);
      }
    </script>
  </body>
</html>
```

According to https://api.onlyoffice.com/editors/open, shouldn't the src in line 10 have the full path including the ONLYOFFCE_URL?
(sorry, no line numbers in this github markdown code block)

**Comment by mickael-kerjean** [comment]
The error has nothing to do with the content of the iframe, it originates from the reverse proxy Filestash creates to access only office so that you don't have to expose your only office instance to the internet at all. 
Everything works fine when you run only office via HTTP but brakes when it runs via HTTPS. Pull request is welcome, this is one of the issue I've spend way too much time working on without success

**Comment by ScrumpyJack** [comment]
Perhaps we could have option/environment variable to remove the reverse proxy that filestash creates for those who want/need their Only Office exposed, or prefer to block using a firewall?

**Comment by mickael-kerjean** [comment]
> Which part of the code creates the reverse proxy?

1. The [onlyoffice related endpoints](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_editor_onlyoffice/index.go#L74-L77)
2. The [reverse proxy part](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_editor_onlyoffice/index.go#L100-L147)


> Perhaps we could have option/environment variable to remove the reverse proxy that filestash creates for those who want/need their Only Office exposed, or prefer to block using a firewall?

If you can get it to work, feel free to make a PR
