### ISSUE TITLE
[bug] Select multiple files

### ISSUE THREAD

**Issue by guizmoau** [mickael-kerjean/filestash#311]
- I cannot select multiple files
- To reproduce bug, try to select multiple files, with CTRL or by dragging or ever
- cannot select multiple files
- expect to be able to select multiple files by any mean possible...

Thanks !

**Comment by mickael-kerjean** [comment]
Hey, I can't replicate what you're seeing. Can you take a video of your screen to show this?

**Comment by guizmoau** [comment]
I am just trying to select multiple files :/

I can't film something I can't do...
How do we do to select multiple files ??
