### ISSUE TITLE
It isn't possible to uninstall filestash

### ISSUE THREAD

**Issue by GamakCZ** [mickael-kerjean/filestash#313]
After deleting main directory and rebooting server the website still works

**Comment by devld** [comment]
Maybe it's because of the PWA. You can delete all cache by unregistering the service work in DevTools->Application->Service Works.

**Comment by GamakCZ** [comment]
I'm using console ubuntu

**Comment by mickael-kerjean** [comment]
@devld is correct, you need to remove the cache. Filestash tries its best to work with flaky connections which is why you still see something when your server is not there. Without the server, you can't log anywhere, that information isn't stored on your browser.

**Comment by VixikHD** [comment]
![obrazek](https://user-images.githubusercontent.com/40556088/94467361-1c4d2380-01c3-11eb-8b0d-261f4dd507bd.png)

🤔 I want to remove the webserver, no service worker ⬇️ 
![obrazek](https://user-images.githubusercontent.com/40556088/94467499-5caca180-01c3-11eb-93ef-fc4a4f08a148.png)

**Comment by devld** [comment]
```
docker ps
```
find the container, and then
```
docker stop <CONTAINER ID>
```

if you want to remove the container(CANT BE UNDONE)
```
docker rm <CONTAINER ID>
```
