### ISSUE TITLE
[Feature Request] Archive browsing

### ISSUE THREAD

**Issue by darkdragon-001** [mickael-kerjean/filestash#314]
It would be awesome if you add support for browsing archives (.zip, .tar, .tgz, .7z, .rar, ...).

**Comment by mickael-kerjean** [comment]
Want to work on a pull request for this?

**Comment by darkdragon-001** [comment]
I am quite busy with my new job and moving to a new city atm. I found some easy-to-use modules though: [node-unzip](https://github.com/EvanOxfeld/node-unzip) and [node-tar](https://github.com/npm/node-tar).

**Comment by darkdragon-001** [comment]
I am quite busy with my new job and moving to a new city atm.

Golang provides packages for easy access to archives:
- [zip](https://golang.org/pkg/archive/zip/#example_Reader)
- [tar](https://golang.org/pkg/archive/tar/#example__minimal)
- [gzip](https://golang.org/pkg/compress/gzip/#example__writerReader)

**Comment by mickael-kerjean** [comment]
I don't have a lot of time to create features I don't need but if someone want to pick this up and create a PR, such a feature would be nice to have

**Comment by mickael-kerjean** [comment]
I have closed this after some [disrespectful interaction](https://github.com/mickael-kerjean/filestash/issues/326#issuecomment-711251376) with @darkdragon-001, I don't want to spend my free time being insulted like this. If someone is willing to work this out, please open a new ticket to start from a clean slate
