### ISSUE TITLE
[Feature Request] Download folder as zip.

### ISSUE THREAD

**Issue by darkdragon-001** [mickael-kerjean/filestash#315]
It would be awesome if one could download a whole folder recursively as zip.

Furthermore, multiple items (files/folders) should be selectable and downloadable together (requires #311).

**Comment by darkdragon-001** [comment]
This feature is available in [MinIO browser (go/react S3 browser)](https://github.com/minio/minio/tree/master/browser) if you need some inspiration.

**Comment by mickael-kerjean** [comment]
I have 0 need for this but if you want to work on a PR that would be awesome

**Comment by darkdragon-001** [comment]
How du _you_ download folders?

Minio (golang) implementation can be found in [cmd/web-handlers.go](https://github.com/minio/minio/blob/017954e7ea23b5ff2d9e49300a09a0a3784bfaf6/cmd/web-handlers.go#L1531) using speed-optimized compression functions from [klauspost/compress](https://github.com/klauspost/compress).

**Comment by darkdragon-001** [comment]
Based on the like, one can see that such a feature would benefit multiple users.

**Comment by mickael-kerjean** [comment]
I have closed this after some [disrespectful interaction](https://github.com/mickael-kerjean/filestash/issues/326#issuecomment-711251376) with @darkdragon-001, I don't want to spend my free time being insulted like this. If someone is willing to work this out, please open a new ticket to start from a clean slate
