### ISSUE TITLE
[Feature Request] Nice/Predictable download URL

### ISSUE THREAD

**Issue by darkdragon-001** [mickael-kerjean/filestash#317]
In addition to `/files/PATH` for browsing, `/view/PATH` for preview, you should connect `/download/PATH` for downloads. Currently, the query component is used like `/api/files/cat?path=%2Fpictures%2Fimage.jpg`.

**Comment by mickael-kerjean** [comment]
What would be the point?

**Comment by darkdragon-001** [comment]
You could take the /view URL and just replace view by download instead of doing urlencode() for the GET parameter when using special characters...

**Comment by mickael-kerjean** [comment]
I haven't seen anyone saying they were issues in how special characters are handled and still don't see the point of such changes. Do you have an example of something that brakes in how it's currently done?

**Comment by darkdragon-001** [comment]
When you do path manipulations (join, basename, ...) one could use existing tools like [`urllib.parse.urljoin()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) on Python3 with relative paths when the location is encoded in the path component of the URL directly but it breaks when using query components instead.

**Comment by mickael-kerjean** [comment]
I have closed this after some [disrespectful interaction](https://github.com/mickael-kerjean/filestash/issues/326#issuecomment-711251376) with @darkdragon-001, I don't want to spend my free time being insulted like this. If someone is willing to work this out, please open a new ticket to start from a clean slate
