### ISSUE TITLE
[Feature Request] Backend file system (fs)

### ISSUE THREAD

**Issue by darkdragon-001** [mickael-kerjean/filestash#318]
It would be awesome to support local file system as backend. This way, I could mount a Kubernetes/Docker volume or a local disk into the container and provide cloud access to my existing files.

**Comment by mickael-kerjean** [comment]
OpenSSH server is installed on pretty much any Linux server for SSH and it has a building SFTP server

**Comment by darkdragon-001** [comment]
For security reasons, I don't want to open up new ports...

**Comment by mickael-kerjean** [comment]
Having openSSH server running doesn't mean you have to open up some ports, it's here:
```
root:~$ head -n 20 /etc/ssh/sshd_config 
#	$OpenBSD: sshd_config,v 1.101 2017/03/14 07:19:07 djm Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key
```

Just put 127.0.0.1 in your ListenAddress and you're good to go

**Comment by Victor239** [comment]
Could you write some instructions for doing this on Ubuntu? `/etc/ssh/ssh_config` is the only file in that directory and it hasn't got anything about "ListenAddress" in it.

**Comment by darkdragon-001** [comment]
@Victor239 To be honest, I don't know what you are talking about. You can just enter a file path on your system which gets served as `/` to the user. When you enter a relative path, it is relative to the filestash folder. If you enter an empty string, it defaults to `filestash/dist/data/files`. Of course the user running filestash needs the corresponding filesystem access rights.

For development, the easiest is to run it in VSCode inside a development container: https://github.com/mickael-kerjean/filestash/pull/322

**Comment by darkdragon-001** [comment]
@Victor239 You can also check my pull request #321. This way it works by just adding a file path via Web GUI.

**Comment by mickael-kerjean** [comment]
@Victor239 I will document this and keep you up to date.

Also I'm closing this as I don't intend to interact with @darkdragon-001 anymore after [this](https://github.com/mickael-kerjean/filestash/issues/326#issuecomment-711251376)

**Comment by Victor239** [comment]
Oof that sucks, I was watching that PR hoping it gets exposed simply to the frontend UI. Documentation will do though, looking forward to it.

**Comment by mickael-kerjean** [comment]
@Victor239 Here it is: https://www.filestash.app/2020/10/20/how-to-access-filesystem-using-filestash/
