### ISSUE TITLE
[bug] Unknow Path

### ISSUE THREAD

**Issue by Serrvosky** [mickael-kerjean/filestash#319]
Hello guys,

First of all, thank you for this amazing tool.

I'm having a problem at this moment and I'm not sure how I can resolve it. At the moment, I'm my pipeline I'm creating a binary of our application, and upload it to a bucket in object storage (on scaleway) to our team be able to download when they need. To perform this upload, I'm using aws-cli and I want to follow this pattern:

bucketName/appA/versionX/bin

I'm not having any problem to upload and create this pattern with aws-cli, but I found that filestash can't open any folder created by aws tool, giving the error `Oops! unknown Path`. Once I'm using scaleway, I searched for another method to upload my files, and I found another tool, called s3cmd. After I configured and tested it but I had the same output.

If I create all the folders, by hand, using filestash frontend, or scaleway console, all the things work fine, but I can't use this approach because I want to create automatically all the versions folders.

I tried to check to debug logs but can't find anything. Below you can find a little excerpt of them (xpto folder was automatically created inside base folder) but when I open it I get the error.
```
2020/10/01 10:56:41 DEBUG Search::indexing Execute PHASE_EXPLORE
2020/10/01 10:56:41 DEBUG Search::indexing Execute PHASE_EXPLORE
2020/10/01 10:56:41 DEBUG Search::indexing Execute PHASE_INDEXING
2020/10/01 10:56:41 DEBUG Search::indexing Execute PHASE_MAINTAIN
2020/10/01 10:56:41 DEBUG Search::indexing Execute PHASE_PAUSE
2020/10/01 10:56:46 INFO HTTP 200 GET  123.6ms /api/files/ls?path=%2Fbase%2F
2020/10/01 10:56:47 DEBUG Search::indexing Execute PHASE_EXPLORE
2020/10/01 10:56:47 DEBUG Search::indexing Execute PHASE_INDEXING
2020/10/01 10:56:47 DEBUG Search::indexing Execute PHASE_MAINTAIN
2020/10/01 10:56:47 DEBUG Search::indexing Execute PHASE_PAUSE
2020/10/01 10:56:49 INFO HTTP 500 GET  152.0ms /api/files/ls?path=%2Fbase%2Fxpto%2F
2020/10/01 10:56:50 INFO HTTP 200 GET    0.1ms /admin/api/session
2020/10/01 10:56:53 DEBUG Search::indexing Execute PHASE_EXPLORE
2020/10/01 10:56:53 DEBUG Search::indexing Execute PHASE_INDEXING
2020/10/01 10:56:53 DEBUG Search::indexing Execute PHASE_MAINTAIN
2020/10/01 10:56:53 DEBUG Search::indexing Execute PHASE_PAUSE
```

Thanks for all your help.

**Comment by mickael-kerjean** [comment]
It looks like something is going wrong somewhere in Filestash. Can you share some credentials to replicate this? If you don't want to make it public: mickael@kerjean.me or we can schedule a quick call: https://app.harmonizely.com/mickael/start

**Comment by Serrvosky** [comment]
Hi @mickael-kerjean. I just schedule a quick call with you for tomorrow. Thanks a lot.

**Comment by Serrvosky** [comment]
Hi @mickael-kerjean. Do you have any update for me?

**Comment by mickael-kerjean** [comment]
Not I haven't been able to replicate the error

**Comment by mickael-kerjean** [comment]
There's been some recent changes on the S3 plugin, did that solve the problem you were facing?
