### ISSUE TITLE
Incomplete Download

### ISSUE THREAD

**Issue by Rustymage** [mickael-kerjean/filestash#325]
I'm trying to download a 3.5GB file from my self-hosted (Docker) Filestash site via Chrome on a Mac and the file completes at 2.56GB. I run a reverse proxy infront of the service but nothing else.

I wonder if anyone has come across this before and knows a solution or perhaps can suggest some places to look?

Thanks in advance!

**Comment by mickael-kerjean** [comment]
That sounds like an issue from your reverse proxy. Can you replicate the error without the reverse proxy?

**Comment by Rustymage** [comment]
I just tried it via the IP (via VPN) and it stopped the download at 1.35GB. I also tried it again via the reverse proxy and it stopped at 3.03GB. The first download in the previous message at 2.56GB was without VPN.

I used a VPN as the server and download client are on the same LAN, so I wanted to ensure the connection was acting from a remote location.

**Comment by Rustymage** [comment]
Any thoughts on this as it appears to not be proxy related?

**Comment by mickael-kerjean** [comment]
I suspect the server is timing out the HTTP connection before the download is complete but that's just a gut feel, the last week and next few weeks will be busy on my side, I would appreciate a pull request if you can dig it through

**Comment by Rustymage** [comment]
I've dug around and hit brick walls in the form of my knowledge. I still sem to be impacted by the problem.

**Comment by Rustymage** [comment]
Will close as issue persists but I've found another way to share files.
