### ISSUE TITLE
[Feature Request] Some UI customization like a way to set the default view mode

### ISSUE THREAD

**Issue by Teufeuleu** [mickael-kerjean/filestash#327]
For example I would like it to be in list mode ordered by date.

Or maybe you can point me out where to change it "manually" in the docker install?

Sorry if my question seems trivial, I'm quite new to all this.

**Comment by mickael-kerjean** [comment]
The default isn't configurable as of today but I would appreciate a PR for this if you're willing to spend the time to work this out.

**Comment by mickael-kerjean** [comment]
Today, [this is where](https://github.com/mickael-kerjean/filestash/blob/master/client/pages/filespage.js#L42) it happens when it comes to default view

**Comment by Teufeuleu** [comment]
Thanks for you answer. I will definitely look at it even if I think my js skill is not strong enough to make a clean version of this feature.
