### ISSUE TITLE
[bug] Share Links & MP4

### ISSUE THREAD

**Issue by Rustymage** [mickael-kerjean/filestash#328]
**- description of the bug**

When sharing a link to an MP4 file, the link will not allow the media to play on the server. It states 'no compatible source was found for this file'. 

When viewing as the admin the media can be played.

**-step by step instructions to reproduce the bug**

Share link to MP4 file. View file via the shared link.

**- observed behavior**

 'no compatible source was found for this file'

**- expected behavior**

File can be played on the host.

Details: Self Hosted Docker on latest image.

ID | sha256:ec948d1676b15a52e078476a9cd8646f159a97a045c5f016d6780462a72b2cd9 Delete this image  Export this image
-- | --
Size | 1 GB
Created | 2020-08-06 16:13:35
Build | Docker 19.03.8 on linux, amd64
Author | mickael@kerjean.me

**Comment by Rustymage** [comment]
Here's the error Chrome chucks:

```
chunk_video_2_471ad82….js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
i {code: 4, message: "No compatible source was found for this media."}
code: 4
message: "No compatible source was found for this media."
__proto__:
MEDIA_ERR_ABORTED: 1
MEDIA_ERR_CUSTOM: 0
MEDIA_ERR_DECODE: 3
MEDIA_ERR_ENCRYPTED: 5
MEDIA_ERR_NETWORK: 2
MEDIA_ERR_SRC_NOT_SUPPORTED: 4
code: 0
message: ""
status: null
constructor: ƒ i(t)
__proto__: Object
```

**Comment by mickael-kerjean** [comment]
Hey, I can't reproduce the issue you're describing. For example: https://demo.filestash.app/s/8R5VtXa

**Comment by Rustymage** [comment]
> Hey, I can't reproduce the issue you're describing. For example: https://demo.filestash.app/s/8R5VtXa

Hi - I've moved across to a linux server to host this (away from Windows) and it is working now. Not sure if it was a windows bug...

**Comment by mickael-kerjean** [comment]
I don't use windows and as the documentation [mentions](https://www.filestash.app/docs/install-and-upgrade/#requirement): `The official installation method requires a Linux server`

**Comment by Isti115** [comment]
Sorry to bump this, but the same issue occurred to me under Linux as well.
When I turn off video transcoding the mp4 file still plays perfectly when I view it from my own directory structure, but if I share it, the sharing link just returns this message.
