### ISSUE TITLE
[bug] Cannot use "base" editor keybinding - editor fails to load

### ISSUE THREAD

**Issue by w0k3** [mickael-kerjean/filestash#330]
Hello,

when I use `General -> Editor: base` in admin settings (general.editor: "base" in config.json), I can't open the text editor.

Web browser exception:

`Uncaught (in promise) Error: Cannot find module './keymap_base'.
    i https://files.student.vazka.sk/assets/js/chunk_ide_6_4798faa508650d2c5548.js:1
    ...`

It works OK with "emacs" and "vim" bindings, but I need to make basic key bindings like `Ctrl+C` and `Ctrl+V` working and I was hoping "base" is the answer.

**Comment by w0k3** [comment]
Looks like the correct name of the keymap was changed to "sublime": https://codemirror.net/demo/sublime.html

When I replace "base" with "sublime" (which cannot be selected in admin interface), the editor loads and the key bindings are just fine. I think it can be fixed here: https://github.com/mickael-kerjean/filestash/blob/7c63073c810363f314de3357c6f33e7b2a3b1117/server/common/config.go#L75

**Comment by mickael-kerjean** [comment]
Thank you for the report, the above commit should fix the issue
