### ISSUE TITLE
[bug] Photo size of portrait photos on portrait screens

### ISSUE THREAD

**Issue by thielepaul** [mickael-kerjean/filestash#333]
The following screenshot shows on the right the current behavior and on the left the expected behavior.
Currently on a portrait format screen portrait photos are not scaled correctly (displayed to small).

![Bildschirmfoto_2020-10-18_16-57-52](https://user-images.githubusercontent.com/2041078/96371740-9427c180-1163-11eb-9d0b-ac434d5ce624.png)

The problem seems to be in https://github.com/mickael-kerjean/filestash/blob/master/client/pages/viewerpage/imageviewer.js#L278

A possible fix would be to change it to 
```js
return url+"&size="+parseInt(Math.max(window.innerWidth*size, window.innerHeight*size));
```

**Comment by mickael-kerjean** [comment]
Sounds good to me, can you make a PR for this?
