### ISSUE TITLE
[Feature Request] Native support for encrypted data, decryption client side ?

### ISSUE THREAD

**Issue by reyman** [mickael-kerjean/filestash#335]
Hi,

In the next week i move my RAW file on Backblaze B2 or Minio S3 like storage.

I'm not sure but is it possible to enhance FileStash to read data encrypted on this type of storage, asking users a password to decrypt photo on client side, in end-to-end encrypted way (like crypt.ee for example) ?

Thx !

**Comment by goldsolitude** [comment]
+1 for this, maybe implement something like gocryptfs? https://github.com/rfjakob/gocryptfs

**Comment by mickael-kerjean** [comment]
There's an option available in S3 compatible storage that Filestash already exposes in the encryption key login field available via the S3 backend:

<img width="1226" alt="Screen Shot 2020-11-01 at 11 51 15 pm" src="https://user-images.githubusercontent.com/13233076/97803271-28824000-1c9d-11eb-9dd2-9a56cb4e4c93.png">

Decryption happens on the server side though

**Comment by poVoq** [comment]
Maybe ETEsync 2.0 aka ETEbase could help implement this?
https://www.etebase.com/

**Comment by reyman** [comment]
@poVoq I don't know if EteBase is compatible with S3like storage backend, but yes, that could be a really good way to implement client side encryption. I ask the lead dev of EteBase on such a thing.

**Comment by tasn** [comment]
Hey, lead dev of Etebase here.
Etebase already does the encryption you, but it has a different API than S3 (as it's encrypted). Let me know if you need any help with this, I'm happy to provide guidance!

**Comment by reyman** [comment]
Perhaps a backend to Etebase backend could be cool for filestash, but that probably require some works, especially the sharing part !

**Comment by tasn** [comment]
It's not necessarily that much work!

**Comment by cr1za** [comment]
Is this already implemented by now?

**Comment by mickael-kerjean** [comment]
As of now, nobody has put up the time to get it done no

**Comment by mattredact** [comment]
> It's not necessarily that much work!

I'm willing to help work on this.
