### ISSUE TITLE
[bug] Can't connect to my account on rsync.net

### ISSUE THREAD

**Issue by rakoo** [mickael-kerjean/filestash#339]
First of all thank you for filestash, it's exactly what I needed ! I don't want to install a huge thing like Seafile or Nextcloud, I already have an SSH account on my VPS, no need to reinvent the wheel; a sexy SFTP browser is all I need.

I'm trying to migrate my personal data to [rsync.net](https://www.rsync.net/) because they have more guarantees of being up than I will ever have, and they provide good old sftp access even with an ssh shell. Unix tools just work !

My account works, I can access it with standard tools (`sftp`, FileZilla, etc...) but filestash doesn't work: when I'm entering my credentials I get a "Compte Invalid" error. The log doesn't help much:

```
2020/11/09 13:33:37 INFO HTTP 400 POST  363.5ms /api/session
```

Is there some setting I'm missing ? rsync.net doesn't provide free accounts for trialing, I can create a sub-account for anyone to test around if needed.

**Comment by mickael-kerjean** [comment]
That's interesting. Can you share some credentials I can use to replicate that? my email is: mickael@kerjean.me

**Comment by rakoo** [comment]
Mail sent

**Comment by mickael-kerjean** [comment]
The above commit should have fix the issue. Do you confirm?

**Comment by rakoo** [comment]
Sorry, I haven't had time to look at this. Will a simple update of docker be enough or do I need to build it locally ?

**Comment by rakoo** [comment]
Ok, I didn't seem to have the latest version earlier but now that I have it, it works. Thank you !
