### ISSUE TITLE
[bug]  Videos don't play on Android

### ISSUE THREAD

**Issue by rob151515** [mickael-kerjean/filestash#344]
I've just setup Filestash and it's working great except when trying to play a video on Android (using default Chrome browser on Pixel 4a) I'm getting the message "The media playback was aborted due to a corruption problem or because the media used features your browser did not support".

To reproduce try to play any video using Chrome on Android. I tried a bunch of different formats and none of them worked.

Observed behaviour is that the error message is displayed when trying to play a video.

The expected behaviour is that the video is transcoded to a format the Chrome on Android is able to play.

**Comment by mickael-kerjean** [comment]
Can you work it out and create a PR for it?
