### ISSUE TITLE
Website not working !

### ISSUE THREAD

**Issue by blmhemu** [mickael-kerjean/filestash#347]
Last checked at 26 November 2021 @ 7 PM IST

![image](https://user-images.githubusercontent.com/19410501/100355607-0f5c7d00-3018-11eb-9ade-1baa94194eba.png)

**Comment by JayRizuri** [comment]
yep im pretty sure i accidentally crashed it

**Comment by blmhemu** [comment]
Looks like it's fixed. Closing this.
