### ISSUE TITLE
Protecting Web

### ISSUE THREAD

**Issue by JustTestCode** [mickael-kerjean/filestash#348]
How is it protected when anyone with an address on the Internet can access it? like `/admin` 
For now, I'm using nginx HTTP Basic authentication.

**Comment by mickael-kerjean** [comment]
I would appreciate if you'd read the issue template before creating a new issue:
<img width="934" alt="Screen Shot 2020-12-07 at 11 38 22 pm" src="https://user-images.githubusercontent.com/13233076/101351859-5afb0a80-38e5-11eb-9ee0-c3037b69bfec.png">
