### ISSUE TITLE
[Feature Request] Sharing Enhancements

### ISSUE THREAD

**Issue by erraticallyefficient** [mickael-kerjean/filestash#349]
Just getting started with FileStash, and I've noticed a couple of minor gaps around file sharing.

My use case is using FileStash to give a small group of people read only access to a big file repository, to generate read-only sharing links for (relatively) untrusted third parties to download content. Obviously as anyone with the url/password could download the files, I'd like these sharing links to be audited, and to always have a limited lifespan.

With this in mind, it would be good to be able to have a couple of extra sharing options in the config:
- Enforce password - When checked, sharing links would need to have a password specified as part of creating a sharing link. This could default to a randomise series of characters.  
- Enforce expiry - When checked, sharing links would need to have an expiry specified as part of creating a sharing link. This could default to 7 days time. 

Finally, at present I'm not able to see a central listing of all the active sharing links. This could be a new page, with a grid style listing of any active sharing links. Bonus would be to be able to delete these links if required. 

If anyone has any workarounds for these current limitations, feedback would be greatly appreciated!

**Comment by mickael-kerjean** [comment]
can you work it out and create a PR for it?

**Comment by erraticallyefficient** [comment]
hey @mickael-kerjean, thanks for all the hard work!

unfortunately it's not something I have time to investigate/learn at the moment... maybe in the new year!
