### ISSUE TITLE
[bug] Website is not working

### ISSUE THREAD

**Issue by sarneeh** [mickael-kerjean/filestash#351]
The website under https://www.filestash.app/ does not work. I think this is a critical issue as one can't even access the documentation anywhere.

**Comment by mickael-kerjean** [comment]
The website was down indeed, some networking issues in the kubernetes cluster that hosts all my stuff + stuff related to this project.

If someone happens to read this comment in the future, the website code is stored in [this repo](https://github.com/mickael-kerjean/filestash-website)
