### ISSUE TITLE
[Feature Request] Download Folder Feature #337

### ISSUE THREAD

**Issue by coxtor** [mickael-kerjean/filestash#352]
Hi, 
I realize this seems to be a difficult topic here as reading #315,  #252 and perhaps more, but @thielepaul was so kind to do most of the work with #337 it appears. 
Could we please get #337 merged? It would boost the usefulness of the application greatly. 
Unfortunately I can't complete the remaining tasks, if this is all that is needed to be done. I'd gladly help with testing or what is necessary. 
Work on this would be greatly appreciated, thanks.

**Comment by mickael-kerjean** [comment]
The feature is up for grab if you want to work on it

**Comment by coxtor** [comment]
I'd love to, however I am not sure what is missing in order to merge it . Also my go skills are limited .

**Comment by thielepaul** [comment]
A rough list of ToDos can be found in the MR: https://github.com/mickael-kerjean/filestash/pull/337#issue-514359546
Feel free to continue what I started!

**Comment by thielepaul** [comment]
The wontfix label seems to be not appropriate anymore: https://github.com/mickael-kerjean/filestash/commit/eb81398ce8ebd906ccd07d0d666a7f7fd8077aa2
Thanks for implementing this @mickael-kerjean
