### ISSUE TITLE
[bug] TypeError in video viewer

### ISSUE THREAD

**Issue by danielfomin96** [mickael-kerjean/filestash#353]
When in picture presentation mode and changing from one video to another video by using the arrows, I am getting a blank page and the following error :
```
Uncaught (in promise) TypeError: The element or ID supplied is not valid. (videojs)
```
It happens with or without transcoding.
I expect to see the picture presentation to show the next video instead a blank page is shown.
Firefox and Chrome both have the same problem.

**Comment by mickael-kerjean** [comment]
can you create a PR that fixes it?

**Comment by danielfomin96** [comment]
I will try but I do not have a lot of time to allocate to this

**Comment by danielfomin96** [comment]
After checking back on this issue I could not find it anymore on my instance.
