### ISSUE TITLE
[bug] Can't enter sharing link's expiration date in Safari on macOS

### ISSUE THREAD

**Issue by michalhosna** [mickael-kerjean/filestash#356]
It's impossible to set expiration date when creating or editing sharing link in Safari on macOS.

When one starts typing, it fills up with garbage `-00-01`. 

![empty-input](https://user-images.githubusercontent.com/679759/103467338-7de6d600-4d4e-11eb-8fc9-8c774fceea1d.gif)

Pasting doesn't work either. When i try to paste `2021-01-30` it resets to `2021-00-30`

![pasting](https://user-images.githubusercontent.com/679759/103467341-80e1c680-4d4e-11eb-941c-d4b1db69884d.gif)

Any editing ends in NaN-NaN-NaN

![editing](https://user-images.githubusercontent.com/679759/103467362-a4a50c80-4d4e-11eb-9de7-b90fc59f8956.gif)

**Expected behavior:** Get calendar UI, or at least be able to entre the date manually in some format.

### Tested on:
Tested on https://demo.filestash.app/files/ 
Same locally using docker image `machines/filestash:e02267d`

### Broken in:
Safari 14.0.2 on macOS 11.1

### Works as expected in:
Safari on ipadOS 14.2
Safari on iOS 14.2
Firefox on macOS 11.1

**Comment by mickael-kerjean** [comment]
Safari has a different way to parse date than every other single browser. Unfortunately I don't have a mac and iphone from which I could fix this. Can you try to create a fix and create a PR for this?
