### ISSUE TITLE
[Feature Request] Support s3 virtual hosted-style host

### ISSUE THREAD

**Issue by deluxghost** [mickael-kerjean/filestash#357]
Reference: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

The s3-compatible provider I'm using doesn't support path-style, only virtual hosted-style works.

[aws sdk doc](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config):

```go
    // Set this to `true` to force the request to use path-style addressing,
    // i.e., `http://s3.amazonaws.com/BUCKET/KEY`. By default, the S3 client
    // will use virtual hosted bucket addressing when possible
    // (`http://BUCKET.s3.amazonaws.com/KEY`).
    //
    // Note: This configuration option is specific to the Amazon S3 service.
    //
    // See http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html
    // for Amazon S3: Virtual Hosting of Buckets
    S3ForcePathStyle *bool
```

There might be also some code about path joining that needs changes

**Comment by deluxghost** [comment]
what? there isn't any reply yet

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process

**Comment by yanickxia** [comment]
@mickael-kerjean  pls, reopen, we need it

**Comment by mickael-kerjean** [comment]
Can you work it out and create a PR for it?

**Comment by yanickxia** [comment]
> Can you work it out and create a PR for it?

let me try ……
