### ISSUE TITLE
Raspbarry Pi 4 - build script working 

### ISSUE THREAD

**Issue by Naphtaline** [mickael-kerjean/filestash#359]
Hi !
I managed to build and setup the app, outside docker, as a standalone app on Raspbarry Pi 4 with la basic and latest RaspbianOS.

BUT (of course there is an issue left) I don't see any picture on the interface :
![image](https://user-images.githubusercontent.com/1192256/104239515-e9b9f480-545a-11eb-8317-547a0850aa38.png)

I found the mime type issue you fixed for someone a while ago, but of course since I'm running your setup on master branch, this is not the issue here. Also :
![image](https://user-images.githubusercontent.com/1192256/104239677-356c9e00-545b-11eb-8f01-c9e893e869cd.png)

No problem to get the images, it's just the display part..

![image](https://user-images.githubusercontent.com/1192256/104239952-95634480-545b-11eb-8a96-4587580cd645.png)

I cannot display an image either.

Maybe it comes from a lib ?...

I'm open to suggestions !

Anyway, if you want, when I fix everything, I'm willing to PR my work.

**Comment by mickael-kerjean** [comment]
It seems to be an issue from Filestash not knowing the mimetype of the file you're seeing and assume by default it is a [application/octet-stream](https://github.com/mickael-kerjean/filestash/blob/fd1249c4d68a755ba1e3cedea9a534c5e60e643e/server/common/mime.go#L19). 

The build instruction is available [here](https://github.com/mickael-kerjean/filestash/blob/master/CONTRIBUTING.md#building-from-source) and relevant section that generate the mime type config is in the [make build_init](https://github.com/mickael-kerjean/filestash/blob/master/Makefile#L4-L6) and specifically [this section](https://github.com/mickael-kerjean/filestash/blob/master/Makefile#L6) which does run [this](https://github.com/mickael-kerjean/filestash/blob/fd1249c4d68a755ba1e3cedea9a534c5e60e643e/server/common/mime.go#L8)

As far as lib, the only 2 C libraries that needs to be build are documented [here](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_light/deps) which would probably need a PR from [this](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_light/deps/create_libresize.sh) and [this](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_image_light/deps/create_libtranscode.sh)

**Comment by Naphtaline** [comment]
I will try with your contributing guide, I must admit I didn't find it before now...
And for the libs, I got them from you !
![image](https://user-images.githubusercontent.com/1192256/104291063-61b80700-54bb-11eb-8ef9-5c0f733d7ff1.png)
I'll try without recompiling them first and I tell you how it goes.

**Comment by Naphtaline** [comment]
I rebuild following your instructions, it works better now :
![image](https://user-images.githubusercontent.com/1192256/104344669-baa88f00-54fd-11eb-9231-76464a85a5a8.png)

But still, I cannot see icons.
and my mime.json look like
![image](https://user-images.githubusercontent.com/1192256/104344848-f4799580-54fd-11eb-9c31-fcee9450168a.png)

I'm runing filestash from the repo :
filestash/dist/filestash
and my mime.json is located :
filestash/dist/data/state/config/mime.json

I believe it's the right mime.json file, the one that the binary is using

**Comment by Naphtaline** [comment]
However, the is a difference between images I can see for instance all of these :
![image](https://user-images.githubusercontent.com/1192256/104345936-25a69580-54ff-11eb-9241-92211f0cf8d4.png)
and the one I cannot see
the difference in the source code of the page is :
this on I cannot see
![image](https://user-images.githubusercontent.com/1192256/104346085-4d95f900-54ff-11eb-84ff-f9975de2fd0f.png)
and this one I can
![image](https://user-images.githubusercontent.com/1192256/104346200-6dc5b800-54ff-11eb-8f72-94a797d2a427.png)

I'm not familiar in web integration but i notice that there is a base64 encoded thing in the svg I can see

Any idea of what is it ?

**Comment by Naphtaline** [comment]
I decoded the base64 thing, it's the actual SVG file with some xml structure around it.
So I'm pretty sure the images from the "dynamic content" are not processed at all, where the icons from the main interface are.

I'll try to dig the code to find where if fails.

**Comment by Naphtaline** [comment]
I fixed it
I'm just doing a final test then I do the PR. 
Also I'm pretty sure this problem affect every versions, not only Raspberry.

**Comment by mickael-kerjean** [comment]
Just saw all your messages, I'm confused as I don't see problem affecting anything. The images you sent is the normal behavior that's working for everyone else and I'm not sure to understand the problem you are facing, can you advise what behavior is not working for you?

**Comment by Naphtaline** [comment]
Ok let me show you :
here is what I see without what I've done in PR :
![image](https://user-images.githubusercontent.com/1192256/105007534-68ed9080-5a38-11eb-8113-7de2574c2a48.png)
On files and directories, so as edit share and delete, there are no icons
And after the fix it look like :
![image](https://user-images.githubusercontent.com/1192256/105007700-976b6b80-5a38-11eb-8da8-9eb915da1448.png)

**Comment by mickael-kerjean** [comment]
The fix in the PR was the previous behaviour from 2 years ago which was change to get better performance while listing large amount of stuff.
Can you replicate the error you're seeing from https://demo.filestash.app/ ? If so which browser are you using and on which platform?

**Comment by Naphtaline** [comment]
Ok I understand what you did
here is my result for  https://demo.filestash.app/
![image](https://user-images.githubusercontent.com/1192256/105021037-5c713400-5a48-11eb-8a7b-962e7b2ec8c4.png)
Seems to be alright and the image is treated in the same way as I was showing at the begining of this issue 🤔 (aka : not hashed in base64)
I will re setup the faulty install, give you the link and you will see. But you can also try if you have a raspberry available (now I begin to believe that the issue is somehow platform related, like a dependency not behaving properly)
