### ISSUE TITLE
[bug] Demo git not working 

### ISSUE THREAD

**Issue by ngjuping** [mickael-kerjean/filestash#360]
# Description
The demo page https://www.filestash.app/docs/ doesn't work when I tried to connect to my git repo...

# Step-by-step to reproduce the bug
Enter repo name, username and password, and press connect.

# Observed behavior
An error window popped at the bottom left corner, with words: Exec: "git": executable file not found in $PATH
![image](https://user-images.githubusercontent.com/35101494/104631181-dca93980-56d6-11eb-8686-56e49e6fd232.png)

# Expected behavior
Should connect to my repo

**Comment by mickael-kerjean** [comment]
That's quite a bad error message that needs to be address but the feature itself is working as expected, eg: https://demo.filestash.app/login?type=git&repo=https://github.com/mickael-kerjean/filestash-website

**Comment by ngjuping** [comment]
It's now fixed! I will close the issue
