### ISSUE TITLE
[bug] Problem with `make build_backend`.

### ISSUE THREAD

**Issue by tgates-nalej** [mickael-kerjean/filestash#368]
I setup a Linux build machine to build Filestash.  But it fails to build the backend.

Steps to reproduce:

```
tgates@orca1:~/gopath/src/mickael-kerjean$ git clone https://github.com/mickael-kerjean/filestash.git
Cloning into 'filestash'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 8640 (delta 19), reused 34 (delta 19), pack-reused 8586
Receiving objects: 100% (8640/8640), 28.52 MiB | 192.00 KiB/s, done.
Resolving deltas: 100% (4611/4611), done.
tgates@orca1:~/gopath/src/mickael-kerjean$ cd filestash/
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ npm install >& npm_install.log
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ make build_init >& build_init.log
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ mkdir -p ./dist/data/state/
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ cp -R config ./dist/data/state/
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ make build_frontend >& build_frontend.log
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ make build_backend >& build_backend.log
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ head build_backend.log 
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ CGO_CFLAGS_ALLOW='-fopenmp' go build -mod=vendor --tags "fts5" -ldflags "-X github.com/mickael-kerjean/filestash/server/common.BUILD_DATE=`date -u +%Y%m%d` -X github.com/mickael-kerjean/filestash/server/common.BUILD_REF=`git rev-parse HEAD`" -o dist/filestash server/main.go
# github.com/mickael-kerjean/filestash/server/plugin/plg_image_light
server/plugin/plg_image_light/deps/libresize_linux_amd64.a(libresize.o): In function `image_resize':
libresize.c:(.text+0x145): undefined reference to `g_object_unref'
server/plugin/plg_image_light/deps/libresize_linux_amd64.a(error.o): In function `vips_check_matrix':
/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/iofuncs/error.c:1231: undefined reference to `g_object_unref'
/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/iofuncs/error.c:1228: undefined reference to `g_object_unref'
server/plugin/plg_image_light/deps/libresize_linux_amd64.a(image.o): In function `vips_image_class_intern_init':
/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/iofuncs/image.c:389: undefined reference to `g_type_class_peek_parent'
/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/iofuncs/image.c:389: undefined reference to `g_type_class_adjust_private_offset'
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ tail build_backend.log 
server/plugin/plg_image_light/deps/libresize_linux_amd64.a(matalloc.o): In function `im_fvector':
/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/deprecated/matalloc.c:72: undefined reference to `g_type_check_instance_cast'
server/plugin/plg_image_light/deps/libresize_linux_amd64.a(matalloc.o): In function `im_dvector':
/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/deprecated/matalloc.c:83: undefined reference to `g_type_check_instance_cast'
server/plugin/plg_image_light/deps/libresize_linux_amd64.a(matalloc.o): In function `im_imat_alloc':
/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/deprecated/matalloc.c:140: undefined reference to `g_type_check_instance_cast'
server/plugin/plg_image_light/deps/libresize_linux_amd64.a(matalloc.o):/tmp/filestash/libresize/tmp/vips-8.7.0/libvips/deprecated/matalloc.c:147: more undefined references to `g_type_check_instance_cast' follow
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'build_backend' failed
make: *** [build_backend] Error 2
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ go version
go version go1.15.7 linux/amd64
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ npm version
{
  filestash: '0.0.0',
  npm: '6.14.11',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '38.1',
  icu: '68.2',
  llhttp: '2.1.3',
  modules: '88',
  napi: '7',
  nghttp2: '1.42.0',
  node: '15.7.0',
  openssl: '1.1.1i',
  tz: '2020d',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.6.395.17-node.23',
  zlib: '1.2.11'
}
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ nodejs -v
v8.10.0
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ node -v
v15.7.0
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ git version
git version 2.17.1
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ make -v
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ apt list -a libglib2.0-dev
Listing... Done
libglib2.0-dev/bionic-updates,bionic-security,now 2.56.4-0ubuntu0.18.04.6 amd64 [installed]
libglib2.0-dev/bionic 2.56.1-2ubuntu1 amd64

tgates@orca1:~/gopath/src/mickael-kerjean/filestash$ 
```

I can upload any of the above log files.

Thanks,
-tom

**Comment by tgates-nalej** [comment]
The log files are attached.

[npm_install.log](https://github.com/mickael-kerjean/filestash/files/5889158/npm_install.log)
[build_init.log](https://github.com/mickael-kerjean/filestash/files/5889159/build_init.log)
[build_frontend.log](https://github.com/mickael-kerjean/filestash/files/5889160/build_frontend.log)
[build_backend.log](https://github.com/mickael-kerjean/filestash/files/5889161/build_backend.log)

**Comment by Bramas** [comment]
I don't know what is the problem, but here is what I used to install filestash locally for development

I created a Dockerfile : https://github.com/Bramas/filestash/blob/docker-dev/docker/Dockerfile.dev
put it in the docker folder of filestash and then you need to build it and execute the installation inside the container

(in the filestash folder:)
```
# Build the image
docker build -f docker/Dockerfile.dev -t filestash-dev .

# Run the image
docker run -v $(pwd):/var/app -p 8334:8334 -it filestash-dev

# Install and run as explained in the previous section
```

When creating the dockerfile I remember that the version of go was important (I used 1.14)

**Comment by tgates-nalej** [comment]
My above commands are following the build instructions from the "official" Filestash repo to build from source code.  

  https://github.com/mickael-kerjean/filestash/blob/master/CONTRIBUTING.md#building-from-source
  
I see conflicting information in the "official" repo about how to build this.  What is the correct way to build Filestash from source code?

**Comment by tgates-nalej** [comment]
I tried the following instructions, but it didn't work.

https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_light/deps

**Comment by Bramas** [comment]
I also followed the official instructions, but inside a container, which should work similarly in a fresh debian install.
You can see in my dockerfile what package I installed, maybe you need a package.
Or maybe in your case some pkg-config is missing but I don’t know why

**Comment by mickael-kerjean** [comment]
The build instruction can be seen [here](https://github.com/mickael-kerjean/filestash/blob/master/CONTRIBUTING.md#building-from-source), the project relies on some custom made C libraries to handle image related stuff like resizing and transcoding and the logs says the linker in its own words it can't find those libraries. To install those libraries, you can either:
- build it yourself: https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_light/deps
- `make build_init`, if you're on hardware I've created the build for, it will just work

**Comment by tgates-nalej** [comment]
@mickael-kerjean  I followed those build instructions, shown in bug description, which includes `make build_init` but it did not "just work".  I also included the logs from those commands in this bug report.

**Comment by mickael-kerjean** [comment]
ho my mistake, can you install the glib on your system? Basically the resizing library relies on another C library called libvips which relies on among other side on the glib and Unfortunately I coudn't manage to statically compile that libvips library entirely, hence errors you're seeing like `g_object_unref`, `g_type_check_instance_cast` and all the other function that have a `g_` prefix

**Comment by tgates-nalej** [comment]
@mickael-kerjean Glib 2.0 is listed as a prerequisites in the CONTRIBUTING.md.  I had previously installed glib on this system.  The installed glib version is shown near the bottom of the bug description.

**Comment by tgates-nalej** [comment]
@mickael-kerjean  Can you provide guidance on this?

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
