### ISSUE TITLE
[bug] Search in admin panel. Checkbox in config is backwards for SFTP.

### ISSUE THREAD

**Issue by esturniolo** [mickael-kerjean/filestash#370]
###DESCRIPTION
Hi guys. I have my container from a fresh install and I saw that the `Search` function doesn't work. By default, in the admin panel, `Search` in enabled.

![image](https://user-images.githubusercontent.com/5169045/106929929-bd109a00-66f3-11eb-977a-b56fdb3490d9.png)
![image](https://user-images.githubusercontent.com/5169045/106930305-27c1d580-66f4-11eb-9a41-b23668950d0a.png)
![image](https://user-images.githubusercontent.com/5169045/106930344-30b2a700-66f4-11eb-851b-c1a1b55a07df.png)
![image](https://user-images.githubusercontent.com/5169045/106930360-35775b00-66f4-11eb-823b-7c18f5a6d803.png)

I started to play with this checkbox and finally I realized that when the checkbox is empty, the search starts to work. If the checkbox is checked, doesn't work.

![image](https://user-images.githubusercontent.com/5169045/106930469-58a20a80-66f4-11eb-925d-c64af8e5ded1.png)
![image](https://user-images.githubusercontent.com/5169045/106930515-66579000-66f4-11eb-8286-6ed27f21236f.png)
![image](https://user-images.githubusercontent.com/5169045/106930569-766f6f80-66f4-11eb-91cd-f97904c6b470.png)

###How reproduce it and observed behavior
- Make a fresh install and take a look to the `Search`. Should be enabled.
- Try to search something inside your SFTP connection.
- You should see that the search brings nothing.

###Expected behavior
Search for files/folders in SFTP connection when the `Search` checkbox is checked in the admin panel.

**Comment by Bramas** [comment]
Hi.
Two things are weird.
* search is disabled by default https://github.com/mickael-kerjean/filestash/blob/fd1249c4d68a755ba1e3cedea9a534c5e60e643e/server/model/search.go#L55-L57
* when search is disable it doesn't really mean search is disabled, it means indexing is disabled. Basic search should always work. Maybe in your case search with indexing enabled does not work well because of what you search or I don't know (In fact, it is weird that you did not compare the results with the same search terms)

Sorry I cannot help your more.

**Comment by esturniolo** [comment]
Hi @bramas.
Thanks for your answer.

>  it is weird that you did not compare the results with the same search terms

My bad. Here are the same search terms with search disable.

![image](https://user-images.githubusercontent.com/5169045/106949201-6a42dc80-670b-11eb-8810-bf73a84a0141.png)
![image](https://user-images.githubusercontent.com/5169045/106948941-1cc66f80-670b-11eb-90b6-d6b73a37eadc.png)
![image](https://user-images.githubusercontent.com/5169045/106949075-497a8700-670b-11eb-8c9d-11ba75d7ea8d.png)


I'll redeploy the container, but besides if the search is enable or not by default, the behavior with SFTP is strange.
The files:
-`01numberOne`
-`02numberTwo`
were created with the `New file` option from Filestash. The `03numberThree` was a markdown file called `Readme.md` that I uploaded from my local machine and then edited with the Filestash online editor.

**Comment by esturniolo** [comment]
I redeploy from scratch and can confirm two things:

1. As @Bramas said, the Search checkbox is disabled by default.
2. The SFTP search only works if the Search checkbox is disabled. When I enable it, I get the results of my first post.

**Comment by mickael-kerjean** [comment]
There's reason for all that, the documentation should definitly reflect all that as it can be confusing indeed. Filestash has 2 type of search which both have their pro/cons:
- the enabled by default search which is **stateless** and relies on a quick crawl of the filesystem for a few ms to find potentially relevant results in the file names only.
- the full text search which is **statefull**, comes with both a crawler that's constantly getting through your filesystem and creating and maintaining over time an index that include both the file names and content of the supported files. This option is disabled by default as crawling through your filesystem can be an expensive thing if you want to do that on a big S3 bucket where AWS charges both for API calls and data transfer. The other problem coming with such search is it's not instant, it both takes a restart to become active and time for the crawler to both crawl through your filesystem and index it, hence the non instant results you're seeing.

**Comment by esturniolo** [comment]
Hi @mickael-kerjean.
With your explanation all make sense now.
What puzzled me was that the search in my WebDav connection works instantly but in the SFTP not.

Today I'll wait for the indexing and see the results.

Thanks
