### ISSUE TITLE
[Feature Request] Filestash redirection to login page for unauthorised users while accessing the files

### ISSUE THREAD

**Issue by azramasood** [mickael-kerjean/filestash#371]
when we are accessing any files uploaded on filestash if the user is not authorised then its giving an error -" Not Authorized". This error message is getting while we are accessing onlyoffice files, pdfs and images. The expected behaviour  is that, it should redirect to login page whenever the user is unauthorised.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
