### ISSUE TITLE
[Feature Request] When downloading file, data fetched 2 times from ftp server, direct download?

### ISSUE THREAD

**Issue by timnis** [mickael-kerjean/filestash#372]
Hi,

I have tested filestash and it work really nice on slow connections, but I noticed one thing when tested on ftp server which is behind slow link (IoT device).

When you want to download file you 
1.  first click filename and it opens it to editor
2. then you can click download button and get the file

The problem is that it filestash download file two times from FTP-server? This comes to problem when you have bigger file and slow link or link with quota, it takes double of the time and data.

**Test**
Connection from filestash to IoT device which has IoT SIM (max 128/128kbits and quota 20M/month :))

with following file
![image](https://user-images.githubusercontent.com/31338854/108198861-d4ed1280-7124-11eb-8496-124709c2daca.png)

connected to ftp server and got file listing
![image](https://user-images.githubusercontent.com/31338854/108198659-922b3a80-7124-11eb-93af-dd474ddf10ea.png)
 
opened file to editor
![image](https://user-images.githubusercontent.com/31338854/108198719-a838fb00-7124-11eb-83ff-512b8ed76e26.png)

and when downloaded file
![image](https://user-images.githubusercontent.com/31338854/108198792-bedf5200-7124-11eb-96f4-0e1ed3ee3802.png)

At the moment according #176 preview cannot be disabled, so could it be possible to add direct download button to file listing page, maybe before delete button?

**Comment by timnis** [comment]
is it possible to add download link to file listing?

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
