### ISSUE TITLE
[bug] Upload file with metadata

### ISSUE THREAD

**Issue by ezeroti** [mickael-kerjean/filestash#374]
Hi guys. I found that when I upload a file to an S3 bucket it does not keep the metadata of the file:

![image](https://user-images.githubusercontent.com/25537441/109085971-7eb23d80-76e9-11eb-8112-295cdd88dd8f.png)

Usually what I upload are files of the type jpg or png, and I change the value to: "binary / octet-stream"

Thanks!

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
