### ISSUE TITLE
[bug] filestash.app public demo error 502: bad gateway

### ISSUE THREAD

**Issue by simonfelding** [mickael-kerjean/filestash#376]
The public demo is broken.

**Comment by nikhilweee** [comment]
The public demo is still broken.

**Comment by TeNNoX** [comment]
Impressive first impression :sweat_smile: 
https://user-images.githubusercontent.com/2084639/113175951-46ec6780-924c-11eb-9ca9-cad743a4567c.mp4

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
