### ISSUE TITLE
[bug] Upload file error

### ISSUE THREAD

**Issue by lilplayer6k** [mickael-kerjean/filestash#378]
Hello there @mickael-kerjean ! if you drag and drop a file which in my case was a .mp4 file it says `Uncaught TypeError: Cannot read property 'fullPath' of null` on the <a href=https://demo.filestash.app>FTP</a> and it wouldn't upload the file. please fix this issue soon. thanks!

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
