### ISSUE TITLE
[bug]  Expiration of shared links – mismatch of input and result

### ISSUE THREAD

**Issue by spitzenwirbel** [mickael-kerjean/filestash#379]
**Bug description**

When selecting an expiration date for a shared link the resulting date is wrong.
E.g. choosing 30/05/2021 will result in 30/04/21.

**Steps to reproduce**: 

Visit [demo.filestash.app (with play.minio.io as S3 backend)](https://demo.filestash.app/login?type=s3&access_key_id=Q3AM3UQ867SPQQA43P2F&secret_access_key=zuf%2BtfteSlswRu7BJ86wekitnifILbZam1KYY3TG&region=us-east-2&encryption_key=&endpoint=https%3A%2F%2Fplay.minio.io%3A9000%2F) and create a shared link for any folder or file.
Under advanced set the *Expiration*  date to e.g. *30/05/2021* (via calendar) the text box then will will show *30/04/2021*.

**Comment by Bramas** [comment]
Hi, it should be fixed by #366

The fix has not reached the release version yet I think.

**Comment by spitzenwirbel** [comment]
Thanks,

I am using the official docker image ([machines/filestash](https://hub.docker.com/r/machines/filestash)). Will provide feedback when it is updated.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
