### ISSUE TITLE
[bug] 'Invalid Account' error from anonymous ftp directory

### ISSUE THREAD

**Issue by toaster42** [mickael-kerjean/filestash#380]
When attempting to connect to the ftp server [ftp://iodd.kr/open/]() (which accepts public, anonymous users) I encounter the Invalid Account error regardless of username/password combo (or lack thereof). As a sanity check I am able to connect via *cyberduck.app* in Mac OS X 10.15.7 (**user/pass**: `null`/`null`, **port**:`21`, **connections**: `2`).

I'm wondering if this bug might be related to the fact that the ftp server root directory does not allow anonymous connections, while the directory /open/ does.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
