### ISSUE TITLE
[bug] Unable to reach hosted server on Raspberry pi 4 with Artix Linux

### ISSUE THREAD

**Issue by FabseGP** [mickael-kerjean/filestash#383]
Hi, 

I had recently found Filestash online, which seemed as the perfect service for me to host - the only problem is that I am unable to reach the server, even if I change the ports or the application-URL; I therefore don't think that it is something wrong with these two configuration. But I am also sure that it is my Raspberry Pi, which is the issue, as I am able to host Nextcloud, Photoprism, Syncthing and more without any issue :)

I also just installed it by using your guide on your website for setting it up with docker - I have also checked that the container is up and running - so I have no clue as why it wouldn't work. Can any of you maybe help me with that? :)

_Installation_:

1. mkdir filestash && cd filestash
2.  curl -O https://downloads.filestash.app/latest/docker-compose.yml
3.  docker-compose up -d

_My docker-compos.yml file_: (even the default port, which is 8334, did not work either)

version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
    - APPLICATION_URL=
    - GDRIVE_CLIENT_ID=<gdrive_client>
    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    - DROPBOX_CLIENT_ID=<dropbox_key>
    - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - "5231:5231"

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver
    restart: always

_Error code_:
"Firefox is unable to connect to the server on xxx.xxx.x.xxx:5231" [I have also tried with localhost without luck :(]

**Comment by gprst** [comment]
This is probably because the docker image `machies/filestash` from dockerhub is built for the amd64 architecture, and the Raspberry Pi is on an arm64 architecture :)

[My own Docker image](https://hub.docker.com/r/gprst/filestash), created 10 months ago, is built for the arm64 architecture. You could also create your own, if you wished.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
