### ISSUE TITLE
[bug] crypto/aes invalid key size 8

### ISSUE THREAD

**Issue by pabmac** [mickael-kerjean/filestash#384]
When I want to sign in on my page, it tells me the following error: crypto / aes invalid key size 8.
No changes have been implemented in the development of the system for three months and two days ago that indicates the aforementioned error

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
