### ISSUE TITLE
[bug] 502 Bad Gateway on site

### ISSUE THREAD

**Issue by Maks-gaming** [mickael-kerjean/filestash#385]
most of pages:
![image](https://user-images.githubusercontent.com/77161824/113185733-7eb0da80-925f-11eb-9182-9ad45cb2b051.png)

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
