### ISSUE TITLE
[Feature Request] Read-only access via SFTP

### ISSUE THREAD

**Issue by nikhilweee** [mickael-kerjean/filestash#386]
Hi! Thank you for developing this amazing project! Since filestash already allows sharing **read-only** permissons via the share button, is it possible to achieve the same functionality while logging in to a regular SFTP server? In particular, I'm asking about read-only access instead of the default read-write access by default. I know this might not be everyone's cup of tea, so just a few pointers on how to do this would be helpful.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
