### ISSUE TITLE
[bug] symbolic links: files are displayed as folders, not accessable

### ISSUE THREAD

**Issue by heavygale** [mickael-kerjean/filestash#387]
The file listing displays symbolic link files as folders and it's not possible to access them.

- observed behavior: Instead of the linked file a folder is displayed. It's not accessable (error: "Unknown Path").
- expected behavior: The linked file is displayed the same way as the original file or refers to it.

![grafik](https://user-images.githubusercontent.com/5744732/113335892-dfa2e600-9325-11eb-9e9c-4be1560e3779.png)

only tested unsing a SFTP connection
latest docker image (Filestash v0.4rc)

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
