### ISSUE TITLE
[bug] 403 error on Dropbox auth request

### ISSUE THREAD

**Issue by ryanpcmcquen** [mickael-kerjean/filestash#390]
Using a self hosted instance of Filestash, I receive the following error on `/api/session/auth/dropbox`:

```
{"status":"error","message":"Not Allowed"}
```

With a status of: `403 Forbidden`

I have a Dropbox app configured and the `DROPBOX_CLIENT_ID` is set inside the `docker-compose.yml`.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
