### ISSUE TITLE
SFTP - Canot connect using sshkey

### ISSUE THREAD

**Issue by remiOdite** [mickael-kerjean/filestash#391]
Hi,

I'd like to connect to my SFTP server using a password and an hostkey.

I set up the SFTP interface to ask for username/password and hostkey without passphrase.

When I try to connect to my sftp, I get this error :

> {
> 	"status": "error",
> 	"message": "Invalid account"
> }

Filestash is trying to do :

> POST https://xxxxx.com/api/session
> 400 Bad Request

I have another sftp server, without hostkey, it works perfectly. For this one, I succedd to connect using command line or filezilla, not using filestash.

Thanks in advance !
Regards

**Comment by Dynych** [comment]
I have the same problem.

**Comment by mickael-kerjean** [comment]
The issue ticket system has been closed for a while as I didn't have much time to spare. I have set up a new process for bug/feature/support. I'm closing this ticket to start fresh, if you need assistance, please use the new process
