### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by Jayy001** [mickael-kerjean/filestash#423]
# Description of the bug

When trying to upload any file to my S3 instance, it gives a 413 error. (The file size is 2 MB)

# Step by step instructions to reproduce the bug

1) Use portainer with docker to run filestash + OnlyOffice as shown in the docker-compose file
2) Setup nginx proxy + SSL to use a domain name with it
3) Keep all the settings as default, add authentication to S3 with the admin password
4) Try to upload any file to any folder 

# Observed behavior

When uploading (via button or drag and drop), it gives this error:

```
<html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.21.3</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```

# Expected behavior

For my file to be uploaded successfully

**Comment by Jayy001** [comment]
If it helps, when I try to upload the file it gives the error but also shows the file being there - then when I go to click the file it just gives `Oops! NoSuchKey: status code: 404, request id: tx00000000000000-00000-0000-<region> host id:`

**Comment by mickael-kerjean** [comment]
The error is generated from nginx, not Filestash. Nginx has some default limits for upload which you can change through `client_max_body_size`. Nginx has a few option by default for timeout, body size which might not fit your needs if you plan to upload large files

**Comment by Jayy001** [comment]
This fixed it - thank you!
