### ISSUE TITLE
[bug] SFTP username is sent in lowercase even if entered with capitals

### ISSUE THREAD

**Issue by jackald** [mickael-kerjean/filestash#426]
# Description of the bug

When connecting to an SFTP account the username entered in the admin panel has capitals however when I try to connect to the backend this fails. Looking at my auth.log on the server the username Filestash is using to connect does not have the capitals I entered in to the username field.

# Step by step instructions to reproduce the bug

Set up a SFTP backend with the username including capitals then. Try using the log in then check the auth.log on your SFTP server and the username used is all in lowercase.

# Can you replicate that error from the demo?

# Observed behavior

Not used the demo how did ask in the Kiwi IRC chat and was asked to raise an issue.

# Expected behavior

To be signed in to the SFTP server.

**Comment by mickael-kerjean** [comment]
This should be address with the commit mentioned above. Let me know if there's any more issues
