### ISSUE TITLE
[bug] CORS error while opening document in OO

### ISSUE THREAD

**Issue by SlavikCA** [mickael-kerjean/filestash#433]
# Description of the bug

When I open the document in OO, I'm getting error in UI: "Unknown error"
And browser console have this message:

> index.html:1 Access to XMLHttpRequest at 'wss://filestash.slavikf.com/onlyoffice/static/cache/files/Pdzc8cHb85bdcBc8dpTb/Editor.bin/Editor.bin?md5=U9Jv5xtuTrlbQUHtr2zngA&expires=1647849885&filename=Editor.bin' from origin 'https://filestash.slavikf.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

# Step by step instructions to reproduce the bug

I created my installation by using docker-compose.yml file of the project and `local` storage

Looking at the Docker logs: no errors.

# Can you replicate that error from the demo?

no, doesn't replicate

**Comment by xadhatter** [comment]
Having the same issue. The error from the console:

```
Access to XMLHttpRequest at 'wss://REDACTED/onlyoffice/static/cache/files/1DbPcHlUbtcQdjbKrdTb/Editor.bin/Editor.bin?md5=8jqjlCdWNtnJyqxPCDwnFg&expires=1650307503&filename=Editor.bin' from origin 'https://REDACTED' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.
```

Screenshot:
![image](https://user-images.githubusercontent.com/3497441/159133162-2adf5884-eafe-4bee-962c-834a9df3950a.png)

**Comment by mickael-kerjean** [comment]
Would be great if someone who can replicate this could create a PR. I personally can't replicate it and it's impossible for me to provide a fix in those conditions
