### ISSUE TITLE
[bug] Unstable SFTP access "invalid account"

### ISSUE THREAD

**Issue by edwyn00** [mickael-kerjean/filestash#457]
# Description of the bug

The current version for SFTP access is unstable, showing the "invalid account" error message when anyone tries to access it from time to time.
Sftp access to the server (in that same period of time) is still available by the command line but not from Filestash Web Interface.
The log error, obtained via Docker-tramp, is the following:
"2022/03/24 15:32:33 DEBUG session::auth 'NewBackend' Invalid account "

The service restores itself automatically after an undefined amount of time.

The private instance is running on a Debian 11 server. Firewalls are not enabled.
No error message is present in Nginx reverse proxy logs.

# Step by step instructions to reproduce the bug
The reason for the bug or how to reproduce it is not clear

**Comment by mickael-kerjean** [comment]
Thank you for creating this, I have never heard about anything like you just describe despite SFTP being used by tons of people. This is what seem to happen:

1. The log is generated from [here](https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_backend_sftp/index.go#L132) meaning  Filestash can't establish a connection with your server.
2. the service restoring itself after an undefined amount of time seems to be the symptom of a caching issue

A gut feel of what's going on is that your connection establishes fine after login, your SFTP connection is cached for reuse by Filestash but somehow something in your network changes and that connection get cut out giving you that error until the cache expires.

Can you say a bit more about how you use Filestash? What SFTP server do you use? What is the network in between Filestash and your SFTP server is made of? Could something get cut out along the way? Is there some VPN somewhere in the chain?

**Comment by edwyn00** [comment]
Thank you for the fast reply.                                                   
                                                                                
We have a docker instance of Filestash on a Debian 11 server, where we set up   
Ngigx reverse proxy following the suggested configuration in the installation   
page.                                                                           
We use VSFTPD for SFTP connections.                                             
No VPN or certificates are involved in the process.

**Comment by w0k3** [comment]
@edwyn00 vsftpd is [not a SFTP server, only FTP(S)](https://www.sftp.net/sftp-vs-ftps). [OpenSSH](https://www.openssh.com/) has a sftp-server, pre-installed on most Linux distributions.

**Comment by mickael-kerjean** [comment]
I would need a way to reproduce this to understand what's going on. Can you share some account I could use that could help?

**Comment by finzzz** [comment]
I'm encountering the same issue.
FYI, the server only accepts ed25519 and hostname is using internal IP address.
I can login with rclone, filezilla, etc. but keeps failing on filestash.
I'm not sure what logs should I provide, since docker logs only says:
```
2022/06/21 08:41:28 HTTP 200 GET    0.3ms /admin/api/session
2022/06/21 08:41:31 HTTP 200 POST    2.7ms /admin/api/config
2022/06/21 08:41:31 HTTP 200 GET    1.5ms /api/config
2022/06/21 08:41:33 HTTP 200 GET    0.3ms /admin/api/session
2022/06/21 08:41:34 HTTP 401 GET    0.2ms /api/session
2022/06/21 08:41:34 HTTP 304 GET    1.3ms /api/backend
2022/06/21 08:41:54 SYST DEBUG session::auth 'NewBackend' Invalid account
2022/06/21 08:41:54 HTTP 400 POST  107.7ms /api/session
2022/06/21 08:42:06 SYST DEBUG session::auth 'NewBackend' Invalid account
2022/06/21 08:42:06 HTTP 400 POST   92.9ms /api/session
```

**Comment by agent188** [comment]
Similar problem

**Comment by jiatern** [comment]
Yes I can share with you the filestash admin credentials with a test user account on my server, however I don't want to post it publicly here. How can I send it to you?

**Comment by mickael-kerjean** [comment]
mickael@kerjean.me

**Comment by jiatern** [comment]
Hi all, just to update that I have found the root cause for my case, where fail2ban has banned the IP address of my filestash instance. I suppose whitelisting the IP and configuring fail2ban properly will mitigate this issue. Thanks.

**Comment by mickael-kerjean** [comment]
That's interesting, I've never seen that before, thank you for keeping me up to date
