### ISSUE TITLE
[bug] OnlyOffice Websocket error

### ISSUE THREAD

**Issue by nuxlight** [mickael-kerjean/filestash#459]
# Description of the bug

Impossible to open file with OnlyOffice instance 

# Step by step instructions to reproduce the bug

Create a simple DOCX or XLS file on your Filestash instance.
Open this file with OnlyOffice and wait the loading proces.
You will see this error popup with the message **unknown error**
![image](https://user-images.githubusercontent.com/2751135/160707763-bdb5bb5c-cdb4-46dd-aa78-75b0b6128d58.png) 

# Can you replicate that error from the demo?

no

# Observed behavior

Not producible on demo instance, but you can see ore data on web socket communication :
![image](https://user-images.githubusercontent.com/2751135/160707884-a9a9f89d-bb71-4277-803f-05fa87bce539.png)

**Comment by nuxlight** [comment]
I have tried to build the project and I don't have this error, I see that docker get a build version that available on this URL [](https://downloads.filestash.app/latest)

**Comment by nuxlight** [comment]
Okay I think I have found the problem, it's due to Traefik behavior...
I have my own OnlyOffice docker service that I was used for my Nextcloud instance and I had configured some specifics parameters on the header : 
```
- "traefik.http.middlewares.onlyoffice-sslheaders.headers.customrequestheaders.X-Forwarded-Proto=https"
- "traefik.http.middlewares.onlyoffice-cors.headers.accessControlAllowOriginList=*"
- "traefik.http.routers.doc-secured.middlewares=onlyoffice-sslheaders,onlyoffice-cors"
```

I saw in the server section in the Golang part that you make the reverse proxy directly on your application.
That work in local mod but with Traefik you can't add the following configuration what I need to make it work.
However, with you configuration, you can't define an external document server, The iframe send all request to your golang reverse proxy, and you can't access to the distant document server api.js file.

That would be great if you can configure an external document server to permit the Traefik reverse proxy :+1:

**Comment by nuxlight** [comment]
I found the solution [here](https://githubhot.com/repo/mickael-kerjean/filestash/issues/355) :)

**Comment by mickael-kerjean** [comment]
cool thanks for this!

**Comment by mickael-kerjean** [comment]
I'm closing as we seem to have a solution but feel free to comment back and we'll reopen

**Comment by ovizii** [comment]
I have a "similar" problem and this is the thread seems related, so I'll post here. Happy to open a new thread, but this seems like a better place.

I used to run filerun + OnlyOffice behind traefik for many years, and I am currently trying to migrate to filestash + OnlyOffice. 

Unfortunately, filestash works but when opening office documents I get:

```
Failed to load resource: the server responded with a status of 404 () /web-apps/apps/api/documents/api.js:1
Refused to execute script from 'https://files.domain.tld/web-apps/apps/api/documents/api.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

Any pointers? Is this something I need to fix with my traefik settings?

**Comment by ovizii** [comment]
Please disregard my last post, I found my own post from 2 years ago: https://github.com/mickael-kerjean/filestash/issues/222#issuecomment-607276633 which was answered by mickael-kerjean which looks like it helped me solve the issue.

**Comment by idunwannagotoschool** [comment]
> I have a "similar" problem and this is the thread seems related, so I'll post here. Happy to open a new thread, but this seems like a better place.
> 
> I used to run filerun + OnlyOffice behind traefik for many years, and I am currently trying to migrate to filestash + OnlyOffice.
> 
> Unfortunately, filestash works but when opening office documents I get:
> 
> ```
> Failed to load resource: the server responded with a status of 404 () /web-apps/apps/api/documents/api.js:1
> Refused to execute script from 'https://files.domain.tld/web-apps/apps/api/documents/api.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
> ```
> 
> Any pointers? Is this something I need to fix with my traefik settings?

@ovizii Can you please kindly share how you solve it? I am facing similar error.

**Comment by ThomasKat** [comment]
@idunwannagotoschool did you ever solve this? I'm stuck at this error message behind the reverse proxy traefik. Thx!
```
Refused to execute script from 'https://filestash.domain.com/web-apps/apps/api/documents/api.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by idunwannagotoschool** [comment]
> @idunwannagotoschool did you ever solve this? I'm stuck at this error message behind the reverse proxy traefik. Thx!
> 
> ```
> Refused to execute script from 'https://filestash.domain.com/web-apps/apps/api/documents/api.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
> ```
Sorry, I also switched and can't remember the exact steps. But even after I resolved the issue, typing on computers sometimes doesn't work and I cannot edit on mobiles.

**Comment by ThomasKat** [comment]
Darn, why is everyone switching away from filestash? ^^ Where to, @idunwannagotoschool ? Thanks for trying anyway!
