### ISSUE TITLE
How to reset admin password?

### ISSUE THREAD

**Issue by jeanpaulrh** [mickael-kerjean/filestash#460]
# Description of the bug

I can't login to admin console anymore.
After a fresh install I went on the welcome screen, but instead of inserting a password I just pressed enter.
Now I cant login to the admin section anymore. I looked into the config.json file and I see there is a secret and I tried to paste that but without luck. It's not a big problem to delete everything and start overm but I would like to know if there is a way to reset the admin password.

**Comment by mickael-kerjean** [comment]
Please follow the github template information this is not the place for support
