### ISSUE TITLE
[bug] Docs pages are down

### ISSUE THREAD

**Issue by YouveGotMeowxy** [mickael-kerjean/filestash#462]
Just a heads up; while trying to find out if Filestash supports docker secrets for things like dropbox/gdrive id's, i got this page:

![image](https://user-images.githubusercontent.com/39491297/161448488-2c7cf1b8-1f34-4176-9973-dca5d671a95b.png)

**Comment by STaRDoGG** [comment]
> Just a heads up; while trying to find out if Filestash supports docker secrets for things like dropbox/gdrive id's, i got this page:

Looks to be fixed.

**Comment by mickael-kerjean** [comment]
it's back online indeed. I used to have a homeserver pinging the website for healthcheck and sending me sms when there's any issue but I move to a new place and haven't setup the server back again :/
