### ISSUE TITLE
[bug] TTY issues

### ISSUE THREAD

**Issue by YouveGotMeowxy** [mickael-kerjean/filestash#463]
# Description of the bug

When visiting `/admin/tty/` it just takes me to a rapidly flickering white screen. Damn near game me a seizure. :-p

# Step by step instructions to reproduce the bug

1. Enable Consonle in admin settings
2.  Visit `/admin/tty/`
3. Try not to seize. lol

# Can you replicate that error from the demo?

# Observed behavior

Also shows this error in the browser tools:

![image](https://user-images.githubusercontent.com/39491297/161686123-7c88bbfa-5716-4696-97ab-1ceeea63b01e.png)

# Expected behavior

A usable console.

Also as an aside, i think updating the description for enabling the console to say it'll be available at `/admin/tty/` instead of just `/tty/` would help out. I was originally thinking that it meant it would be available at  `https://filestash.my.domain.com/tty/`.

Maybe even jsut add an actual link that opens in a new tab, such as:

> Enable/Disable the interactive web console on your instance. It will be available under [/admin/tty/](https://filestash.my.domain.com/admin/tty/) where username is 'admin' and password is your admin console

**Comment by r4v10l1** [comment]
#461

**Comment by mickael-kerjean** [comment]
> /admin/tty/

done in https://github.com/mickael-kerjean/filestash/commit/84aaea40086f52f25b9275ef49f4510a1800f920

> Try not to seize. lol

Oops, what's going on is I thought it would be a good idea to restart the page if something was to go wrong in the websocket and the underlying library version as been causing issue with the particular version we use for go, hence that scary flickering.

Both that restart behaviour and feature has been updated in https://github.com/mickael-kerjean/filestash/commit/84aaea40086f52f25b9275ef49f4510a1800f920

**Comment by mickael-kerjean** [comment]
I'm closing this as it's solved. If something isn't working right, feel free to comment and we'll reopen

**Comment by YouveGotMeowxy** [comment]
Thank you :)

How about "beefing" this feature up a little, and when the console option is enabled, add a "Console" link to the menu at the left, for easy access (and remove it when disabled)?

As it is, we have to either bookmark the URL to the console, or manually type it in, or drag the text to another tab, and type the URL. One of the main reasons for this app is to simplify life for us (by placing all clouds in 1 spot), so it would make sense to also simplify our lives by adding a link to the console. :)

Same when SyncThing is en/disabled.

p.s. This page ([#8](https://www.filestash.app/docs/tips-and-tricks/)) hasn't been updated with the new `/admin/tty/` info. (I only happened to notice it while trying to dig up some info on using multiple DropBox/Goodle Drive users; and also trying to see if I can disable the admin password)
