### ISSUE TITLE
[bug] (?) Odd behavior when used in Organizr

### ISSUE THREAD

**Issue by YouveGotMeowxy** [mickael-kerjean/filestash#464]
# Description of the bug

When using inside of [Organizr](https://github.com/causefx/organizr) (added as an iframe) there's no longer any Logout button, or "frequently accessed folders" area.

# Step by step instructions to reproduce the bug

1. Add FS to organizr as an iframe:

![image](https://user-images.githubusercontent.com/39491297/161859174-932e4c65-0021-40cd-b592-b9ba8fa6b55d.png)

2. login to something with FS. In my case I was already logged into a mysql instance.
3. Visit the FS tab within Organizr

# Observed behavior

No logout button (makes switching things to use within FS impossible from within Organizr), nor a  frequently  accessed area.

Screenshots:

NOT from within Organizr:
![image](https://user-images.githubusercontent.com/39491297/161859840-618c63a9-1f21-4d87-b65b-eb4db4b19673.png)

WITHIN Organizr:
![image](https://user-images.githubusercontent.com/39491297/161859904-6509f883-8e96-4219-839b-4428fe670dd2.png)

# Expected behavior

To still be able to use FS's logout button and frequent accessed area.

I'm wondering if maybe this is all due to perhaps both Organizr and FS using the same CSS classes or IDs? Just thinking outloud since I haven't looked.

**Comment by mickael-kerjean** [comment]
This is actually a feature. The reasoning is most people who embed the application somewhere do so from the point of view of sharing things on their website for others to see. In that sense, having a logout button doesn't make sense and so is the frequently access folders. Using something like Organizr breaks that initial assumption
