### ISSUE TITLE
[bug] Oops! BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint '' status code: 301, request id: , host id:

### ISSUE THREAD

**Issue by devdream02** [mickael-kerjean/filestash#465]
# Description of the bug

Getting below error when i trying to access a s3 bucket which i have access to
Oops!
BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint '' status code: 301, request id: , host id:
# Step by step instructions to reproduce the bug

Tried passing region as well but no luck. Am i missing something here?

# Can you replicate that error from the demo? yes

# Observed behavior

# Expected behavior

**Comment by mickael-kerjean** [comment]
By default the region is us-east-1 but you have an option to select the region your bucket is in. S3 is picky on that kind of things

**Comment by mpreynolds** [comment]
I'm also having this same issue. I enter the region as ap-southeast-2 but the console error still says the bucket is not in 'us-east-1'.

**Comment by Oterem** [comment]
@mickael-kerjean I have selected the correct region in the dropdown. it seems like the server doesn't pick up the region param and just using the default/fallback value

**Comment by mickael-kerjean** [comment]
Can you send me a testing account from which I can replicate the issue you are facing?

**Comment by mickael-kerjean** [comment]
I'm closing this as we have 2 tickets describing the same issue #493
If someone can send a testing account I will dig onto it
