### ISSUE TITLE
[Feature Request] WHY??? -- >DO NOT CREATE A FEATURE REQUEST FROM GITHUB - USE IRC INSTEAD

### ISSUE THREAD

**Issue by valschmidt** [mickael-kerjean/filestash#467]
It is not clear to me why one would push feature request discussions to a IRC which is less visible and has no history. It removes the ability for folks to collaborate and for developers to get a sense of the pressing things that everyone needs because folks can't easily read the discussion, register their ideas and support for a new feature. Any chance you'd consider removing this guidance and allowing a more public discussion to flourish around the cool things filestash might some day do?

**Comment by mickael-kerjean** [comment]
the IRC history is archived and is searchable. With this in mind, it's a matter of preference, I like standard protocol like IRC more than github proprietary system. Sure things could be greatly improved but it's a matter of priority considering this doesn't pay my bills. 

As of today, I want to put more time torward the code avoiding the trap which would consist in spreading attention everywhere but going nowhere as a result. If I'm ever able to make a living out of this, I will make it my life mission to create an awesome place for collaboration but so far this project is a massive time sink that's only the result of a labour of love and I can't afford to spend more time on things that would distract from the primary objective which is code

**Comment by Happyrobot33** [comment]
I honestly second this, as there doesnt actually appear to be any history system to the IRC chat (history isnt even a part of how IRC works) and it makes tracking commits to implement things more obscure as they cant be linked to any feature requests on github itself.

**Comment by mickael-kerjean** [comment]
> any history system to the IRC chat (history isnt even a part of how IRC works)

There's an IRC bot which make the history searchable, the links are in the IRC banner
