### ISSUE TITLE
[bug] Video player times-out on large video files.

### ISSUE THREAD

**Issue by valschmidt** [mickael-kerjean/filestash#468]
# Description of the bug
Video player times-out on large video files.

# Step by step instructions to reproduce the bug
Attempt to play a video file several GB in size. (.mov or mp4)
Works fine with files several 10's of MB in size.

# Can you replicate that error from the demo?
Have not tried.

# Observed behavior
Spinning icon for several minutes followed by error - "The media could not be loaded, either because the server or network failed or because the format is not supported."

# Expected behavior
Video should stream from S3 bucket 

# Questions:
Are the video files downloaded in the background to the server running filestash and then streamed to the user? Could the player just be timing out while such a large file is downloaded?

**Comment by mickael-kerjean** [comment]
streaming a large video in real time isn't trivial. It would be great to support this via a PR. Can you work something like this out?
