### ISSUE TITLE
[bug] Filestash: cannot load webdav from iframe

### ISSUE THREAD

**Issue by xhildashazivari** [mickael-kerjean/filestash#469]
# Description of the bug

I am trying to load Webdav from Filestash with iframe, but I get 

`{"status":"error","message":"Not authorised"}`

# Step by step instructions to reproduce the bug

I tried adding the URL in iframe parameters from the admin console, still not working.

# Can you replicate that error from the demo?

# Observed behavior

# Expected behavior

**Comment by mickael-kerjean** [comment]
I've added a few other commit that relates to this, namely https://github.com/mickael-kerjean/filestash/commit/b9279fa77f52e3be7d676cc887a5c2ef4c69e558  https://github.com/mickael-kerjean/filestash/commit/b3762eff6a3f94c1f88ee4cd9a51d089fd799800 and https://github.com/mickael-kerjean/filestash/commit/629a80c83625f75b786bae4e5a132d47b02fe7e5

The release has gone through, you should be able to pull the latest and call it a day. Let me know how this goes.

**Comment by xhildashazivari** [comment]
It works great! 
Thanks a lot!
