### ISSUE TITLE
[bug] Unable to build data connection / Link to file server lost

### ISSUE THREAD

**Issue by iandk** [mickael-kerjean/filestash#470]
# Description of the bug

Creating files fails with the error:
`SYST DEBUG touch::backend 'unexpected response: 425-Unable to build data connection: Operation not permitted'`

And uploading files:
`SYST DEBUG save::backend 'unexpected response: 450-Transfer aborted. Link to file server lost (can't resume)'`

# Step by step instructions to reproduce the bug
Deploy file stash as docker container, connect to ftp server.
And try to create a file or upload one

# Can you replicate that error from the demo?
Yes, same error

# Observed behavior
Uploading/ creating a file fails with the above mentioned error message, however the file will get created anyway.

# Expected behavior
No error message

**Comment by mickael-kerjean** [comment]
Can you setup your proftpd with the following setting:
``` 
TLSOptions NoSessionReuseRequired
```
and let me know how this goes?

**Comment by iandk** [comment]
Hi, 

Thanks!

But that’s already part of the configuration.

Ian

**Comment by iandk** [comment]
Hi, 

Were you able to find the issue or can I do anything to help you with it?
Unfortunately I’m still experiencing the same problem.


Kind regards
Ian

**Comment by danielsawan** [comment]
Hello,

I’d like to report that this bug is still present in the current version. Despite applying the recommended settings, I continue to encounter the following errors when creating a file:

```
SYST DEBUG touch::backend 'unexpected response: 425-Unable to build data connection: Operation not permitted'
HTTP 500 POST 1762.5ms /api/files/touch?path=%2Frgrgr
```

The behavior remains the same as previously described, and the issue hasn’t been resolved with the proposed solutions. If needed, I can provide a testing environment to help investigate and fix this bug.

Thank you for your attention and assistance.  

Best regards,

**Comment by mickael-kerjean** [comment]
A testing environment would be great indeed: mickael@kerjean.me

**Comment by danielsawan** [comment]
The issue occurs only when Filestash attempts to connect to an FTP server using TLS. Without TLS, everything works perfectly. I have sent you an email with all the necessary details to access a development VPS, where ProFTPD is configured with TLS and Filestash. The connection information is provided in that email.
