### ISSUE TITLE
Easier way to delete files?

### ISSUE THREAD

**Issue by patrickbolle** [mickael-kerjean/filestash#471]
Hi! Great app. Working perfectly on my server.

Wondering if there is a shortcut or anything to make deleting files easier? I'm working through organizing and deleting old files via Filestash.

Right now it seems the only way is via Grid view and clicking the garbage icon, and then typing out the file name.

It makes it a pain to delete more than a few images.

Any keyboard shortcut available, or a way to reduce the effort it takes currently to delete files?

Thanks!

**Comment by brlarini** [comment]
+1 on this.

I know if you hold Ctrl key you can select multiple files, but I didn't find a way to delete them all at once.
Managing files on a browser should be the same way that we're used to do on desktop. I feel there should be an option to change the behaviour of the single click: click once to select and double click to open the file/folder.
And another option to change the confirm deletion, from needing to type the file name to a Yes/No choice.
Look how [Filebrowser](https://github.com/filebrowser/filebrowser/) does it: 
[https://user-images.githubusercontent.com/5447088/50716739-ebd26700-107a-11e9-9817-14230c53efd2.gif](https://user-images.githubusercontent.com/5447088/50716739-ebd26700-107a-11e9-9817-14230c53efd2.gif)
