### ISSUE TITLE
Unable to start filestash

### ISSUE THREAD

**Issue by tapashdatta** [mickael-kerjean/filestash#472]
I am following the installation guide on github.
All seems to be installed correctly. But the container is not connected to the port 8334.
I am unable to even start the container with the port.
Any help please? Thanks
<img width="650" alt="Screenshot 2022-04-30 at 17 35 45" src="https://user-images.githubusercontent.com/5366545/166104814-924634a7-8929-4536-a522-99c85914cb96.png">
<img width="650" alt="Screenshot 2022-04-30 at 17 33 55" src="https://user-images.githubusercontent.com/5366545/166104818-f51e4c4e-c92b-4035-a7ff-b35ead566c85.png">

**Comment by mickael-kerjean** [comment]
Please don't ignore the rule when creating a ticket, we don't use github as a support platform, feel free to use IRC for this
