### ISSUE TITLE
[bug] [typo] "Frequently access folders will be shown here" -> "Frequently accessed folders will be shown here"

### ISSUE THREAD

**Issue by Zorlin** [mickael-kerjean/filestash#475]
# Description of the bug

There is a minor typo/grammatical issue with the app, it says "Frequently access folders will be shown here" but should read "Frequently accessed folders will be shown here" instead.

# Step by step instructions to reproduce the bug

* Install, run

**Comment by Zorlin** [comment]
Not stale, thanks @stale

**Comment by Zorlin** [comment]
Not complete :( please fix

**Comment by andylinton** [comment]
Confirming that this typo still exists - please change to "frequently accessed"... instead of "frequently access"...
