### ISSUE TITLE
[bug] Selecting / Downloading not intuitive on desktop / mobile

### ISSUE THREAD

**Issue by coxtor** [mickael-kerjean/filestash#478]
# Description of the bug
On mobile devices it is impossible to download anything as selecting folders is not possible currently. Also making the download / zip function appear on desktop is not intuitive as it is not apparent that a selection can be made at all.

**Comment by mickael-kerjean** [comment]
There's a plan to change how this work and revamp it so that one click is to select a folder, 2 click is to navigate through like what you see commonly on mac finder and window explorer. Can you help with this? I just had a newborn and I'm not sure when I will be able to save time to do this
