### ISSUE TITLE
[bug] Full-text search option missing

### ISSUE THREAD

**Issue by dinkonin** [mickael-kerjean/filestash#479]
Using the latest docker-image I noticed that the full-text search option is missing...

Maybe `plg_search_sqlitefts` should be added to https://github.com/mickael-kerjean/filestash/blob/573fb9be28ec1bf88a2a0836cab5a80d56b36432/server/plugin/index.go#L28

or is this feature depracated ?

**Comment by mickael-kerjean** [comment]
No the plugin is available here: https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_search_sqlitefts

What has changed is that we made search available via plugin so you can extend the search to plug anything you want like elastic search, solr, ...

**Comment by dinkonin** [comment]
I still don't see a way of using it other than recompiling filestash and building a new docker container. What am I missing ?

**Comment by Timon-Schneider** [comment]
I installed Filestash for the sole reason that it supposedly supports Full-Text Search. The website and documentation says everywhere "You can enable full-text search via the admin console". This is apparently no longer true and nowhere is it written how to enable this feature. Very confusing. What do I need to do?

**Comment by mickael-kerjean** [comment]
Hello,

We've made search available as a plugin so people can plug whatever
they want. The idea being you can either use one we have or create your
own. The code for the full text search is still available
 ( https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_search_sqlitefts
), you simply need to recompile the software to get it back

Cheers,

Mickael
