### ISSUE TITLE
[bug] Passwords in config.json are plain text

### ISSUE THREAD

**Issue by YouveGotMeowxy** [mickael-kerjean/filestash#482]
# Description of the bug

1. Enter any password into the UI (i.e. Email password, or MySQL password)
2. Open up config.json and there they are in plain text

# Can you replicate that error from the demo?

Haven't tried; probably don't have access to it's config.json

# Observed behavior

Passes are in plain text. (Bad security practice)

# Expected behavior

Passes _not_ in plain text. (They should be encrypted in the file and decoded as needed.)

**Comment by mickael-kerjean** [comment]
I'm not sure what you mean, password in Filestash are stored using bcrypt. Also config.json is just one example of config storage, this can be change via the plugin mechanism (see [here](https://github.com/mickael-kerjean/filestash/blob/master/server/common/config_state.go#L8-L13)) to store config in any medium you want with any kind of encryption you want. config.json is just the default storage mechanism

**Comment by mickael-kerjean** [comment]
I'm closing as I don't see any action on my side. Feel free to comment if you think we should reopen

**Comment by STaRDoGG** [comment]
I'm seeing this as well. 

It's pretty easy to see in a quick test; just add a sFTP, fill it out, including the password,. then look at the `config.json`. Right in that new sftp connection's `"password":` key it shows the unencrypted password as it's value.

I could make a video of it if needed.

**Comment by mickael-kerjean** [comment]
I made 9a98da79782db460647b82132bd94ce6a0db6c1b after seeing the various reaction. From now on, if you set the CONFIG_SECRET env variable to something, the config.json will be encrypted (using aes gcm) without needing an extra plugin

**Comment by mickael-kerjean** [comment]
Yes that would make for a very nice PR

**Comment by YouveGotMeowxy** [comment]
> Yes that would make for a very nice PR.

lol, ok, give me 5 mins. to learn Go from scratch, and then the entire flow of the program, and I'll submit a PR to encrypt a string. :)
