### ISSUE TITLE
Do you support the creation of custom user ?

### ISSUE THREAD

**Issue by L1so** [mickael-kerjean/filestash#485]
Hello, I just installed this app on my box, looking great with all the customization !

I have one question though, is it possible to add new user to access certain protocol ? I have set up new s3 browser in filestash, but I want to share access to my coworker, it says `unlimited users` on https://www.filestash.app/pricing/ makes me think there exist settings to add new user. If it's there, I haven't found it yet then.

I'm planning to assign this user to my already set up S3 browser in filestash, currently it only accepts admin credentials which I obviously don't want to share.

This is a picture when I visit my filestash instance, I wish to add new field for user input.
![Screenshot 2022-06-15 at 12-57-42](https://user-images.githubusercontent.com/44594524/173754062-92fd91ee-bab9-4e25-a030-627879075924.png)

Thanks !

**Comment by mickael-kerjean** [comment]
For the admin area, there's no concept of user, only an admin password to protect the configuration of the instance. 

On the end user side there's 2 different idea of users:
1. the users as setup in your storage backend, in your case that would be the various access key you can setup via IAM for S3
2. a Filestash construct of users that is available via the authentication middleware section of the admin console. We do have various plugin available to connect to existing source of users like LDAP, SAML, OpenID or we can create custom plugin that work for your needs. A simple exemple of such plugin if you want to create your own is the admin one: https://github.com/mickael-kerjean/filestash/blob/master/server/plugin/plg_authenticate_admin/index.go
