### ISSUE TITLE
[bug] docker permission denied

### ISSUE THREAD

**Issue by itorz7** [mickael-kerjean/filestash#489]
![image](https://user-images.githubusercontent.com/30155968/175264293-5a91866a-373e-451e-9981-5c65c2fbd789.png)
![image](https://user-images.githubusercontent.com/30155968/175264607-247b6839-0650-40da-b53f-5399c49c4892.png)

my docker-compose.yml
![image](https://user-images.githubusercontent.com/30155968/175264413-53bd8a92-4800-4cbb-a3a6-ec7a2ce82077.png)

**Comment by mickael-kerjean** [comment]
Filestash needs to create/edit the file that exist in the state directory. In practice, this means you need to:
```
chown -R 1000:1000 ./state/
```
from the location of your docker-compose.yml

**Comment by mickael-kerjean** [comment]
I'm closing as it seems to be solved. I've link this ticket from the faq so if someone google this, the answer should be easier to find. If you think we shouldn't close, feel free to comment back and I'll reopen

**Comment by MeiRos** [comment]
I'm running this with rootless podman-compose and I can't make this work by using 'chown -R 1000:1000 ./state/'. (Path is changed to my path.) Podman cp did already a copy with the same owner/user (1000:1000) as the user running podman-compose. In the container the state directory is owned by root:root. Others are filestash:filestash. Could everything be filestash: filestash?
Or is the problem somewhere else and I don't understand it..?
