### ISSUE TITLE
[bug] Cannot download non-standard extension files

### ISSUE THREAD

**Issue by Bllacky** [mickael-kerjean/filestash#491]
The issue I have is rather simple:
I have a multipart archive:
test.zip
test.z01

I can download test.zip without an issue, but I cannot download test.z01.
If I click on the test.z01 file I get the spinning/loading animation forever and the "Download" button never appears.
If I rename the test.z01 file to test.z01.zip , then everything works fine.

I am using the docker version of filestash.

Issue is present with the latest version of Firefox (101) and Chrome (103). 

What I am doing wrong?

**Comment by Bllacky** [comment]
Thanks! I will close this issue. However, I am going to suggest that instead of this plugin, maybe in the future you can enable a toggle button in the admin console that makes all files "downloadable".

**Comment by mickael-kerjean** [comment]
good idea
