### ISSUE TITLE
[bug] S3 login doesn't support use aws keys on specific path

### ISSUE THREAD

**Issue by Oterem** [mickael-kerjean/filestash#494]
# Description of the bug

I've created an STS credentials using aws assume role against a policy on a specific path (myBucket/folder1).
when providing the credentials with full path I'm getting an "invalid account" error.

# Step by step instructions to reproduce the bug

1. create aws keys against a policy with entitlement on a specific s3 path.
2. insert credentials to the client
3. specify full path (like /bucket/folder1)
4. try to login

<img width="1135" alt="Screen Shot 2022-07-11 at 20 37 44" src="https://user-images.githubusercontent.com/26056415/178324454-647e4918-bd37-4835-a650-d68961c7a5c8.png">

# Can you replicate that error from the demo?

# Observed behavior

# Expected behavior

**Comment by spwoodcock** [comment]
I just wanted to add a note here, for anyone else looking into this.

I don't think the issue was solved per-se. The IAM user for the access/secret key must have permission `s3:ListAllMyBuckets`, to list all the buckets on the account, so it's not easy to give users access to only one bucket at a time.

This isn't ideal, but it can be worked around with two things:
1. Restrict actual S3 operations to only the bucket you want:
    ```json
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "s3:GetBucketLocation",
                    "s3:ListBucket",
                    "s3:GetObject",
                    "s3:PutObject",
                    "s3:DeleteObject"
                ],
                "Resource": [
                    "arn:aws:s3:::the-name-of-your-s3-bucket",
                    "arn:aws:s3:::the-name-of-your-s3-bucket/*"
                ]
            },
            {
                "Effect": "Allow",
                "Action": "s3:ListAllMyBuckets",
                "Resource": "*"
            }
        ]
    }
    ```
2. Click 'Advanced options', then update the endpoint to point to the specific S3 bucket only:
    `https://the-name-of-your-bucket.s3.amazonaws.com/`
    This will ensure the user goes straight to the root of the bucket at login, instead of showing a list of all available bucket.

Awesome project by the way 🎉

**Comment by spwoodcock** [comment]
Actually ignore what I wrote above. The connection works, and creating a new folder 'works', but when you click on the folder there is an error...

Presumably having an endpoint like `https://the-name-of-your-bucket.s3.amazonaws.com` causes the paths to be messed up. Even using `https://s3.amazonaws.com/the-name-of-your-bucket` also works for connecting to the bucket, and creating new folders, but then entering folders and uploading data fails.
