### ISSUE TITLE
[bug] cannot build with current node version

### ISSUE THREAD

**Issue by qwerty287** [mickael-kerjean/filestash#496]
# Description of the bug

I can't build the frontend with a current node version (node v18.7.0 with npm 8.15.1).

# Step by step instructions to reproduce the bug

Install or update to node 18 and try to run `npm install`.

# Can you replicate that error from the demo?

No, because I don't compile it there.

# Observed behavior

1. Running `npm install` fails due to peer dependency issues. I solved this by using `npm install --force`
2. Using this fails at another point, when `node-sass` is compiled. This is an issue of node-sass with the current node version. You should migrate to dart-sass (NPM package `sass`). I tried to migrate this, and I also tried to update various dependencies (you should update webpack to v5), but it fails. I didn't investigated here that much.

# Expected behavior

It runs without errors, similar to what the CI does. The CI uses node 13, which is [end of life for 2 years now](https://endoflife.date/nodejs). You should update this project and the package.json files / dependencies to be compatible with all currently supported Node/NPM versions (as of writing this, these are 14, 16 and 18).

**Comment by JoshuaCrewe** [comment]
I noticed this as well. To get it working I used https://github.com/nodenv/nodenv (which is excellent) to set the environment to Node 13. This resulted in a successful build without too many issues if I remember correctly. `npm install --force` didn't work for me.

Node Sass is a real pain, I will say that. Seeing as updating everything to the latest versions didn't work it is possible that one of the packages is not being maintained any more which might take some time to fix/replace. @qwerty287 were you able to isolate the issue any more than when you created this issue? I might get some time to have a look this week :crossed_fingers:

**Comment by JoshuaCrewe** [comment]
beautiful. Thanks for the guidance. I will take a look and see how far we can get.

**Comment by JoshuaCrewe** [comment]
Stalebot is super keen. It was too much for me to see this one through at the moment. Probably should get done one day but it isn't a super fun one to do so I understand why it wouldn't!

**Comment by mickael-kerjean** [comment]
being able to create a build against every possible node version isn't really in the roadmap, there's only so much I can do on my own. If someone wants to see which version works, we've complete the migration of CI to github action so you can use that as a reference
