### ISSUE TITLE
[bug] Can't list LDAP

### ISSUE THREAD

**Issue by mfominov** [mickael-kerjean/filestash#500]
I've configured LDAP, and now see debug error
```
2022/08/26 07:16:14 SYST DEBUG session::auth 'NewBackend' LDAP Result Code 200 "Network Error": dial tcp :389: connect: connection refused
```
by telnet work's fine
And "LDAP examples" from https://www.filestash.app/ldap-browser.html also does not work...

**Comment by mickael-kerjean** [comment]
It's back again

**Comment by mfominov** [comment]
It works.
