### ISSUE TITLE
[bug] Clear text ldap password in payload

### ISSUE THREAD

**Issue by mfominov** [mickael-kerjean/filestash#501]
It's kind a strange thing by in request http://localhost:8334/api/session i can see plain text payload with ldap plain text password.
```
{
    "type": "ldap",
    "hostname": "ldap://ldap-server",
    "bind_dn": "bind_user",
    "bind_password": "bind_user_password",
    "base_dn": "search_base",
    "path": null,
    "port": null
}
```
is it ok?

**Comment by mickael-kerjean** [comment]
Please create another ticket but without ignoring the bug template we have setup, thanks!
