### ISSUE TITLE
[poll] documenting the API 

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/filestash#503]
50 :+1: and I will:

1. write documentation for the API
2. make enhancement to make the API a breeze to work with

**Comment by scoobyd0027** [comment]
Hi @mickael-kerjean, were you able to document any of the APIs yet? Do you have any suggestions on what code to reference for to use those APIs, if they are available? The main API I was looking for is how to get a link for viewing individual files

**Comment by mickael-kerjean** [comment]
I have started a few days ago, wip at this stage

**Comment by mickael-kerjean** [comment]
the first batch of the doc: https://www.filestash.app/docs/api/
more will be coming

**Comment by scoobyd0027** [comment]
that is awesome @mickael-kerjean, thank you!
