### ISSUE TITLE
[bug] Plain text with ldap password in payload

### ISSUE THREAD

**Issue by mfominov** [mickael-kerjean/filestash#504]
# Description of the bug

Plain text with ldap password in payload

# Step by step instructions to reproduce the bug

On request http://localhost:8334/api/session i can see plain text payload with ldap plain text password.
```
{
    "type": "ldap",
    "hostname": "ldap://ldap-server",
    "bind_dn": "bind_user",
    "bind_password": "bind_user_password",
    "base_dn": "search_base",
    "path": null,
    "port": null
}
```

# Can you replicate that error from the demo?

no.

# Observed behavior

# Expected behavior

no plaintext ldap password in payload

**Comment by mickael-kerjean** [comment]
I'm not sure to understand what you're saying here. How could Filestash know what to connect and how to do so if you weren't transmitting anything? There's already a bunch of warning after installation to warn against using plain HTTP and use HTTPS instead

**Comment by mfominov** [comment]
I've configured ldap connection in admin panel/console.
Then i've opened user ui connect to ldap and see payload of ldap connection with plain text data.

**Comment by mickael-kerjean** [comment]
yes and that's the reason why everyone recommend using HTTPS as it wouldn't be safe to use HTTP on something where you transmit anything that should stay a secret. Every website behind some sort of login behave like this, I fail to see what you think is a bug

**Comment by mfominov** [comment]
ok.
Before i start of using something, i've make localhost test without any revers proxy with ssl termination.
