### ISSUE TITLE
[bug] wrongly determine traditional Chinese as simplified Chinese

### ISSUE THREAD

**Issue by changchichung** [mickael-kerjean/filestash#508]
### Description of the bug
browser language has already configured as traditional Chinese  , but filestash still show simplified Chinese chars

### Can you replicate that error from the demo?
yes

browser language settings 
![](https://i.imgur.com/LpnghWr.png)

filestash frontend shows simplified Chinese
![](https://i.imgur.com/AKuR8h6.png)

maybe it's a good idea to add language option in config.json ?

**Comment by mickael-kerjean** [comment]
As I'm not familiar with Chinese at all, can you say if that would work:
- zh_tw: traditional chinese will see this: https://github.com/mickael-kerjean/filestash/blob/master/client/locales/zh_tw.json
- zh_*: will see this: https://github.com/mickael-kerjean/filestash/blob/master/client/locales/zh.json

**Comment by changchichung** [comment]
yes , that's correct !
and also it would be nicer to distinguish traditional Chinese ( zh_tw ) and simplified Chinese  ( zh_cn ) to respect ISO-3166-1

**Comment by mickael-kerjean** [comment]
Do you confirm the fix above fix this issue? A live version is available from https://demo.filestash.app

**Comment by changchichung** [comment]
No , it's the same as before.
![](https://i.imgur.com/cLPUQ7i.png)

**Comment by mickael-kerjean** [comment]
What do you get when you execute "navigator.language" from the developer console?

**Comment by changchichung** [comment]
zh-TW
![](https://i.imgur.com/fwYqkwq.png)

**Comment by mickael-kerjean** [comment]
What about now?

**Comment by mickael-kerjean** [comment]
Awesome. I'm closing as it seems solve but feel free to comment back and I'll reopen
