### ISSUE TITLE
[bug] .pdf, .pptx, .mp4, .docx files are shown as folders 🐛

### ISSUE THREAD

**Issue by andrewpap22** [mickael-kerjean/filestash#510]
First of all, hello and thank you for this project! 

We have the following issue with @Learus 

# Description of the bug

As the title says, those files are shown as directories on the main Frontend screen (1) and when you click on them an error occurs (2) and there is no preview of those files or download. 

By searching the particular files in the search box on the top right, the issue gets fixed and they correctly are being displayed as files and you can preview them or download. (3)

Attaching screenshots with the corresponding numbers:

(1): 
![pic-selected-220914-1310-12](https://user-images.githubusercontent.com/68736032/190126877-dc8d069a-96da-475a-a782-8aac9d8f187b.png)

(2): 
![pic-selected-220914-1312-49](https://user-images.githubusercontent.com/68736032/190127260-dcffe49a-6ab0-4cf4-b996-fab4b2af7e2a.png)

(3): 
![pic-selected-220914-1314-43](https://user-images.githubusercontent.com/68736032/190127640-59920266-d52c-4e2b-ac6c-e3d0983942a0.png)

# Step by step instructions to reproduce the bug

Connect to a fileserver via Samba and upload files with the mentioned extensions.

# Can you replicate that error from the demo?

No, because our file server has no exposed public IP outside of our network, to connect via the demo.

**Comment by mickael-kerjean** [comment]
If someone can made a PR for this that would be awesome, I don't have an environment ready on my side where I can replicate this.

**Comment by mickael-kerjean** [comment]
There's no action pending on our side so I'm closing this. Feel free to comment back and we'll reopen
