### ISSUE TITLE
[bug] Videos not playing

### ISSUE THREAD

**Issue by alanmilinovic** [mickael-kerjean/filestash#522]
Just wondering if anyone managed to play any kind of video? Do I need to install any package in addition?

**Comment by Happyrobot33** [comment]
you might need to install ffmpeg, check the logs with the different log levels when you try to play a video

**Comment by Happyrobot33** [comment]
also depending on the size of the video the transcoding process might take a while

**Comment by alanmilinovic** [comment]
```
ffmpeg:
  Installed: 10:4.4.3-dmo0+deb11u3
  Candidate: 10:4.4.3-dmo0+deb11u3
```

```
video.mkv
Video Player is loading.This is a modal window.audio append of 458147b failed for segment #0 in playlist 0-http://1nuc.mooo.com:20534/api/files/cat?path=%2Fhome%video.mkv&transcode=hls
```

**Comment by alanmilinovic** [comment]
I am using ffmpeg a lot, only with filestash I have issues. Maybe because I installed it without docker, I used alternative method for debian.

**Comment by Happyrobot33** [comment]
I dont think mkv is actually supported at the moment

**Comment by Happyrobot33** [comment]
never mind im wrong it is supported

**Comment by alanmilinovic** [comment]
I tried small avi files as well.

**Comment by alanmilinovic** [comment]
Ok, so I switched to docker installation and same behavior. But some videos are now playable and some not. The one that is not working is throwing this audio error:

`This is a modal window.audio append of 458147b failed for segment #0 in playlist 0-http://1nuc.mooo.com:20534/api/files/cat?path=%2Fhome%video.mkv&transcode=hls`

Any idea?

**Comment by mickael-kerjean** [comment]
Can you share a sample file that you have problem with?

**Comment by alanmilinovic** [comment]
> Can you share one of those video you have problem with?

Sure: http://1nuc.mooo.com:20534/s/video_test

**Comment by alanmilinovic** [comment]
Any news on this?

**Comment by mickael-kerjean** [comment]
Not yet, I'm quite busy and can't afford to work full time of this

**Comment by alanmilinovic** [comment]
> Not yet, I'm quite busy and can't afford to work full time of this. Hopefully I can take a look in the next few weeks

Sounds good, tnx for info.

**Comment by mickael-kerjean** [comment]
should be working now

**Comment by alanmilinovic** [comment]
I can confirm that it is working! Many tnx.
