### ISSUE TITLE
Question: What is shareID in the API doc https://www.filestash.app/docs/api/ and how to get it?

### ISSUE THREAD

**Issue by scoobyd0027** [mickael-kerjean/filestash#526]
I am trying to get the /api/share?path={path}&key={key}&share={share} endpoint to work with curl, but I was not able to find what shareID is supposed to be and not sure if this API is even enabled, would appreciate your input @mickael-kerjean

**Comment by mickael-kerjean** [comment]
When you create a shared link, it could be in this screen: EYYi1LI
![image](https://user-images.githubusercontent.com/13233076/200099049-cde3ebd7-16cf-40b9-bbdc-edd231948e8f.png)

or you can create a custom "shareID" via
![image](https://user-images.githubusercontent.com/13233076/200099079-b8ba420d-4313-4eee-960a-b8ba690a7ee4.png)
in this case it would be "test"

**Comment by scoobyd0027** [comment]
<img width="1016" alt="Screen Shot 2022-11-04 at 8 40 25 PM" src="https://user-images.githubusercontent.com/43387955/200099276-3916979b-e4ed-4ba9-9757-97f26fefbd44.png">
Yes, I found that UI option, but how can I make this POST call to get the same file share links programmatically by sending a curl to the API

**Comment by mickael-kerjean** [comment]
This part hasn't been revamped yet so you'd need to go through the same command the UI is getting through:
![image](https://user-images.githubusercontent.com/13233076/200274651-1991eb79-7b27-401c-9550-106ad94683b4.png)

which when you remove the fluff gives:
```
curl 'https://demo.filestash.app/api/share/rqBAYOx' \
  -H 'Cookie: auth=Vlmr9g1cflf9KSN5OL6TXnVZSfj5E89oujaZ1ByPJVkQUVJpWkdwTIduaNU8RvAkDsPsu1frk5HbY0B1eK0-EY-PaZAab8fJYCgCdpW6Yl0DsrKT1eBtrTWG6N9oHkEtJiPrvfooi0VQ0s8mTxgZe-z4to5EMTJFLPrcrDjCBXmP;' \
  -H 'X-Requested-With: XmlHttpRequest' \
  --data-raw '{"path":"/Pictures/","id":"rqBAYOx","url":null,"users":null,"password":null,"expire":null,"can_manage_own":false,"can_share":false,"can_read":true,"can_write":false,"can_upload":false}'
```

**Comment by mickael-kerjean** [comment]
This might happen one day but as of today I don't have enough time to focus on this in my free time
