### ISSUE TITLE
Double click instead of single click

### ISSUE THREAD

**Issue by alanmilinovic** [mickael-kerjean/filestash#530]
Can you please make an option to have double click for files and folders in place, instead of single click.
Something that User can decide on their own as an option "Use double clicks to open files and directories", or global configuration for admin.

If double click option is activated, single click should be for files and folders selection and should work with Ctrl and Shift for multi selection.

Thank you.

**Comment by mickael-kerjean** [comment]
Please stop ignoring the issue template we've setup. FYI a frontend refactoring is in the backlog and if i ever get the time to get it through will have that covered.

**Comment by alanmilinovic** [comment]
Thank you for your reply. I tried to reach out to you over IRC several time, but had no response. Will stop opening issues.
Thank you.
