### ISSUE TITLE
[bug]  "CAN't LOAD"

### ISSUE THREAD

**Issue by Apollo3zehn** [mickael-kerjean/filestash#540]
# Description of the bug

When loading filestash page on Firefox Mobile in private mode the response is just a "CAN't LOAD".

# Step by step instructions to reproduce the bug

See above.

# Can you replicate that error from the demo?

Yes.

# Observed behavior

See above.

# Expected behavior

Inform the user that the app needs access to the local storage which is not available in private browsing mode.

**Comment by mickael-kerjean** [comment]
this is the same issue discussed in #581 for which a fix just got published. If something doesn't work, let's use #581 instead of this
