### ISSUE TITLE
[bug] webdav upload to nextcloud stuck a 0 bytes

### ISSUE THREAD

**Issue by shrippen** [mickael-kerjean/filestash#550]
# Description of the bug

When using the webdav connector to my nextcloud installation the uploading of files doesn't work.

# Step by step instructions to reproduce the bug

Docker installation behind caddy proxy
Docker Nextcloud Installation, current version

1. Using WebDAV Connector behind HTPASSWD
2. Using the default nextcloud webdav connection via https://domain/remote.php/dav/files/user/
3. Using a subfolder via the Path variable
4. Browsing that folder works without problems as does downloading files
5. When trying to uploading a new file no error message appears, file is created but is stuck a size of 0 bytes.

# Can you replicate that error from the demo?

yes

**Comment by Mayuresh0072** [comment]
@shrippen @mildred @xlight @darkdragon-001 @ryanpcmcquen Hello, I want to work on this issue, please assign me this issue.

**Comment by ryanpcmcquen** [comment]
@Mayuresh0072 you should start by creating a PR.

**Comment by Mayuresh0072** [comment]
Actually solving github issues is part of my college assignment, So please assign me this issue, as I need to show my progress.

**Comment by ryanpcmcquen** [comment]
The owner of the repo may be the only one with assignment rights. @mickael-kerjean can you assign this issue to @Mayuresh0072?

**Comment by mickael-kerjean** [comment]
I can't replicate this on my side, happy to look at a PR if you have one

**Comment by mickael-kerjean** [comment]
I'm closing this to cleanup the repo of issues that have no pending tasks associated to it. If someone have a way to replicate this, please comment back and we'll reopen
