### ISSUE TITLE
[bug] missing dist/jpeg_linux_amd64.bin - build_backend

### ISSUE THREAD

**Issue by devanao** [mickael-kerjean/filestash#551]
# Description of the bug

When trying to compile the backend, an error is raised 
`▶make build_backend
CGO_ENABLED=0 go build -ldflags="-extldflags=-static" -mod=vendor --tags "fts5" -o dist/filestash server/main.go
server/plugin/plg_image_thumbnail/resize_jpeg_linux_amd64.go:7:12: pattern dist/jpeg_linux_amd64.bin: no matching files found
make: *** [Makefile:13: build_backend] Error 1`

i have tried in 3 different enviroments

# Step by step instructions to reproduce the bug

follow the instructions on CONTRIBUTING.md, the error is raised on the `make build_backend` step
all the previous commands were successful

# Can you replicate that error from the demo?
No

# Observed behavior

`pattern dist/jpeg_linux_amd64.bin: no matching files found`

# Expected behavior

Build the backend

**Comment by mickael-kerjean** [comment]
As explained in our call a few days ago, this is coming from the thumbnailer which runs some custom C program. Those C programs in the default thumbnailer are precompiled in  [here](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_thumbnail/dist) and as I only have around me a raspberry pie and regular laptop was only able to compile those programs on those architecture. 

The simplest option is to use another thumbnailer like [plg_image_golang](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_golang) which is made in pure golang but is a few order of magnitude slower than the [default thumbnailer](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_thumbnail) or [plg_image_bimg](https://github.com/mickael-kerjean/filestash/tree/master/server/plugin/plg_image_bimg) which is a bit faster than plg_image_golang but slower than the default one and has a dependency on the glib
