### ISSUE TITLE
[bug] SERVER STOP RESPONDING | AWS MARKET PLACE SETUP 

### ISSUE THREAD

**Issue by helmiboussaid** [mickael-kerjean/filestash#562]
# Description of the bug

We configured Filestash from AWs market place on our VPC.
The solution works but server start not responding (ping alive but no data)when we have more than 500 users connecting in the same time to download files from SFTP.

# Step by step instructions to reproduce the bug

We recreated the VM and problem happened again.
We increased the EC2 instance size but server still unreachable and application not started

# Can you replicate that error from the demo?
No

**Comment by mickael-kerjean** [comment]
I'm closing this as we had a deeper discussion offline to support this use case. Feel free to reach back to me through support if you need any more help, we're trying not to use github issues as a support platform. Cheers, Mickael
