### ISSUE TITLE
[Feature Request] Use authentication middleware by storage backend

### ISSUE THREAD

**Issue by SirLagardere** [mickael-kerjean/filestash#579]
I'm not sure if it's possible, but it could be usefull to be able to chose an indivudual authentication method for each backend (based on label or type)
For example :
Backend S3, label "Public" : Authentication middleware => Passthrough
Backend S3, label "Private" : Authentication middleware => HTPASSWD

And thanks for this great piece of software !

**Comment by mickael-kerjean** [comment]
You'd be in custom territory as you'd need to create a custom authentication middleware to do this but yes this is possible and I've done exactly this for a company a couple weeks ago. It would look something like this:
![image](https://user-images.githubusercontent.com/13233076/227494950-14bab9e2-75c2-4e7b-be15-08ef2bb585b7.png)

Once you got the label, you can essentially do whatever you want from there and redirect to anything you want or call any of the existing plugins as well. FYI, an authentication middleware is a plugin that implements this interface: https://github.com/mickael-kerjean/filestash/blob/master/server/common/types.go#L23-L27
