### ISSUE TITLE
Feature request: Onedrive sync

### ISSUE THREAD

**Issue by Whil-** [mickael-kerjean/filestash#59]
Would be cool to see Onedrive supported as a backend in complement to the already available Dropbox and GDrive backends. Just dropping this here with the hopes of this not being to difficult to implement!

**Comment by mickael-kerjean** [comment]
Indeed, adding support for onedrive shouldn't that complicated. From my experience the burden comes when it's time to follow the vendor process to request a production api key.

I can look after it as I got some time off but pull request are welcome as well if you want to make it work. If you want to give it a try, the existing backend are [here](https://github.com/mickael-kerjean/nuage/tree/master/server/model/backend). Implementing one is just a question of adding a reference [here](https://github.com/mickael-kerjean/nuage/blob/master/server/model/files.js#L8), [here](https://github.com/mickael-kerjean/nuage/blob/master/server/model/session.js#L8) and make up a form in [the connection page](https://github.com/mickael-kerjean/nuage/blob/master/client/pages/connectpage/form.js#L316-L321)

**Comment by mickael-kerjean** [comment]
I have no plans to personally implement it this feature but would be happy to accept a pull request. we can re-open the issue if we have a volunteer for the work.
