### ISSUE TITLE
[bug] Images are not resized on preview

### ISSUE THREAD

**Issue by evstmihail** [mickael-kerjean/filestash#599]
# Images are not resized for preview

Not sure if this is actually a bug, but if you open an image for preview, the original image file is loaded, however, a link to the image has `size` parameter `...api/files/cat?path=/files/images/image_123.jpg&size=1920`, changing `size` does not affect the image. This can be reproduced on demo. The issue becomes a problem when loading huge images.

# Step by step instructions to reproduce the bug

- Navigate to a folder with images
- Open an image
- Check its original size

# Can you replicate that error from the demo?

Yes, see [this example on demo](https://demo.filestash.app/view/Pictures/IMG_20151225_120351.jpg)

# Observed behavior

The original not resized image is loaded

# Expected behavior

The image should be resized to `1920` according to the uri parameter `size=1920`.

**Comment by mickael-kerjean** [comment]
this is a something that's used by some transcoding plugin but not the default one, feel free to use one that does that or not, it's all up to the plugins
