### ISSUE TITLE
[bug] Filestash doesn't work on qutebrowser

### ISSUE THREAD

**Issue by YasserKa** [mickael-kerjean/filestash#607]
# Description of the bug

I get `Uncaught TypeError: Cannot read property 'media' of undefined` on [qutebrowser/qutebrowser: A keyboard-driven, vim-like browser based on Python and Qt.](https://github.com/qutebrowser/qutebrowser)

I apologize if this issue isn't from the side of filestash. I thought that you might give me an insight about the problem.

# Step by step instructions to reproduce the bug

Opening https://demo.filestash.app/ in qutebrowser

# Can you replicate that error from the demo?

Yes

# Observed behavior

![2023-05-16_12:18:02](https://github.com/mickael-kerjean/filestash/assets/16079479/be789648-2e9f-45eb-a1b9-5bd371e528f6)

![2023-05-16_12:20:18](https://github.com/mickael-kerjean/filestash/assets/16079479/ff1b5d52-5284-4bff-adf3-e4bf9beb7083)

**Comment by maroda** [comment]
I am getting this error when I try to record a session for a Pingdom transaction check with WPM Recorder [Version 2022.3.0 (2022.3.0.70)]. Maybe this is a display problem with the animation on login?
