### ISSUE TITLE
Connection refused behind Nginx Reverse proxy

### ISSUE THREAD

**Issue by sirNugg3ts** [mickael-kerjean/filestash#610]
I'm only getting connection refused when trying to access through a reverse proxy that I setup following [this tutorial](https://notthebe.ee/blog/easy-ssl-in-homelab-dns01/)

logs dont report anything

`2023/05/27 21:23:35 HTTP 200 POST    0.9ms /admin/api/config
2023/05/27 21:23:35 HTTP 200 GET    1.1ms /api/config
2023/05/27 21:23:38 HTTP 200 GET    0.2ms /admin/api/session
2023/05/27 21:23:43 HTTP 200 GET    0.8ms /admin/api/session
2023/05/27 21:23:48 HTTP 200 GET    0.2ms /admin/api/session
2023/05/27 21:23:53 HTTP 200 GET    0.2ms /admin/api/session
2023/05/27 21:23:58 HTTP 200 GET    0.1ms /admin/api/session
2023/05/27 21:24:03 HTTP 200 POST 1504.5ms /admin/api/session
2023/05/27 21:24:03 HTTP 200 GET    0.2ms /admin/api/session
2023/05/27 21:24:03 HTTP 200 GET    1.7ms /admin/api/config
2023/05/27 21:24:03 HTTP 200 GET    0.1ms /admin/api/session
2023/05/27 21:24:08 HTTP 200 GET    0.3ms /admin/api/session`

![image](https://github.com/mickael-kerjean/filestash/assets/28486181/70c7928b-4cc5-47c7-a1ad-80374d8d98c3)

![image](https://github.com/mickael-kerjean/filestash/assets/28486181/92716234-02e4-4bfa-baa6-05f6a8fc1c7a)

**Comment by dmorab** [comment]
In Setting/General/Host don't write internal IP 192.168.1.158:8334 but the domain name filestash.sirnugg3ts.tech, next go to https://filestash.sirnugg3ts.tech
