### ISSUE TITLE
[bug] 504 Gateway Time-out when trying to download docker-compose.yml

### ISSUE THREAD

**Issue by Stormrice** [mickael-kerjean/filestash#631]
# Description of the bug

My web browser returns "504 Gateway Time-out" when trying to download https://downloads.filestash.app/latest/docker-compose.yml as decribed in the [documentation](https://www.filestash.app/docs/install-and-upgrade/).

# Step by step instructions to reproduce the bug

Follow the standard installation documentation.

# Can you replicate that error from the demo?

No.

# Observed behavior

The docker-compose.yml file cannot be downloaded through HTTP.

# Expected behavior

The docker-compose.yml file can be downloaded through HTTP.

**Comment by joebordes** [comment]
Look at #628
Maybe an update the documentation pull request would be a good idea

**Comment by Stormrice** [comment]
Thank you
