### ISSUE TITLE
Can't download docker-compose.yml (SQLSTATE[08004])

### ISSUE THREAD

**Issue by mwllgr** [mickael-kerjean/filestash#633]
Hello, the link in the curl command from the docs is currently down: https://downloads.filestash.app/latest/docker-compose.yml

> Error : SQLSTATE[08004] [1040] Too many connections

**Comment by joebordes** [comment]
Look at #628

**Comment by mwllgr** [comment]
Ah well, thanks @joebordes! The issue's title isn't exactly the greates. Leaving this issue open for now.

**Comment by joebordes** [comment]
HTH 

https://github.com/mickael-kerjean/filestash-website/pull/41

**Comment by mickael-kerjean** [comment]
it should work now, links coming from the downloads.filestash.app are hook with some analytics to get some ideas of how many people download Filestash every month but this was down for a couple weeks and back up

**Comment by mwllgr** [comment]
Thanks! Closed.
