### ISSUE TITLE
[Feature Request] How Could I enable LDAP in free version of Filestash

### ISSUE THREAD

**Issue by believerHSP** [mickael-kerjean/filestash#661]
In Filestash, we have all standard industry relevant authentication middle-ware in its enterprise release.

Is there any provision to Integrate LDAP, SAML, OPENID to Filestash in free version. 

Please some possible ways to authenticate using free version of Filestash.

**Comment by mickael-kerjean** [comment]
No. Filestash isn't my full time job, it's a side project I would like to turn onto my main job so it can one day be better than all commercial projects out there. To do so requires both time and funding, I'm giving everything somebody interested in selfhosting might need for free but giving away enterprise tools for free as well goes against the bigger mission and that bigger mission is to be better than Dropbox, Google Drive and One Drive, it's why I wake up in the morning, it's my mission and that's what give me the force to work on this after a day at work when normal people would watch netflix instead.

If I'm ever able to work on this full time I might revisit that decision to open source absolutely everything but until that happen I need to be laser focus on giving enterprise a carrot in the hope they will financially contribute back.

**Comment by believerHSP** [comment]
Thanks for the clarity.

**Comment by camposdelima** [comment]
It already is an amazing project, @mickael-kerjean!

Congratulations on the work. I hope the project continues to grow, becomes a market leader, and, why not, helps the main contributors pay their bills.

Good luck!

**Comment by frankvoelker** [comment]
Seriously. No SSO at all in free version? This is poor. Very very greedy and poor

**Comment by mickael-kerjean** [comment]
Please enlighten me on how to make things sustainable then. I work > 80h a week on this and any junior engineer working half less in a corporate job makes multiple time my income from this
