### ISSUE TITLE
Fix polish locale

### ISSUE THREAD

**Issue by Pieshka** [mickael-kerjean/filestash#677]
Hello!
I've recently came across Filestash while I was searching for a simple frontend for my SMB server. Everything is working fine, but I've noticed that the polish locale is slightly incorrect in some places. I didn't find a language contribution guidelines nor template files, so I've took `pl.json` from one of the directories and fixed the translation. I don't know if this is sufficient and if there are any other files I need to translate but I'll attach this corrected file here to be included in Filestash. If necessary I can create a pull request.

Some lines are translated slightly different than the json key might suggest. E.g. "UPLOADER" should be "Przesyłający", but It's used in context where "Tylko wysyłanie" (in English: "Only uploading allowed") is more appropriate (that is when creating shared link). I think it's good to point that out to avoid issues when reusing json keys in places where the meaning will be different.

[pl.json](https://github.com/mickael-kerjean/filestash/files/14550398/pl.json)

**Comment by mickael-kerjean** [comment]
Can you make a PR for this?
