### ISSUE TITLE
Unable to paste text into the editor using CTRL-V

### ISSUE THREAD

**Issue by goldmont** [mickael-kerjean/filestash#681]
# Description of the bug

Hi,

I'm unable to paste text into the editor using CTRL-V shortcut. I can only do it from the context menu using the mouse. Is anyone else experiencing the same issue?

# Expected behavior

Being able to paste text into the editor using the keyboard.

Thanks.

**Comment by ptah-alexs** [comment]
Change in settings, editor option from emacs to base.
