### ISSUE TITLE
[bug] fresh instance of filestash setup page gives an error

### ISSUE THREAD

**Issue by nahsi** [mickael-kerjean/filestash#706]
# Description of the bug

Cannot setup a fresh instance of filestash

# Step by step instructions to reproduce the bug

```shell
mkdir filestash && cd filestash
curl -O https://downloads.filestash.app/latest/docker-compose.yml
docker-compose up -d
```
and then go to http://localhost:8334

# Can you replicate that error from the demo?

Nope. Only happens on fresh install.

# Observed behavior

```
The requested module '../../model/config.js' does not provide an export named 'get'
```

# Expected behavior

Fresh instance of filestash can be setup

**Comment by uwu64** [comment]
I'm also experiencing this issue. I followed the [install guide](https://www.filestash.app/docs/install-and-upgrade/?release=agpl) with the same commands as @nahsi 

Some more info - I get the same error message as above when using Chromium, but on Firefox the error message is `ambiguous indirect export: get`

Going to `http://address:8334/about` seems to work fine

**Comment by zemzema** [comment]
Same problem here!

**Comment by uwu64** [comment]
Happy to report that it seems to work as of `latest` updated 8 hours ago. I did the [upgrade procedure](https://www.filestash.app/docs/install-and-upgrade/?release=agpl) and was able to set admin password and begin configuring Filestash.

**Comment by nahsi** [comment]
Since it works I think it can be closed.
@uwu64 you mind creating another issue for it?
