### ISSUE TITLE
Feature Request: Show the TODO states in the agenda view.

### ISSUE THREAD

**Issue by Nebucatnetzer** [mickael-kerjean/filestash#73]
Currently Nuage doesn't show the TODO states in the agenda view. For prioratising it would be good to know if the task has a WAITING state or a next state.

**Comment by mickael-kerjean** [comment]
Currently you can use the search to find the state you're interested in.
While creating the agenda, I tried to make it fit in 1 line, if it doesn't fit the content is simply cut with `...`. Considering the small amount of screen space available on mobile, I'm not sure how it can be done. Feel free to share if you have any ideas

**Comment by Nebucatnetzer** [comment]
Hm good point. Maybe we could group them under a heading?

**Comment by Nebucatnetzer** [comment]
Speaking about the agenda view, how long is the time range you are displaying?

**Comment by mickael-kerjean** [comment]
Currently, the org document is parsed and get all the [timestamp](https://orgmode.org/manual/Timestamps.html) it can find. Those are display in the screen with the following logic:
- headlines are shown if there's an active timestamp attach to them and considered done (aka not one of "TODO" "NEXT" "DOING" "WAITING" "PENDING")
- When those active timestamp have a SCHEDULE or DEADLINE keywork attached, both are shown (with an icon to distinguish when it's SCHEDULE or a DEADLINE).
- when it comes to recurrent event, those are shown at least once and displayed in the agenda for 30 days

**Comment by Nebucatnetzer** [comment]
Ah okay.
I just realized that I've split my agenda into multiple files. I moved the tasks into the main file and now it shows the same tasks as in Emacs.

**Comment by mickael-kerjean** [comment]
Currently, there's no logic in place to parse all your org documents, your agenda and todo only relates to the currently open org document. That's not the default behavior of emacs but it would require quite a bit of work to make it behave like emacs and to be honest, I like it better that way (separation of concern, different files, different things)

**Comment by Nebucatnetzer** [comment]
Makes I wouldn't change it either.
I would like to use Nauge anyway mostly to add new tasks or do quick edits and not really to work with the agenda or so.

**Comment by ScottyMills13** [comment]
I just saw your reddit post and this is very needed.  Ill see if i can adjust the UI and add the option for both layouts ;) 
Love the logo as well

**Comment by mickael-kerjean** [comment]
That's great to hear, I'm quite busy at the moment developping new features that should land soon ([photo management](https://github.com/mickael-kerjean/nuage/wiki/ROADMAP-for-Release-0.2:-Photo-Management))
