### ISSUE TITLE
[bug] Onlyoffice no longer opens on newest version

### ISSUE THREAD

**Issue by bjornclauw** [mickael-kerjean/filestash#734]
On the latest docker image, i can no longer use openoffice (screen stays blank)
![image](https://github.com/user-attachments/assets/a9e5440d-64f8-47cd-acef-83b86865d16e)

getting a script error in google chrome -> expecting a string instead of a boolean.
![image](https://github.com/user-attachments/assets/18d0645d-a62b-409d-a072-2361f3f2b05b)

https://github.com/mickael-kerjean/filestash/blame/bbd01070fb295c40a1884ce5c71f901b728113dd/server/plugin/plg_editor_onlyoffice/index.go#L368
Not very proficient with Go, but I assume replacing %t with %s would fix the issue.

**Comment by homegrownhrbs** [comment]
same issue for me

**Comment by bjornclauw** [comment]
Missed this pull request: https://github.com/mickael-kerjean/filestash/pull/724 (this should resolve the issue)

**Comment by mickael-kerjean** [comment]
The issue is from stuff that got introduced in only office v7.2 and breaks compatibility. If you upgrade the docker-compose, it should work fine with the above commit.
