### ISSUE TITLE
[bug] Filtering prevents deleting

### ISSUE THREAD

**Issue by rgaudin** [mickael-kerjean/filestash#788]
# Description of the bug

Only tested over WebDAV.
When using the filter in the file listing, the rows dont have the edit/remove icons.
When clearing the filter, the rows that were displayed when the filter applied have lost their edit/remove icons while other rows are normal.

# Step by step instructions to reproduce the bug

1. check by hovering over the list of files that edit/remove icons are present
2. use the filter that matches one or more rows
3. confirm the icons are not present in filter mode
4. clear filter
5. confirm that once-filtered rows have lost edit/remove icons

# Can you replicate that error from the demo?

demo is 502 ATM

# Observed behavior

- No edit/remove icons when filtering
- No edit/remove icons post-filtering on once-filtered rows

# Expected behavior

- edit/remove icons when filtering: that's debatable ; maybe it's a feature?
- edit/remove icons post-filtering everywhere

**Comment by mickael-kerjean** [comment]
I'm not entirely clear what this is about yet but the demo is back online. Can you send screenshots of that behavior?

**Comment by mickael-kerjean** [comment]
The version of the frontend is the old one that is gonna be deprecated. To access the new version, just use the CANARY env variable as documented [here](https://www.filestash.app/docs/install-and-upgrade/#installation)

**Comment by rgaudin** [comment]
Indeed ; thanks for the tip!

May I ask why we cant do multiple selection on a filter? And thus cant use a filter to find and delete files.

**Comment by mickael-kerjean** [comment]
Happy to hear about any improvement on the new frontend selection. At the moment, you can select via shift and ctrl click to do long selection, etc ... pretty much all the operation from any regular file manager should be supported. If I missed something, happy to hear about it.

**Comment by rgaudin** [comment]
Well ctrl-click is right-click by default on macOS so that renders it impossible on that platform. Most webapps map command key on mac instead of ctrl.
