### ISSUE TITLE
Consider automated builds at https://hub.docker.com

### ISSUE THREAD

**Issue by bdillahu** [mickael-kerjean/filestash#86]
I use unRaid for my docker host and it has automated tools available to pull docker images from hub.docker.com - I know others use that repository in other setups.

I created my own fork and a build at hub.docker.com and it works fine (does require moving the Dockerfile to the root, but otherwise no changes)... I'm fine with doing this, but thought I would mention the possibility so that you could have one under your "control" - once it's set it auto-builds when you update github, so I don't think it would be a lot of maintenance.

Just a suggestion... thanks for a great tool!

**Comment by mickael-kerjean** [comment]
Wow, it's actually awesome to see so many people using it!

A few things here:
- autobuild: for now I got CI (travis) to create the build and publishing the artifact [here](https://hub.docker.com/r/machines/nuage/) as I had no idea docker hub could do it automatically. I'm working on the automatic build from github using docker hub as we speak
- I'm not sure to understand, the unraid thinghy. What is needed to get the automatic pull from the docker hub? Do you mind to say which tool does that? I've never heard of such a thing and it looks awesome

**Comment by bdillahu** [comment]
Your autobuild in hub.docker.com looks great... works fine.

Will also need (or I suggest, anyhow :-)) putting the nuage-transform one there. That lets us pull them both and have at it.

For the unRaid - that is more just background information on why I wanted this... unRaid is kind of a "distribution" that is set up for NAS type storage, but it will also host VMs and Docker images with a nice web GUI. Instead of having to load them by hand (command line), if a docker is on hub.docker.com it's a point and click to get the docker loaded.

So I just did the load from your hub.docker.com on unRaid and it worked fine, so what you did satisfied that need of mine.

Appreciate it.

**Comment by mickael-kerjean** [comment]
nuage_transform will be [here](https://hub.docker.com/r/mickaelkerjean/nuage_transform) once the build complete. I'll make up some test and update the relevant code to ensure everything is pointing there. I guess it's cleaner to rely on the docker hub automated build than [this](https://hub.docker.com/r/machines/nuage/)

**Comment by bdillahu** [comment]
Was working great on the old codebase, but looks like the build is failing in the "new world" - just wanted to point it out since I don't know that you directly use it.

**Comment by mickael-kerjean** [comment]
I use [this one](https://hub.docker.com/r/machines/nuage/). For some reasons I have no idea of yet, the build is working fine from my laptop but the very same Dockerfile fails in the docker hub .... That's a very weird mistery as of now and trying to make a proper build from the docker hub is a pain as their build machine is awfully slow (raspberry pie kind of slow)

**Comment by bdillahu** [comment]
Yep, after I left that comment I found your "machines/nuage" and just got it going... looks really, really nice. And I love the auto-load on the config file :-)

**Comment by RaraAvis8** [comment]
It also would be nice to have tags for (future) versions on images on docker hub. To be able to build reproducible setup and to know what version is currently installed etc.

**Comment by mickael-kerjean** [comment]
To conclude the ticket:
1. link to the official docker image: https://hub.docker.com/r/machines/filestash
2. link to the automated build that's created directly by the docker hub website: https://hub.docker.com/r/mickaelkerjean/filestash
    I don't recommend using this image because this build is getting is created out of CI, with absolutly no test. To be use by people who want to live on the edge
3. future version will be tagged
4. Build are already reproducible: see [the build file](https://github.com/mickael-kerjean/filestash/blob/master/.drone.yml#L87-L98)
