### ISSUE TITLE
Feature Request: Show links in the pretty format

### ISSUE THREAD

**Issue by Nebucatnetzer** [mickael-kerjean/filestash#88]
It would be nice if the links would get displayed in the pretty format and get converted to normal text when one deletes a bracket like it does in org-mode.

**Comment by mickael-kerjean** [comment]
As for now I'm currently deep inside a backend [rewrite](https://github.com/mickael-kerjean/nuage/issues/87) so I guess a pull request would make things come live much faster.

This is the kind of things that can be tricky to implement from CodeMirror (the text editor nuage is integrating org mode in) but I can think of one approach that might work:

Currently:
`[[http://google.com][google]]`become `<span class="cm-org-url">[[http://google.com][google]]</span>`
It might work to have it split in multiple chunk and hide those chunk via CSS depending where the cursor is located (cursor on a link: show all the links chunks | cursor not on a link: hide those chunks)

To make it work, we would need to change a few things:
- how links are parsed before being rendered by Codemirror: [here](https://github.com/mickael-kerjean/nuage/blob/0a60945c3d586a99b9cb602ce4c7da410c081200/client/pages/viewerpage/editor/orgmode.js#L19) 
- add some logic to show/hide the links chunks depending on how the cursor is positionned: see [here](https://github.com/mickael-kerjean/nuage/blob/0a60945c3d586a99b9cb602ce4c7da410c081200/client/pages/viewerpage/editor/orgmode.js#L121-L122)

**Comment by Nebucatnetzer** [comment]
I put it on my list, however I don't think I'll have time anytime soon.
I'm currently in my last year studying with a thesis coming up :)

**Comment by mickael-kerjean** [comment]
No worries, I'll look after it once the migration is complete `:)`
